using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MVC.Models;

namespace MVC
{
    public class SampleData
    {
        public static void Initialize(UniversityContext context)
        {
            if (!context.Courses.Any())
            {
                context.Courses.AddRange(
                    new Course
                    {
                        Name = "Математика",
                        Description = "Царица наук"
                    },
                    new Course
                    {
                        Name = "Физика",
                        Description = "Основа всего"
                    },
                    new Course
                    {
                        Name = "Физкультура",
                        Description = "В здоровом теле - здоровый дух"
                    },
                    new Course
                    {
                        Name = "История",
                        Description = "У того, кто не знает прошлого - нет будущего"
                    }
                );
                context.SaveChanges();
            }

            if (!context.Groups.Any())
            {
                context.Groups.AddRange(
                    new Group { CourseId = 1, Name = "КБ-101"},
                    new Group { CourseId = 2, Name = "ЛП-102"},
                    new Group { CourseId = 3, Name = "РР-103"},
                    new Group { CourseId = 2, Name = "РС-104"},
                    new Group { CourseId = 1, Name = "РА-105"},
                    new Group { CourseId = 3, Name = "РА-202"},
                    new Group { CourseId = 4, Name = "АР-203"},
                    new Group { CourseId = 4, Name = "РА-204"},
                    new Group { CourseId = 1, Name = "НК-205"},
                    new Group { CourseId = 3, Name = "БК-301"},
                    new Group { CourseId = 4, Name = "РА-353"},
                    new Group { CourseId = 1, Name = "РА-333"},
                    new Group { CourseId = 3, Name = "ВП-322"},
                    new Group { CourseId = 3, Name = "УЦ-311"},
                    new Group { CourseId = 1, Name = "МВ-354"},
                    new Group { CourseId = 3, Name = "РА-344"}
                );
                context.SaveChanges();
            }

            if (!context.Students.Any())
            {
                context.Students.AddRange(
                    new Student { GroupId = 1, FirstName = "Алексей", LastName = "Сергеев" },
                    new Student { GroupId = 1, FirstName = "Тимур", LastName = "Хохлов" },
                    new Student { GroupId = 1, FirstName = "Савелий", LastName = "Гаврилов" },
                    new Student { GroupId = 1, FirstName = "Виктор", LastName = "Бобров" },
                    new Student { GroupId = 1, FirstName = "Стефания", LastName = "Петухова" },
                    new Student { GroupId = 1, FirstName = "Глеб", LastName = "Петров" },
                    new Student { GroupId = 1, FirstName = "Степан", LastName = "Казаков" },
                    new Student { GroupId = 1, FirstName = "Макар", LastName = "Суханов" },
                    new Student { GroupId = 1, FirstName = "Кира", LastName = "Кононова" },
                    new Student { GroupId = 1, FirstName = "Денис", LastName = "Макаров" },
                    new Student { GroupId = 1, FirstName = "Никита", LastName = "Грачев" },
                    new Student { GroupId = 1, FirstName = "Дмитрий", LastName = "Уткин" },
                    new Student { GroupId = 1, FirstName = "Мирослава", LastName = "Егорова" },
                    new Student { GroupId = 1, FirstName = "Дарья", LastName = "Фокина" },
                    new Student { GroupId = 1, FirstName = "Любовь", LastName = "Васильева" },
                    new Student { GroupId = 1, FirstName = "Иван", LastName = "Егоров" },
                    new Student { GroupId = 1, FirstName = "Полина", LastName = "Колесникова" },
                    new Student { GroupId = 1, FirstName = "София", LastName = "Кузнецова" },
                    new Student { GroupId = 1, FirstName = "Юрий", LastName = "Севастьянов" },
                    new Student { GroupId = 1, FirstName = "Максим", LastName = "Касаткин" },
                    new Student { GroupId = 1, FirstName = "Мария", LastName = "Нечаева" },
                    new Student { GroupId = 1, FirstName = "Нина", LastName = "Волкова" },
                    new Student { GroupId = 1, FirstName = "Василиса", LastName = "Алексеева" },
                    new Student { GroupId = 1, FirstName = "Матвей", LastName = "Кошелев" },
                    new Student { GroupId = 1, FirstName = "Ника", LastName = "Громова" },
                    new Student { GroupId = 1, FirstName = "Анна", LastName = "Панова" },
                    new Student { GroupId = 1, FirstName = "Елизавета", LastName = "Зубкова" },
                    new Student { GroupId = 1, FirstName = "Татьяна", LastName = "Баранова" },
                    new Student { GroupId = 1, FirstName = "Эмин", LastName = "Антипов" },
                    new Student { GroupId = 1, FirstName = "Яна", LastName = "Белякова" },
                    new Student { GroupId = 2, FirstName = "Вера", LastName = "Михайлова" },
                    new Student { GroupId = 2, FirstName = "Александр", LastName = "Копылов" },
                    new Student { GroupId = 2, FirstName = "Тимофей", LastName = "Зайцев" },
                    new Student { GroupId = 2, FirstName = "Влада", LastName = "Кузнецова" },
                    new Student { GroupId = 2, FirstName = "София", LastName = "Костина" },
                    new Student { GroupId = 2, FirstName = "Анастасия", LastName = "Виноградова" },
                    new Student { GroupId = 2, FirstName = "Лев", LastName = "Кононов" },
                    new Student { GroupId = 2, FirstName = "Эмир", LastName = "Миронов" },
                    new Student { GroupId = 2, FirstName = "Екатерина", LastName = "Митрофанова" },
                    new Student { GroupId = 2, FirstName = "Алина", LastName = "Кузнецова" },
                    new Student { GroupId = 2, FirstName = "Мария", LastName = "Смирнова" },
                    new Student { GroupId = 2, FirstName = "Андрей", LastName = "Федоров" },
                    new Student { GroupId = 2, FirstName = "Максим", LastName = "Барсуков" },
                    new Student { GroupId = 2, FirstName = "Анна", LastName = "Лаптева" },
                    new Student { GroupId = 2, FirstName = "Матвей", LastName = "Лебедев" },
                    new Student { GroupId = 2, FirstName = "Михаил", LastName = "Калмыков" },
                    new Student { GroupId = 2, FirstName = "Эмилия", LastName = "Макарова" },
                    new Student { GroupId = 2, FirstName = "Марьям", LastName = "Никулина" },
                    new Student { GroupId = 2, FirstName = "Мирон", LastName = "Романов" },
                    new Student { GroupId = 2, FirstName = "Стефания", LastName = "Горбунова" },
                    new Student { GroupId = 2, FirstName = "Марьяна", LastName = "Алексеева" },
                    new Student { GroupId = 2, FirstName = "Александр", LastName = "Крючков" },
                    new Student { GroupId = 2, FirstName = "Милана", LastName = "Гусева" },
                    new Student { GroupId = 2, FirstName = "Кирилл", LastName = "Андреев" },
                    new Student { GroupId = 2, FirstName = "Мария", LastName = "Ефимова" },
                    new Student { GroupId = 2, FirstName = "Александр", LastName = "Власов" },
                    new Student { GroupId = 2, FirstName = "Валерия", LastName = "Афанасьева" },
                    new Student { GroupId = 2, FirstName = "Максим", LastName = "Кузин" },
                    new Student { GroupId = 2, FirstName = "Ксения", LastName = "Родина" },
                    new Student { GroupId = 2, FirstName = "Вероника", LastName = "Мальцева" },
                    new Student { GroupId = 3, FirstName = "Данил", LastName = "Вишневский" },
                    new Student { GroupId = 3, FirstName = "Василиса", LastName = "Федорова" },
                    new Student { GroupId = 3, FirstName = "Ксения", LastName = "Ефимова" },
                    new Student { GroupId = 3, FirstName = "Ева", LastName = "Семенова" },
                    new Student { GroupId = 3, FirstName = "Ульяна", LastName = "Лазарева" },
                    new Student { GroupId = 3, FirstName = "Артур", LastName = "Нечаев" },
                    new Student { GroupId = 3, FirstName = "Алиса", LastName = "Романова" },
                    new Student { GroupId = 3, FirstName = "Полина", LastName = "Романова" },
                    new Student { GroupId = 3, FirstName = "Эмилия", LastName = "Волкова" },
                    new Student { GroupId = 3, FirstName = "Тимур", LastName = "Романов" },
                    new Student { GroupId = 3, FirstName = "Анна", LastName = "Мешкова" },
                    new Student { GroupId = 3, FirstName = "Мирослава", LastName = "Ларина" },
                    new Student { GroupId = 3, FirstName = "Иван", LastName = "Майоров" },
                    new Student { GroupId = 3, FirstName = "Антон", LastName = "Никитин" },
                    new Student { GroupId = 3, FirstName = "Максим", LastName = "Кузнецов" },
                    new Student { GroupId = 3, FirstName = "Оливия", LastName = "Калашникова" },
                    new Student { GroupId = 3, FirstName = "Никита", LastName = "Иванов" },
                    new Student { GroupId = 3, FirstName = "Софья", LastName = "Фролова" },
                    new Student { GroupId = 3, FirstName = "Дмитрий", LastName = "Морозов" },
                    new Student { GroupId = 3, FirstName = "Глеб", LastName = "Зайцев" },
                    new Student { GroupId = 3, FirstName = "Екатерина", LastName = "Цветкова" },
                    new Student { GroupId = 3, FirstName = "Владислав", LastName = "Коротков" },
                    new Student { GroupId = 3, FirstName = "Софья", LastName = "Грачева" },
                    new Student { GroupId = 3, FirstName = "Ева", LastName = "Новикова" },
                    new Student { GroupId = 3, FirstName = "Милана", LastName = "Калашникова" },
                    new Student { GroupId = 3, FirstName = "Варвара", LastName = "Антонова" },
                    new Student { GroupId = 3, FirstName = "Кирилл", LastName = "Гаврилов" },
                    new Student { GroupId = 3, FirstName = "Михаил", LastName = "Кочетков" },
                    new Student { GroupId = 3, FirstName = "Вероника", LastName = "Филиппова" },
                    new Student { GroupId = 3, FirstName = "Дмитрий", LastName = "Антонов" },
                    new Student { GroupId = 4, FirstName = "Егор", LastName = "Волков" },
                    new Student { GroupId = 4, FirstName = "Тимур", LastName = "Морозов" },
                    new Student { GroupId = 4, FirstName = "Глеб", LastName = "Денисов" },
                    new Student { GroupId = 4, FirstName = "Фёдор", LastName = "Филимонов" },
                    new Student { GroupId = 4, FirstName = "Анна", LastName = "Одинцова" },
                    new Student { GroupId = 4, FirstName = "Варвара", LastName = "Пименова" },
                    new Student { GroupId = 4, FirstName = "Тимур", LastName = "Шилов" },
                    new Student { GroupId = 4, FirstName = "Мария", LastName = "Пименова" },
                    new Student { GroupId = 4, FirstName = "Марк", LastName = "Лавров" },
                    new Student { GroupId = 4, FirstName = "Тимофей", LastName = "Дмитриев" },
                    new Student { GroupId = 4, FirstName = "Елизавета", LastName = "Николаева" },
                    new Student { GroupId = 4, FirstName = "Валерия", LastName = "Иванова" },
                    new Student { GroupId = 4, FirstName = "Богдан", LastName = "Рыжов" },
                    new Student { GroupId = 4, FirstName = "Виктория", LastName = "Сергеева" },
                    new Student { GroupId = 4, FirstName = "Зоя", LastName = "Швецова" },
                    new Student { GroupId = 4, FirstName = "Мария", LastName = "Морозова" },
                    new Student { GroupId = 4, FirstName = "Степан", LastName = "Егоров" },
                    new Student { GroupId = 4, FirstName = "Яна", LastName = "Кудрявцева" },
                    new Student { GroupId = 4, FirstName = "Савва", LastName = "Крылов" },
                    new Student { GroupId = 4, FirstName = "Егор", LastName = "Андреев" },
                    new Student { GroupId = 4, FirstName = "Глеб", LastName = "Поляков" },
                    new Student { GroupId = 4, FirstName = "Амина", LastName = "Николаева" },
                    new Student { GroupId = 4, FirstName = "Мирон", LastName = "Воробьев" },
                    new Student { GroupId = 4, FirstName = "Владислав", LastName = "Коровин" },
                    new Student { GroupId = 4, FirstName = "Анна", LastName = "Беляева" },
                    new Student { GroupId = 4, FirstName = "Дмитрий", LastName = "Симонов" },
                    new Student { GroupId = 4, FirstName = "София", LastName = "Попова" },
                    new Student { GroupId = 4, FirstName = "Лев", LastName = "Алексеев" },
                    new Student { GroupId = 4, FirstName = "Анна", LastName = "Романова" },
                    new Student { GroupId = 4, FirstName = "Даниил", LastName = "Пантелеев" },
                    new Student { GroupId = 5, FirstName = "Александра", LastName = "Высоцкая" },
                    new Student { GroupId = 5, FirstName = "Фёдор", LastName = "Левин" },
                    new Student { GroupId = 5, FirstName = "Олеся", LastName = "Симонова" },
                    new Student { GroupId = 5, FirstName = "Вероника", LastName = "Пахомова" },
                    new Student { GroupId = 5, FirstName = "Макар", LastName = "Самсонов" },
                    new Student { GroupId = 5, FirstName = "Юрий", LastName = "Николаев" },
                    new Student { GroupId = 5, FirstName = "Майя", LastName = "Дмитриева" },
                    new Student { GroupId = 5, FirstName = "Кирилл", LastName = "Большаков" },
                    new Student { GroupId = 5, FirstName = "Милана", LastName = "Карасева" },
                    new Student { GroupId = 5, FirstName = "Олег", LastName = "Иванов" },
                    new Student { GroupId = 5, FirstName = "Артём", LastName = "Киселев" },
                    new Student { GroupId = 5, FirstName = "Стефания", LastName = "Данилова" },
                    new Student { GroupId = 5, FirstName = "Пётр", LastName = "Михайлов" },
                    new Student { GroupId = 5, FirstName = "Сафия", LastName = "Прохорова" },
                    new Student { GroupId = 5, FirstName = "Оливия", LastName = "Яковлева" },
                    new Student { GroupId = 5, FirstName = "Анастасия", LastName = "Матвеева" },
                    new Student { GroupId = 5, FirstName = "Анна", LastName = "Карасева" },
                    new Student { GroupId = 5, FirstName = "Даниил", LastName = "Климов" },
                    new Student { GroupId = 5, FirstName = "Никита", LastName = "Громов" },
                    new Student { GroupId = 5, FirstName = "Ксения", LastName = "Васильева" },
                    new Student { GroupId = 5, FirstName = "Маргарита", LastName = "Михайлова" },
                    new Student { GroupId = 5, FirstName = "Алина", LastName = "Старостина" },
                    new Student { GroupId = 5, FirstName = "Мирон", LastName = "Щербаков" },
                    new Student { GroupId = 5, FirstName = "Тимур", LastName = "Титов" },
                    new Student { GroupId = 5, FirstName = "Марьяна", LastName = "Гришина" },
                    new Student { GroupId = 5, FirstName = "Лука", LastName = "Виноградов" },
                    new Student { GroupId = 5, FirstName = "Артём", LastName = "Минаев" },
                    new Student { GroupId = 5, FirstName = "Пётр", LastName = "Ермаков" },
                    new Student { GroupId = 5, FirstName = "Ольга", LastName = "Ковалева" },
                    new Student { GroupId = 5, FirstName = "Есения", LastName = "Шарова" },
                    new Student { GroupId = 6, FirstName = "Марина", LastName = "Соболева" },
                    new Student { GroupId = 6, FirstName = "Марсель", LastName = "Галкин" },
                    new Student { GroupId = 6, FirstName = "Дмитрий", LastName = "Рубцов" },
                    new Student { GroupId = 6, FirstName = "Валерия", LastName = "Субботина" },
                    new Student { GroupId = 6, FirstName = "Марк", LastName = "Александров" },
                    new Student { GroupId = 6, FirstName = "Владимир", LastName = "Муратов" },
                    new Student { GroupId = 6, FirstName = "Мария", LastName = "Дегтярева" },
                    new Student { GroupId = 6, FirstName = "Глеб", LastName = "Трофимов" },
                    new Student { GroupId = 6, FirstName = "Милана", LastName = "Семенова" },
                    new Student { GroupId = 6, FirstName = "Виктория", LastName = "Золотова" },
                    new Student { GroupId = 6, FirstName = "Михаил", LastName = "Зимин" },
                    new Student { GroupId = 6, FirstName = "Николай", LastName = "Марков" },
                    new Student { GroupId = 6, FirstName = "Мария", LastName = "Островская" },
                    new Student { GroupId = 6, FirstName = "Мирон", LastName = "Цветков" },
                    new Student { GroupId = 6, FirstName = "Ангелина", LastName = "Островская" },
                    new Student { GroupId = 6, FirstName = "Варвара", LastName = "Попова" },
                    new Student { GroupId = 6, FirstName = "Максим", LastName = "Морозов" },
                    new Student { GroupId = 6, FirstName = "Александр", LastName = "Егоров" },
                    new Student { GroupId = 6, FirstName = "Ульяна", LastName = "Голубева" },
                    new Student { GroupId = 6, FirstName = "Диана", LastName = "Юдина" },
                    new Student { GroupId = 6, FirstName = "Иван", LastName = "Авдеев" },
                    new Student { GroupId = 6, FirstName = "Ника", LastName = "Сидорова" },
                    new Student { GroupId = 6, FirstName = "Никита", LastName = "Хохлов" },
                    new Student { GroupId = 6, FirstName = "Дмитрий", LastName = "Мальцев" },
                    new Student { GroupId = 6, FirstName = "Анастасия", LastName = "Егорова" },
                    new Student { GroupId = 6, FirstName = "Лев", LastName = "Кочетков" },
                    new Student { GroupId = 6, FirstName = "Матвей", LastName = "Егоров" },
                    new Student { GroupId = 6, FirstName = "Лейла", LastName = "Макарова" },
                    new Student { GroupId = 6, FirstName = "Лев", LastName = "Николаев" },
                    new Student { GroupId = 6, FirstName = "Борис", LastName = "Меркулов" },
                    new Student { GroupId = 7, FirstName = "Тимофей", LastName = "Васильев" },
                    new Student { GroupId = 7, FirstName = "Александр", LastName = "Воронин" },
                    new Student { GroupId = 7, FirstName = "Александра", LastName = "Михайлова" },
                    new Student { GroupId = 7, FirstName = "Василиса", LastName = "Гордеева" },
                    new Student { GroupId = 7, FirstName = "Таисия", LastName = "Гришина" },
                    new Student { GroupId = 7, FirstName = "Лидия", LastName = "Коновалова" },
                    new Student { GroupId = 7, FirstName = "Максим", LastName = "Сурков" },
                    new Student { GroupId = 7, FirstName = "Софья", LastName = "Свешникова" },
                    new Student { GroupId = 7, FirstName = "Иван", LastName = "Журавлев" },
                    new Student { GroupId = 7, FirstName = "Григорий", LastName = "Макаров" },
                    new Student { GroupId = 7, FirstName = "Лука", LastName = "Бородин" },
                    new Student { GroupId = 7, FirstName = "Вероника", LastName = "Комарова" },
                    new Student { GroupId = 7, FirstName = "Иван", LastName = "Харитонов" },
                    new Student { GroupId = 7, FirstName = "Варвара", LastName = "Токарева" },
                    new Student { GroupId = 7, FirstName = "Григорий", LastName = "Андреев" },
                    new Student { GroupId = 7, FirstName = "Макар", LastName = "Иванов" },
                    new Student { GroupId = 7, FirstName = "Александра", LastName = "Шаповалова" },
                    new Student { GroupId = 7, FirstName = "Иван", LastName = "Крылов" },
                    new Student { GroupId = 7, FirstName = "Арина", LastName = "Горшкова" },
                    new Student { GroupId = 7, FirstName = "Артём", LastName = "Коротков" },
                    new Student { GroupId = 7, FirstName = "Евгения", LastName = "Скворцова" },
                    new Student { GroupId = 7, FirstName = "Анна", LastName = "Климова" },
                    new Student { GroupId = 7, FirstName = "Эмир", LastName = "Кукушкин" },
                    new Student { GroupId = 7, FirstName = "Иван", LastName = "Соловьев" },
                    new Student { GroupId = 7, FirstName = "Сергей", LastName = "Зайцев" },
                    new Student { GroupId = 7, FirstName = "Мила", LastName = "Иванова" },
                    new Student { GroupId = 7, FirstName = "Варвара", LastName = "Горбачева" },
                    new Student { GroupId = 7, FirstName = "Ксения", LastName = "Матвеева" },
                    new Student { GroupId = 7, FirstName = "Максим", LastName = "Федотов" },
                    new Student { GroupId = 7, FirstName = "Аделя", LastName = "Ефимова" },
                    new Student { GroupId = 8, FirstName = "Валерия", LastName = "Герасимова" },
                    new Student { GroupId = 8, FirstName = "Гордей", LastName = "Иванов" },
                    new Student { GroupId = 8, FirstName = "Александр", LastName = "Высоцкий" },
                    new Student { GroupId = 8, FirstName = "Анна", LastName = "Полякова" },
                    new Student { GroupId = 8, FirstName = "Матвей", LastName = "Черкасов" },
                    new Student { GroupId = 8, FirstName = "Полина", LastName = "Борисова" },
                    new Student { GroupId = 8, FirstName = "Тимофей", LastName = "Козлов" },
                    new Student { GroupId = 8, FirstName = "Степан", LastName = "Андреев" },
                    new Student { GroupId = 8, FirstName = "Дарья", LastName = "Горбунова" },
                    new Student { GroupId = 8, FirstName = "Степан", LastName = "Крылов" },
                    new Student { GroupId = 8, FirstName = "Диана", LastName = "Соколова" },
                    new Student { GroupId = 8, FirstName = "Екатерина", LastName = "Алексеева" },
                    new Student { GroupId = 8, FirstName = "Маргарита", LastName = "Малышева" },
                    new Student { GroupId = 8, FirstName = "Виктор", LastName = "Шевцов" },
                    new Student { GroupId = 8, FirstName = "Вера", LastName = "Любимова" },
                    new Student { GroupId = 8, FirstName = "Сафия", LastName = "Павлова" },
                    new Student { GroupId = 8, FirstName = "Максим", LastName = "Белов" },
                    new Student { GroupId = 8, FirstName = "Лев", LastName = "Воронцов" },
                    new Student { GroupId = 8, FirstName = "Маргарита", LastName = "Седова" },
                    new Student { GroupId = 8, FirstName = "Алина", LastName = "Ершова" },
                    new Student { GroupId = 8, FirstName = "Ярослав", LastName = "Зайцев" },
                    new Student { GroupId = 8, FirstName = "Артём", LastName = "Комаров" },
                    new Student { GroupId = 8, FirstName = "Марк", LastName = "Вдовин" },
                    new Student { GroupId = 8, FirstName = "Майя", LastName = "Сорокина" },
                    new Student { GroupId = 8, FirstName = "Михаил", LastName = "Ефимов" },
                    new Student { GroupId = 8, FirstName = "Артём", LastName = "Скворцов" },
                    new Student { GroupId = 8, FirstName = "Павел", LastName = "Новиков" },
                    new Student { GroupId = 8, FirstName = "Алина", LastName = "Шульгина" },
                    new Student { GroupId = 8, FirstName = "Кирилл", LastName = "Михеев" },
                    new Student { GroupId = 8, FirstName = "Злата", LastName = "Ермакова" },
                    new Student { GroupId = 9, FirstName = "Варвара", LastName = "Смирнова" },
                    new Student { GroupId = 9, FirstName = "Михаил", LastName = "Иванов" },
                    new Student { GroupId = 9, FirstName = "Артур", LastName = "Семенов" },
                    new Student { GroupId = 9, FirstName = "Вячеслав", LastName = "Климов" },
                    new Student { GroupId = 9, FirstName = "Артём", LastName = "Максимов" },
                    new Student { GroupId = 9, FirstName = "Эмма", LastName = "Тихонова" },
                    new Student { GroupId = 9, FirstName = "Максим", LastName = "Иванов" },
                    new Student { GroupId = 9, FirstName = "Максим", LastName = "Мальцев" },
                    new Student { GroupId = 9, FirstName = "Александр", LastName = "Софронов" },
                    new Student { GroupId = 9, FirstName = "Марк", LastName = "Ильин" },
                    new Student { GroupId = 9, FirstName = "Давид", LastName = "Александров" },
                    new Student { GroupId = 9, FirstName = "Георгий", LastName = "Власов" },
                    new Student { GroupId = 9, FirstName = "Артём", LastName = "Капустин" },
                    new Student { GroupId = 9, FirstName = "Адам", LastName = "Лукьянов" },
                    new Student { GroupId = 9, FirstName = "Егор", LastName = "Тихонов" },
                    new Student { GroupId = 9, FirstName = "Ярослав", LastName = "Никитин" },
                    new Student { GroupId = 9, FirstName = "Ариана", LastName = "Иванова" },
                    new Student { GroupId = 9, FirstName = "Кира", LastName = "Герасимова" },
                    new Student { GroupId = 9, FirstName = "Михаил", LastName = "Никифоров" },
                    new Student { GroupId = 9, FirstName = "Лидия", LastName = "Анисимова" },
                    new Student { GroupId = 9, FirstName = "Ксения", LastName = "Медведева" },
                    new Student { GroupId = 9, FirstName = "Тимофей", LastName = "Лаптев" },
                    new Student { GroupId = 9, FirstName = "Артемий", LastName = "Казаков" },
                    new Student { GroupId = 9, FirstName = "Ульяна", LastName = "Казакова" },
                    new Student { GroupId = 9, FirstName = "Игорь", LastName = "Васильев" },
                    new Student { GroupId = 9, FirstName = "Кирилл", LastName = "Романов" },
                    new Student { GroupId = 9, FirstName = "Анастасия", LastName = "Васильева" },
                    new Student { GroupId = 9, FirstName = "Арина", LastName = "Субботина" },
                    new Student { GroupId = 9, FirstName = "Александр", LastName = "Родионов" },
                    new Student { GroupId = 9, FirstName = "Лев", LastName = "Курочкин" },
                    new Student { GroupId = 10, FirstName = "Михаил", LastName = "Захаров" },
                    new Student { GroupId = 10, FirstName = "Мирослав", LastName = "Матвеев" },
                    new Student { GroupId = 10, FirstName = "Михаил", LastName = "Романов" },
                    new Student { GroupId = 10, FirstName = "Виктор", LastName = "Савельев" },
                    new Student { GroupId = 10, FirstName = "Айлин", LastName = "Корнеева" },
                    new Student { GroupId = 10, FirstName = "Милана", LastName = "Калашникова" },
                    new Student { GroupId = 10, FirstName = "Лидия", LastName = "Попова" },
                    new Student { GroupId = 10, FirstName = "Александр", LastName = "Аксенов" },
                    new Student { GroupId = 10, FirstName = "Герман", LastName = "Родионов" },
                    new Student { GroupId = 10, FirstName = "Милана", LastName = "Князева" },
                    new Student { GroupId = 10, FirstName = "Максим", LastName = "Головин" },
                    new Student { GroupId = 10, FirstName = "Елизавета", LastName = "Кузнецова" },
                    new Student { GroupId = 10, FirstName = "Александра", LastName = "Любимова" },
                    new Student { GroupId = 10, FirstName = "Семён", LastName = "Грачев" },
                    new Student { GroupId = 10, FirstName = "Мария", LastName = "Баранова" },
                    new Student { GroupId = 10, FirstName = "Николай", LastName = "Сомов" },
                    new Student { GroupId = 10, FirstName = "Виктория", LastName = "Куликова" },
                    new Student { GroupId = 10, FirstName = "Богдан", LastName = "Кузнецов" },
                    new Student { GroupId = 10, FirstName = "Андрей", LastName = "Куликов" },
                    new Student { GroupId = 10, FirstName = "Егор", LastName = "Захаров" },
                    new Student { GroupId = 10, FirstName = "Тимофей", LastName = "Иванов" },
                    new Student { GroupId = 10, FirstName = "Константин", LastName = "Львов" },
                    new Student { GroupId = 10, FirstName = "Мелисса", LastName = "Пугачева" },
                    new Student { GroupId = 10, FirstName = "Григорий", LastName = "Сидоров" },
                    new Student { GroupId = 10, FirstName = "Михаил", LastName = "Ананьев" },
                    new Student { GroupId = 10, FirstName = "Александра", LastName = "Поликарпова" },
                    new Student { GroupId = 10, FirstName = "Андрей", LastName = "Корнилов" },
                    new Student { GroupId = 10, FirstName = "Фёдор", LastName = "Евдокимов" },
                    new Student { GroupId = 10, FirstName = "Иван", LastName = "Орехов" },
                    new Student { GroupId = 10, FirstName = "Мирослава", LastName = "Панфилова" },
                    new Student { GroupId = 11, FirstName = "Владислав", LastName = "Новиков" },
                    new Student { GroupId = 11, FirstName = "Демид", LastName = "Спиридонов" },
                    new Student { GroupId = 11, FirstName = "Даниил", LastName = "Ларионов" },
                    new Student { GroupId = 11, FirstName = "Ульяна", LastName = "Волкова" },
                    new Student { GroupId = 11, FirstName = "Дмитрий", LastName = "Беляев" },
                    new Student { GroupId = 11, FirstName = "Мария", LastName = "Белова" },
                    new Student { GroupId = 11, FirstName = "Николай", LastName = "Семенов" },
                    new Student { GroupId = 11, FirstName = "Алёна", LastName = "Кириллова" },
                    new Student { GroupId = 11, FirstName = "Максим", LastName = "Сафонов" },
                    new Student { GroupId = 11, FirstName = "Даниил", LastName = "Рубцов" },
                    new Student { GroupId = 11, FirstName = "Владимир", LastName = "Ильин" },
                    new Student { GroupId = 11, FirstName = "Анфиса", LastName = "Майорова" },
                    new Student { GroupId = 11, FirstName = "Елизавета", LastName = "Андреева" },
                    new Student { GroupId = 11, FirstName = "Максим", LastName = "Антонов" },
                    new Student { GroupId = 11, FirstName = "София", LastName = "Бурова" },
                    new Student { GroupId = 11, FirstName = "Дмитрий", LastName = "Зайцев" },
                    new Student { GroupId = 11, FirstName = "Полина", LastName = "Николаева" },
                    new Student { GroupId = 11, FirstName = "Егор", LastName = "Пирогов" },
                    new Student { GroupId = 11, FirstName = "Всеволод", LastName = "Баженов" },
                    new Student { GroupId = 11, FirstName = "Николай", LastName = "Сергеев" },
                    new Student { GroupId = 11, FirstName = "Владимир", LastName = "Макаров" },
                    new Student { GroupId = 11, FirstName = "Александра", LastName = "Белоусова" },
                    new Student { GroupId = 11, FirstName = "Максим", LastName = "Коновалов" },
                    new Student { GroupId = 11, FirstName = "София", LastName = "Романова" },
                    new Student { GroupId = 11, FirstName = "Марина", LastName = "Власова" },
                    new Student { GroupId = 11, FirstName = "Константин", LastName = "Николаев" },
                    new Student { GroupId = 11, FirstName = "Лев", LastName = "Леонтьев" },
                    new Student { GroupId = 11, FirstName = "Николь", LastName = "Егорова" },
                    new Student { GroupId = 11, FirstName = "Анастасия", LastName = "Белоусова" },
                    new Student { GroupId = 11, FirstName = "Дмитрий", LastName = "Федоров" },
                    new Student { GroupId = 12, FirstName = "Егор", LastName = "Герасимов" },
                    new Student { GroupId = 12, FirstName = "Варвара", LastName = "Галкина" },
                    new Student { GroupId = 12, FirstName = "Алиса", LastName = "Суханова" },
                    new Student { GroupId = 12, FirstName = "Александр", LastName = "Ефимов" },
                    new Student { GroupId = 12, FirstName = "Виктория", LastName = "Иванова" },
                    new Student { GroupId = 12, FirstName = "Алиса", LastName = "Медведева" },
                    new Student { GroupId = 12, FirstName = "Фёдор", LastName = "Кузьмин" },
                    new Student { GroupId = 12, FirstName = "Дмитрий", LastName = "Антонов" },
                    new Student { GroupId = 12, FirstName = "Анастасия", LastName = "Жарова" },
                    new Student { GroupId = 12, FirstName = "Анна", LastName = "Миронова" },
                    new Student { GroupId = 12, FirstName = "Тимофей", LastName = "Иванов" },
                    new Student { GroupId = 12, FirstName = "Майя", LastName = "Зайцева" },
                    new Student { GroupId = 12, FirstName = "Полина", LastName = "Филиппова" },
                    new Student { GroupId = 12, FirstName = "Ева", LastName = "Пастухова" },
                    new Student { GroupId = 12, FirstName = "Александр", LastName = "Ильин" },
                    new Student { GroupId = 12, FirstName = "Филипп", LastName = "Максимов" },
                    new Student { GroupId = 12, FirstName = "Дмитрий", LastName = "Захаров" },
                    new Student { GroupId = 12, FirstName = "Константин", LastName = "Киселев" },
                    new Student { GroupId = 12, FirstName = "Василиса", LastName = "Тарасова" },
                    new Student { GroupId = 12, FirstName = "Мария", LastName = "Куликова" },
                    new Student { GroupId = 12, FirstName = "Артём", LastName = "Королев" },
                    new Student { GroupId = 12, FirstName = "Евгения", LastName = "Воронова" },
                    new Student { GroupId = 12, FirstName = "Елизавета", LastName = "Куликова" },
                    new Student { GroupId = 12, FirstName = "Иван", LastName = "Поляков" },
                    new Student { GroupId = 12, FirstName = "Максим", LastName = "Егоров" },
                    new Student { GroupId = 12, FirstName = "Максим", LastName = "Балашов" },
                    new Student { GroupId = 12, FirstName = "Иван", LastName = "Новиков" },
                    new Student { GroupId = 12, FirstName = "Анастасия", LastName = "Баранова" },
                    new Student { GroupId = 12, FirstName = "Мария", LastName = "Титова" },
                    new Student { GroupId = 12, FirstName = "Мирослава", LastName = "Золотова" },
                    new Student { GroupId = 13, FirstName = "Анна", LastName = "Данилова" },
                    new Student { GroupId = 13, FirstName = "Дмитрий", LastName = "Соловьев" },
                    new Student { GroupId = 13, FirstName = "Кирилл", LastName = "Виноградов" },
                    new Student { GroupId = 13, FirstName = "Ева", LastName = "Макарова" },
                    new Student { GroupId = 13, FirstName = "Савелий", LastName = "Филатов" },
                    new Student { GroupId = 13, FirstName = "Софья", LastName = "Сычева" },
                    new Student { GroupId = 13, FirstName = "Степан", LastName = "Сергеев" },
                    new Student { GroupId = 13, FirstName = "Вероника", LastName = "Иванова" },
                    new Student { GroupId = 13, FirstName = "Василиса", LastName = "Малышева" },
                    new Student { GroupId = 13, FirstName = "Платон", LastName = "Демин" },
                    new Student { GroupId = 13, FirstName = "Максим", LastName = "Тихонов" },
                    new Student { GroupId = 13, FirstName = "Ярослав", LastName = "Юдин" },
                    new Student { GroupId = 13, FirstName = "Елизавета", LastName = "Серова" },
                    new Student { GroupId = 13, FirstName = "Елизавета", LastName = "Егорова" },
                    new Student { GroupId = 13, FirstName = "Надежда", LastName = "Уткина" },
                    new Student { GroupId = 13, FirstName = "Ульяна", LastName = "Маркина" },
                    new Student { GroupId = 13, FirstName = "Сергей", LastName = "Соколов" },
                    new Student { GroupId = 13, FirstName = "Антон", LastName = "Смирнов" },
                    new Student { GroupId = 13, FirstName = "Александра", LastName = "Касаткина" },
                    new Student { GroupId = 13, FirstName = "Константин", LastName = "Баранов" },
                    new Student { GroupId = 13, FirstName = "Кирилл", LastName = "Абрамов" },
                    new Student { GroupId = 13, FirstName = "Яков", LastName = "Рыжов" },
                    new Student { GroupId = 13, FirstName = "Лев", LastName = "Кузнецов" },
                    new Student { GroupId = 13, FirstName = "Марина", LastName = "Куприянова" },
                    new Student { GroupId = 13, FirstName = "Никита", LastName = "Мальцев" },
                    new Student { GroupId = 13, FirstName = "Матвей", LastName = "Титов" },
                    new Student { GroupId = 13, FirstName = "Борис", LastName = "Баранов" },
                    new Student { GroupId = 13, FirstName = "Виктория", LastName = "Степанова" },
                    new Student { GroupId = 13, FirstName = "Тимофей", LastName = "Артамонов" },
                    new Student { GroupId = 13, FirstName = "Мирон", LastName = "Захаров" },
                    new Student { GroupId = 14, FirstName = "Савва", LastName = "Масленников" },
                    new Student { GroupId = 14, FirstName = "Евгений", LastName = "Соловьев" },
                    new Student { GroupId = 14, FirstName = "Макар", LastName = "Киселев" },
                    new Student { GroupId = 14, FirstName = "Арсений", LastName = "Николаев" },
                    new Student { GroupId = 14, FirstName = "Марк", LastName = "Павлов" },
                    new Student { GroupId = 14, FirstName = "Мария", LastName = "Малинина" },
                    new Student { GroupId = 14, FirstName = "Александр", LastName = "Кулешов" },
                    new Student { GroupId = 14, FirstName = "София", LastName = "Ерофеева" },
                    new Student { GroupId = 14, FirstName = "Вероника", LastName = "Родионова" },
                    new Student { GroupId = 14, FirstName = "Виктория", LastName = "Кочетова" },
                    new Student { GroupId = 14, FirstName = "Илья", LastName = "Андрианов" },
                    new Student { GroupId = 14, FirstName = "Милана", LastName = "Субботина" },
                    new Student { GroupId = 14, FirstName = "Аврора", LastName = "Дмитриева" },
                    new Student { GroupId = 14, FirstName = "Семён", LastName = "Казаков" },
                    new Student { GroupId = 14, FirstName = "Матвей", LastName = "Малахов" },
                    new Student { GroupId = 14, FirstName = "Мия", LastName = "Болдырева" },
                    new Student { GroupId = 14, FirstName = "Ксения", LastName = "Чеснокова" },
                    new Student { GroupId = 14, FirstName = "Владимир", LastName = "Козлов" },
                    new Student { GroupId = 14, FirstName = "Артём", LastName = "Селезнев" },
                    new Student { GroupId = 14, FirstName = "Кирилл", LastName = "Кузнецов" },
                    new Student { GroupId = 14, FirstName = "Регина", LastName = "Полякова" },
                    new Student { GroupId = 14, FirstName = "Алиса", LastName = "Романова" },
                    new Student { GroupId = 14, FirstName = "Полина", LastName = "Баранова" },
                    new Student { GroupId = 14, FirstName = "Константин", LastName = "Соловьев" },
                    new Student { GroupId = 14, FirstName = "Полина", LastName = "Русакова" },
                    new Student { GroupId = 14, FirstName = "Артём", LastName = "Петров" },
                    new Student { GroupId = 14, FirstName = "Софья", LastName = "Тихонова" },
                    new Student { GroupId = 14, FirstName = "Максим", LastName = "Богданов" },
                    new Student { GroupId = 14, FirstName = "София", LastName = "Власова" },
                    new Student { GroupId = 14, FirstName = "Константин", LastName = "Антипов" },
                    new Student { GroupId = 15, FirstName = "Лилия", LastName = "Овчинникова" },
                    new Student { GroupId = 15, FirstName = "Варвара", LastName = "Филиппова" },
                    new Student { GroupId = 15, FirstName = "Никита", LastName = "Попов" },
                    new Student { GroupId = 15, FirstName = "Дарья", LastName = "Герасимова" },
                    new Student { GroupId = 15, FirstName = "Арина", LastName = "Филатова" },
                    new Student { GroupId = 15, FirstName = "Анастасия", LastName = "Семенова" },
                    new Student { GroupId = 15, FirstName = "Вероника", LastName = "Корнеева" },
                    new Student { GroupId = 15, FirstName = "Лев", LastName = "Фадеев" },
                    new Student { GroupId = 15, FirstName = "Виктория", LastName = "Павлова" },
                    new Student { GroupId = 15, FirstName = "Мария", LastName = "Демина" },
                    new Student { GroupId = 15, FirstName = "Милана", LastName = "Гришина" },
                    new Student { GroupId = 15, FirstName = "Степан", LastName = "Куликов" },
                    new Student { GroupId = 15, FirstName = "Эмилия", LastName = "Минаева" },
                    new Student { GroupId = 15, FirstName = "Аиша", LastName = "Смирнова" },
                    new Student { GroupId = 15, FirstName = "Анна", LastName = "Морозова" },
                    new Student { GroupId = 15, FirstName = "Аделина", LastName = "Гаврилова" },
                    new Student { GroupId = 15, FirstName = "Вероника", LastName = "Максимова" },
                    new Student { GroupId = 15, FirstName = "Варвара", LastName = "Волкова" },
                    new Student { GroupId = 15, FirstName = "Иван", LastName = "Абрамов" },
                    new Student { GroupId = 15, FirstName = "Захар", LastName = "Морозов" },
                    new Student { GroupId = 15, FirstName = "Анна", LastName = "Орлова" },
                    new Student { GroupId = 15, FirstName = "Артём", LastName = "Горшков" },
                    new Student { GroupId = 15, FirstName = "Дамир", LastName = "Чернов" },
                    new Student { GroupId = 15, FirstName = "Максим", LastName = "Смирнов" },
                    new Student { GroupId = 15, FirstName = "Денис", LastName = "Соболев" },
                    new Student { GroupId = 15, FirstName = "Марк", LastName = "Кондратьев" },
                    new Student { GroupId = 15, FirstName = "Амалия", LastName = "Устинова" },
                    new Student { GroupId = 15, FirstName = "София", LastName = "Богданова" },
                    new Student { GroupId = 15, FirstName = "Мария", LastName = "Попова" },
                    new Student { GroupId = 15, FirstName = "Ксения", LastName = "Попова" },
                    new Student { GroupId = 16, FirstName = "Игорь", LastName = "Анисимов" },
                    new Student { GroupId = 16, FirstName = "София", LastName = "Суханова" },
                    new Student { GroupId = 16, FirstName = "Ева", LastName = "Лебедева" },
                    new Student { GroupId = 16, FirstName = "Кира", LastName = "Куликова" },
                    new Student { GroupId = 16, FirstName = "Екатерина", LastName = "Степанова" },
                    new Student { GroupId = 16, FirstName = "Александра", LastName = "Рябинина" },
                    new Student { GroupId = 16, FirstName = "Гордей", LastName = "Хохлов" },
                    new Student { GroupId = 16, FirstName = "Николай", LastName = "Нечаев" },
                    new Student { GroupId = 16, FirstName = "Макар", LastName = "Борисов" },
                    new Student { GroupId = 16, FirstName = "Матвей", LastName = "Фролов" },
                    new Student { GroupId = 16, FirstName = "Ульяна", LastName = "Калашникова" },
                    new Student { GroupId = 16, FirstName = "Дмитрий", LastName = "Васильев" },
                    new Student { GroupId = 16, FirstName = "Эмилия", LastName = "Пахомова" },
                    new Student { GroupId = 16, FirstName = "Глеб", LastName = "Мухин" },
                    new Student { GroupId = 16, FirstName = "Егор", LastName = "Рудаков" },
                    new Student { GroupId = 16, FirstName = "Мелания", LastName = "Смирнова" },
                    new Student { GroupId = 16, FirstName = "Полина", LastName = "Губанова" },
                    new Student { GroupId = 16, FirstName = "Никита", LastName = "Николаев" },
                    new Student { GroupId = 16, FirstName = "Екатерина", LastName = "Воробьева" },
                    new Student { GroupId = 16, FirstName = "Полина", LastName = "Демидова" },
                    new Student { GroupId = 16, FirstName = "Мария", LastName = "Афанасьева" },
                    new Student { GroupId = 16, FirstName = "Екатерина", LastName = "Петрова" },
                    new Student { GroupId = 16, FirstName = "Лев", LastName = "Беляев" },
                    new Student { GroupId = 16, FirstName = "Богдан", LastName = "Григорьев" },
                    new Student { GroupId = 16, FirstName = "Сергей", LastName = "Зеленин" },
                    new Student { GroupId = 16, FirstName = "Филипп", LastName = "Латышев" },
                    new Student { GroupId = 16, FirstName = "Анна", LastName = "Лукина" },
                    new Student { GroupId = 16, FirstName = "Евгения", LastName = "Шульгина" },
                    new Student { GroupId = 16, FirstName = "Василиса", LastName = "Белова" },
                    new Student { GroupId = 16, FirstName = "Владимир", LastName = "Емельянов" }
                );
                context.SaveChanges();
            }
        }
    }
}
