using Microsoft.EntityFrameworkCore;
using MVC.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MVC.DataAccess
{
    public static class ModelBuilderExtensions
    {
        public static void Seed(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Course>().HasData
                (
                    new Course
                    {   
                        Id = 1,
                        Name = "Математика",
                        Description = "Царица наук"
                    },
                    new Course
                    {
                        Id = 2,
                        Name = "Физика",
                        Description = "Основа всего"
                    },
                    new Course
                    {
                        Id = 3,
                        Name = "Физкультура",
                        Description = "В здоровом теле - здоровый дух"
                    },
                    new Course
                    {
                        Id = 4,
                        Name = "История",
                        Description = "У того, кто не знает прошлого - нет будущего"
                    }
                );

            modelBuilder.Entity<Group>().HasData
                (
                    new Group { Id = 1, CourseId = 1, Name = "КБ-101" },
                    new Group { Id = 2, CourseId = 2, Name = "ЛП-102" },
                    new Group { Id = 3, CourseId = 3, Name = "РР-103" },
                    new Group { Id = 4, CourseId = 2, Name = "РС-104" },
                    new Group { Id = 5, CourseId = 1, Name = "РА-105" },
                    new Group { Id = 6, CourseId = 3, Name = "РА-202" },
                    new Group { Id = 7, CourseId = 4, Name = "АР-203" },
                    new Group { Id = 8, CourseId = 4, Name = "РА-204" },
                    new Group { Id = 9, CourseId = 1, Name = "НК-205" },
                    new Group { Id = 10, CourseId = 3, Name = "БК-301" },
                    new Group { Id = 11, CourseId = 4, Name = "РА-353" },
                    new Group { Id = 12, CourseId = 1, Name = "РА-333" },
                    new Group { Id = 13, CourseId = 3, Name = "ВП-322" },
                    new Group { Id = 14, CourseId = 3, Name = "УЦ-311" },
                    new Group { Id = 15, CourseId = 1, Name = "МВ-354" },
                    new Group { Id = 16, CourseId = 3, Name = "РА-344" },
                    new Group { Id = 17, CourseId = 3, Name = "ГА-223" },
                    new Group { Id = 18, CourseId = 3, Name = "ПВ-232" },
                    new Group { Id = 19, CourseId = 1, Name = "СП-344" },
                    new Group { Id = 20, CourseId = 1, Name = "ОР-421" },
                    new Group { Id = 21, CourseId = 1, Name = "РФ-231" },
                    new Group { Id = 22, CourseId = 2, Name = "ШО-521" },
                    new Group { Id = 23, CourseId = 2, Name = "РР-214" },
                    new Group { Id = 24, CourseId = 2, Name = "ФП-341" },
                    new Group { Id = 25, CourseId = 4, Name = "ПЦ-344" },
                    new Group { Id = 26, CourseId = 4, Name = "ТО-324" },
                    new Group { Id = 27, CourseId = 4, Name = "НР-433" },
                    new Group { Id = 28, CourseId = 4, Name = "РА-364" }
                );

            modelBuilder.Entity<Student>().HasData
                (
                    new Student { Id = 1, GroupId = 1, FirstName = "Ксения", LastName = "Пономарева", DateOfBirth = DateTime.Parse("02-10-1990"), ExamScore = 4.5F },
                    new Student { Id = 2, GroupId = 1, FirstName = "Милана", LastName = "Михайлова", DateOfBirth = DateTime.Parse("29-07-1986"), ExamScore = 3.9F },
                    new Student { Id = 3, GroupId = 1, FirstName = "Тимофей", LastName = "Яковлев", DateOfBirth = DateTime.Parse("30-04-2000"), ExamScore = 4.2F },
                    new Student { Id = 4, GroupId = 1, FirstName = "Эвелина", LastName = "Михайлова", DateOfBirth = DateTime.Parse("14-05-1996"), ExamScore = 3.4F },
                    new Student { Id = 5, GroupId = 1, FirstName = "Елизавета", LastName = "Волкова", DateOfBirth = DateTime.Parse("29-07-1999"), ExamScore = 4.8F },
                    new Student { Id = 6, GroupId = 1, FirstName = "Ольга", LastName = "Кузнецова", DateOfBirth = DateTime.Parse("29-11-1987"), ExamScore = 4.3F },
                    new Student { Id = 7, GroupId = 1, FirstName = "Илья", LastName = "Харитонов", DateOfBirth = DateTime.Parse("19-11-1990"), ExamScore = 4.4F },
                    new Student { Id = 8, GroupId = 1, FirstName = "Мария", LastName = "Соловьева", DateOfBirth = DateTime.Parse("27-09-1987"), ExamScore = 4F },
                    new Student { Id = 9, GroupId = 1, FirstName = "Майя", LastName = "Гришина", DateOfBirth = DateTime.Parse("16-09-2000"), ExamScore = 4F },
                    new Student { Id = 10, GroupId = 1, FirstName = "Дарья", LastName = "Корнеева", DateOfBirth = DateTime.Parse("12-04-1995"), ExamScore = 4F },
                    new Student { Id = 11, GroupId = 2, FirstName = "Эвелина", LastName = "Горшкова", DateOfBirth = DateTime.Parse("06-01-1995"), ExamScore = 4.6F },
                    new Student { Id = 12, GroupId = 2, FirstName = "София", LastName = "Юдина", DateOfBirth = DateTime.Parse("13-08-1991"), ExamScore = 3.6F },
                    new Student { Id = 13, GroupId = 2, FirstName = "Ульяна", LastName = "Гаврилова", DateOfBirth = DateTime.Parse("12-02-2000"), ExamScore = 4.9F },
                    new Student { Id = 14, GroupId = 2, FirstName = "Кира", LastName = "Ковалева", DateOfBirth = DateTime.Parse("04-10-1999"), ExamScore = 3.3F },
                    new Student { Id = 15, GroupId = 2, FirstName = "Александра", LastName = "Петрова", DateOfBirth = DateTime.Parse("21-05-1990"), ExamScore = 3F },
                    new Student { Id = 16, GroupId = 2, FirstName = "Никита", LastName = "Румянцев", DateOfBirth = DateTime.Parse("19-10-1987"), ExamScore = 4.2F },
                    new Student { Id = 17, GroupId = 2, FirstName = "Мия", LastName = "Кузьмина", DateOfBirth = DateTime.Parse("09-06-1993"), ExamScore = 4.3F },
                    new Student { Id = 18, GroupId = 2, FirstName = "Милана", LastName = "Куликова", DateOfBirth = DateTime.Parse("17-11-2001"), ExamScore = 4.7F },
                    new Student { Id = 19, GroupId = 2, FirstName = "Анастасия", LastName = "Сергеева", DateOfBirth = DateTime.Parse("16-09-1996"), ExamScore = 3.5F },
                    new Student { Id = 20, GroupId = 2, FirstName = "Денис", LastName = "Чернов", DateOfBirth = DateTime.Parse("18-02-1991"), ExamScore = 3.9F },
                    new Student { Id = 21, GroupId = 2, FirstName = "Савелий", LastName = "Воронов", DateOfBirth = DateTime.Parse("28-08-1986"), ExamScore = 4.4F },
                    new Student { Id = 22, GroupId = 2, FirstName = "Егор", LastName = "Степанов", DateOfBirth = DateTime.Parse("17-11-1990"), ExamScore = 4.3F },
                    new Student { Id = 23, GroupId = 2, FirstName = "Кирилл", LastName = "Федоров", DateOfBirth = DateTime.Parse("15-12-1995"), ExamScore = 3.9F },
                    new Student { Id = 24, GroupId = 2, FirstName = "Аиша", LastName = "Дубровина", DateOfBirth = DateTime.Parse("01-06-1998"), ExamScore = 4.4F },
                    new Student { Id = 25, GroupId = 2, FirstName = "Матвей", LastName = "Озеров", DateOfBirth = DateTime.Parse("15-09-1995"), ExamScore = 3.5F },
                    new Student { Id = 26, GroupId = 2, FirstName = "Нина", LastName = "Соловьева", DateOfBirth = DateTime.Parse("21-05-1990"), ExamScore = 4.8F },
                    new Student { Id = 27, GroupId = 2, FirstName = "Константин", LastName = "Павлов", DateOfBirth = DateTime.Parse("04-02-1990"), ExamScore = 3.4F },
                    new Student { Id = 28, GroupId = 2, FirstName = "Макар", LastName = "Захаров", DateOfBirth = DateTime.Parse("13-10-1999"), ExamScore = 3.3F },
                    new Student { Id = 29, GroupId = 2, FirstName = "Николай", LastName = "Афанасьев", DateOfBirth = DateTime.Parse("25-07-1998"), ExamScore = 4.5F },
                    new Student { Id = 30, GroupId = 2, FirstName = "Иван", LastName = "Иванов", DateOfBirth = DateTime.Parse("01-02-1992"), ExamScore = 4.9F },
                    new Student { Id = 31, GroupId = 2, FirstName = "Михаил", LastName = "Дмитриев", DateOfBirth = DateTime.Parse("25-04-1986"), ExamScore = 3.9F },
                    new Student { Id = 32, GroupId = 2, FirstName = "Артём", LastName = "Макаров", DateOfBirth = DateTime.Parse("12-10-1989"), ExamScore = 3.7F },
                    new Student { Id = 33, GroupId = 2, FirstName = "Ева", LastName = "Рябинина", DateOfBirth = DateTime.Parse("21-07-1988"), ExamScore = 5F },
                    new Student { Id = 34, GroupId = 2, FirstName = "Роман", LastName = "Кузьмин", DateOfBirth = DateTime.Parse("02-07-2000"), ExamScore = 3.5F },
                    new Student { Id = 35, GroupId = 2, FirstName = "Софья", LastName = "Винокурова", DateOfBirth = DateTime.Parse("07-09-1988"), ExamScore = 3.5F },
                    new Student { Id = 36, GroupId = 2, FirstName = "Мария", LastName = "Пирогова", DateOfBirth = DateTime.Parse("13-10-1993"), ExamScore = 4.3F },
                    new Student { Id = 37, GroupId = 2, FirstName = "Максим", LastName = "Денисов", DateOfBirth = DateTime.Parse("21-07-1999"), ExamScore = 3.4F },
                    new Student { Id = 38, GroupId = 2, FirstName = "Артём", LastName = "Колпаков", DateOfBirth = DateTime.Parse("25-03-1992"), ExamScore = 4.3F },
                    new Student { Id = 39, GroupId = 2, FirstName = "Лев", LastName = "Попов", DateOfBirth = DateTime.Parse("30-12-1996"), ExamScore = 4.3F },
                    new Student { Id = 40, GroupId = 3, FirstName = "Кира", LastName = "Савельева", DateOfBirth = DateTime.Parse("28-10-2001"), ExamScore = 4.3F },
                    new Student { Id = 41, GroupId = 3, FirstName = "Даниил", LastName = "Лаптев", DateOfBirth = DateTime.Parse("02-12-1986"), ExamScore = 4.9F },
                    new Student { Id = 42, GroupId = 3, FirstName = "Амира", LastName = "Филатова", DateOfBirth = DateTime.Parse("09-04-1987"), ExamScore = 3.6F },
                    new Student { Id = 43, GroupId = 3, FirstName = "Любовь", LastName = "Покровская", DateOfBirth = DateTime.Parse("19-05-1985"), ExamScore = 3.3F },
                    new Student { Id = 44, GroupId = 3, FirstName = "Евгения", LastName = "Алексеева", DateOfBirth = DateTime.Parse("03-05-1986"), ExamScore = 4.4F },
                    new Student { Id = 45, GroupId = 3, FirstName = "Тимофей", LastName = "Тарасов", DateOfBirth = DateTime.Parse("02-06-1996"), ExamScore = 3.1F },
                    new Student { Id = 46, GroupId = 3, FirstName = "Платон", LastName = "Терехов", DateOfBirth = DateTime.Parse("10-12-1987"), ExamScore = 5F },
                    new Student { Id = 47, GroupId = 3, FirstName = "Анна", LastName = "Андрианова", DateOfBirth = DateTime.Parse("10-09-1997"), ExamScore = 4F },
                    new Student { Id = 48, GroupId = 3, FirstName = "Арина", LastName = "Зуева", DateOfBirth = DateTime.Parse("14-07-1990"), ExamScore = 4.3F },
                    new Student { Id = 49, GroupId = 3, FirstName = "Арина", LastName = "Савельева", DateOfBirth = DateTime.Parse("11-08-1986"), ExamScore = 3.9F },
                    new Student { Id = 50, GroupId = 3, FirstName = "Тимофей", LastName = "Федотов", DateOfBirth = DateTime.Parse("21-07-2001"), ExamScore = 3.2F },
                    new Student { Id = 51, GroupId = 3, FirstName = "Владислав", LastName = "Капустин", DateOfBirth = DateTime.Parse("11-03-1993"), ExamScore = 3.2F },
                    new Student { Id = 52, GroupId = 3, FirstName = "Матвей", LastName = "Волков", DateOfBirth = DateTime.Parse("10-06-1998"), ExamScore = 3.5F },
                    new Student { Id = 53, GroupId = 3, FirstName = "Варвара", LastName = "Краснова", DateOfBirth = DateTime.Parse("29-10-1986"), ExamScore = 4.4F },
                    new Student { Id = 54, GroupId = 3, FirstName = "Матвей", LastName = "Воробьев", DateOfBirth = DateTime.Parse("19-01-1986"), ExamScore = 4.7F },
                    new Student { Id = 55, GroupId = 3, FirstName = "Мария", LastName = "Степанова", DateOfBirth = DateTime.Parse("27-09-1992"), ExamScore = 3.7F },
                    new Student { Id = 56, GroupId = 3, FirstName = "Нина", LastName = "Абрамова", DateOfBirth = DateTime.Parse("03-12-1997"), ExamScore = 4.9F },
                    new Student { Id = 57, GroupId = 3, FirstName = "Герман", LastName = "Кукушкин", DateOfBirth = DateTime.Parse("05-01-1996"), ExamScore = 4.8F },
                    new Student { Id = 58, GroupId = 3, FirstName = "Виктория", LastName = "Блинова", DateOfBirth = DateTime.Parse("12-02-1986"), ExamScore = 3.4F },
                    new Student { Id = 59, GroupId = 3, FirstName = "Алёна", LastName = "Морозова", DateOfBirth = DateTime.Parse("01-03-2001"), ExamScore = 4F },
                    new Student { Id = 60, GroupId = 3, FirstName = "Виктория", LastName = "Тарасова", DateOfBirth = DateTime.Parse("20-06-1996"), ExamScore = 4.8F },
                    new Student { Id = 61, GroupId = 3, FirstName = "Алексей", LastName = "Беляев", DateOfBirth = DateTime.Parse("07-03-2000"), ExamScore = 3.4F },
                    new Student { Id = 62, GroupId = 3, FirstName = "Елизавета", LastName = "Малышева", DateOfBirth = DateTime.Parse("21-04-1990"), ExamScore = 4.1F },
                    new Student { Id = 63, GroupId = 3, FirstName = "Максим", LastName = "Егоров", DateOfBirth = DateTime.Parse("02-05-1988"), ExamScore = 5F },
                    new Student { Id = 64, GroupId = 3, FirstName = "Максим", LastName = "Дубов", DateOfBirth = DateTime.Parse("12-04-1988"), ExamScore = 4.5F },
                    new Student { Id = 65, GroupId = 3, FirstName = "Елизавета", LastName = "Смирнова", DateOfBirth = DateTime.Parse("10-12-1985"), ExamScore = 4.9F },
                    new Student { Id = 66, GroupId = 4, FirstName = "Алиса", LastName = "Корнилова", DateOfBirth = DateTime.Parse("22-01-1990"), ExamScore = 4.4F },
                    new Student { Id = 67, GroupId = 4, FirstName = "Ян", LastName = "Герасимов", DateOfBirth = DateTime.Parse("29-12-1991"), ExamScore = 3.6F },
                    new Student { Id = 68, GroupId = 4, FirstName = "Олег", LastName = "Смирнов", DateOfBirth = DateTime.Parse("09-04-1988"), ExamScore = 4.2F },
                    new Student { Id = 69, GroupId = 4, FirstName = "Елисей", LastName = "Аксенов", DateOfBirth = DateTime.Parse("28-03-1989"), ExamScore = 4.2F },
                    new Student { Id = 70, GroupId = 4, FirstName = "Сергей", LastName = "Лукьянов", DateOfBirth = DateTime.Parse("28-12-1997"), ExamScore = 3.3F },
                    new Student { Id = 71, GroupId = 4, FirstName = "Полина", LastName = "Ковалева", DateOfBirth = DateTime.Parse("09-03-1991"), ExamScore = 4.9F },
                    new Student { Id = 72, GroupId = 4, FirstName = "Мирон", LastName = "Казаков", DateOfBirth = DateTime.Parse("09-10-1990"), ExamScore = 3.9F },
                    new Student { Id = 73, GroupId = 4, FirstName = "Алиса", LastName = "Логинова", DateOfBirth = DateTime.Parse("29-01-2001"), ExamScore = 3.9F },
                    new Student { Id = 74, GroupId = 4, FirstName = "Ксения", LastName = "Попова", DateOfBirth = DateTime.Parse("26-11-1994"), ExamScore = 3F },
                    new Student { Id = 75, GroupId = 4, FirstName = "Ангелина", LastName = "Кондрашова", DateOfBirth = DateTime.Parse("08-01-1990"), ExamScore = 3.5F },
                    new Student { Id = 76, GroupId = 4, FirstName = "Ульяна", LastName = "Давыдова", DateOfBirth = DateTime.Parse("05-02-1989"), ExamScore = 4.1F },
                    new Student { Id = 77, GroupId = 4, FirstName = "Анастасия", LastName = "Капустина", DateOfBirth = DateTime.Parse("09-08-1987"), ExamScore = 5F },
                    new Student { Id = 78, GroupId = 4, FirstName = "Макар", LastName = "Корнеев", DateOfBirth = DateTime.Parse("17-04-2001"), ExamScore = 3.9F },
                    new Student { Id = 79, GroupId = 4, FirstName = "Давид", LastName = "Голованов", DateOfBirth = DateTime.Parse("05-06-1996"), ExamScore = 4.3F },
                    new Student { Id = 80, GroupId = 4, FirstName = "Диана", LastName = "Колесникова", DateOfBirth = DateTime.Parse("18-02-1989"), ExamScore = 4.1F },
                    new Student { Id = 81, GroupId = 4, FirstName = "Константин", LastName = "Волков", DateOfBirth = DateTime.Parse("05-03-1991"), ExamScore = 3.1F },
                    new Student { Id = 82, GroupId = 4, FirstName = "Арина", LastName = "Чернышева", DateOfBirth = DateTime.Parse("20-09-1985"), ExamScore = 4.7F },
                    new Student { Id = 83, GroupId = 4, FirstName = "Евдокия", LastName = "Прохорова", DateOfBirth = DateTime.Parse("04-02-1991"), ExamScore = 4F },
                    new Student { Id = 84, GroupId = 5, FirstName = "Никита", LastName = "Тарасов", DateOfBirth = DateTime.Parse("25-01-1988"), ExamScore = 3.3F },
                    new Student { Id = 85, GroupId = 5, FirstName = "Лев", LastName = "Калинин", DateOfBirth = DateTime.Parse("24-05-1997"), ExamScore = 4.6F },
                    new Student { Id = 86, GroupId = 5, FirstName = "Георгий", LastName = "Большаков", DateOfBirth = DateTime.Parse("10-06-2001"), ExamScore = 3.4F },
                    new Student { Id = 87, GroupId = 5, FirstName = "Виктория", LastName = "Яшина", DateOfBirth = DateTime.Parse("05-01-1999"), ExamScore = 4.1F },
                    new Student { Id = 88, GroupId = 5, FirstName = "Лев", LastName = "Иванов", DateOfBirth = DateTime.Parse("06-03-1995"), ExamScore = 4F },
                    new Student { Id = 89, GroupId = 5, FirstName = "Елизавета", LastName = "Романова", DateOfBirth = DateTime.Parse("07-04-2001"), ExamScore = 3.3F },
                    new Student { Id = 90, GroupId = 5, FirstName = "Виктория", LastName = "Медведева", DateOfBirth = DateTime.Parse("23-08-1997"), ExamScore = 4.1F },
                    new Student { Id = 91, GroupId = 5, FirstName = "Анастасия", LastName = "Иванова", DateOfBirth = DateTime.Parse("04-01-2000"), ExamScore = 4.8F },
                    new Student { Id = 92, GroupId = 5, FirstName = "Елизавета", LastName = "Константинова", DateOfBirth = DateTime.Parse("09-06-1991"), ExamScore = 4.3F },
                    new Student { Id = 93, GroupId = 6, FirstName = "Мирослава", LastName = "Высоцкая", DateOfBirth = DateTime.Parse("30-11-1987"), ExamScore = 3.4F },
                    new Student { Id = 94, GroupId = 6, FirstName = "Никита", LastName = "Рубцов", DateOfBirth = DateTime.Parse("13-05-2000"), ExamScore = 3.1F },
                    new Student { Id = 95, GroupId = 6, FirstName = "Степан", LastName = "Ильин", DateOfBirth = DateTime.Parse("04-02-1991"), ExamScore = 4.4F },
                    new Student { Id = 96, GroupId = 6, FirstName = "Арина", LastName = "Егорова", DateOfBirth = DateTime.Parse("20-10-1995"), ExamScore = 3.5F },
                    new Student { Id = 97, GroupId = 6, FirstName = "Таисия", LastName = "Дубровина", DateOfBirth = DateTime.Parse("16-09-1995"), ExamScore = 3.8F },
                    new Student { Id = 98, GroupId = 6, FirstName = "Арина", LastName = "Воробьева", DateOfBirth = DateTime.Parse("17-10-1989"), ExamScore = 3.8F },
                    new Student { Id = 99, GroupId = 6, FirstName = "Вероника", LastName = "Пономарева", DateOfBirth = DateTime.Parse("30-12-1986"), ExamScore = 3.5F },
                    new Student { Id = 100, GroupId = 6, FirstName = "Михаил", LastName = "Львов", DateOfBirth = DateTime.Parse("20-03-1999"), ExamScore = 4.1F },
                    new Student { Id = 101, GroupId = 6, FirstName = "Дмитрий", LastName = "Семенов", DateOfBirth = DateTime.Parse("10-11-1994"), ExamScore = 4F },
                    new Student { Id = 102, GroupId = 6, FirstName = "Ульяна", LastName = "Краснова", DateOfBirth = DateTime.Parse("04-09-1989"), ExamScore = 4.1F },
                    new Student { Id = 103, GroupId = 6, FirstName = "Малика", LastName = "Козлова", DateOfBirth = DateTime.Parse("15-06-1990"), ExamScore = 4.7F },
                    new Student { Id = 104, GroupId = 6, FirstName = "Полина", LastName = "Воробьева", DateOfBirth = DateTime.Parse("20-08-1999"), ExamScore = 3.9F },
                    new Student { Id = 105, GroupId = 6, FirstName = "Владислав", LastName = "Нефедов", DateOfBirth = DateTime.Parse("22-01-1995"), ExamScore = 3.8F },
                    new Student { Id = 106, GroupId = 6, FirstName = "Арсений", LastName = "Рогов", DateOfBirth = DateTime.Parse("07-12-1991"), ExamScore = 4F },
                    new Student { Id = 107, GroupId = 6, FirstName = "София", LastName = "Ракова", DateOfBirth = DateTime.Parse("10-02-1994"), ExamScore = 4.7F },
                    new Student { Id = 108, GroupId = 6, FirstName = "Вероника", LastName = "Денисова", DateOfBirth = DateTime.Parse("12-12-2000"), ExamScore = 3.1F },
                    new Student { Id = 109, GroupId = 7, FirstName = "Павел", LastName = "Медведев", DateOfBirth = DateTime.Parse("13-03-1988"), ExamScore = 3.9F },
                    new Student { Id = 110, GroupId = 7, FirstName = "Николай", LastName = "Исаев", DateOfBirth = DateTime.Parse("09-11-1985"), ExamScore = 4.1F },
                    new Student { Id = 111, GroupId = 7, FirstName = "Кирилл", LastName = "Жилин", DateOfBirth = DateTime.Parse("18-08-2001"), ExamScore = 3F },
                    new Student { Id = 112, GroupId = 7, FirstName = "Вероника", LastName = "Кузнецова", DateOfBirth = DateTime.Parse("28-07-1987"), ExamScore = 3.4F },
                    new Student { Id = 113, GroupId = 7, FirstName = "Серафима", LastName = "Волкова", DateOfBirth = DateTime.Parse("17-02-1990"), ExamScore = 3.3F },
                    new Student { Id = 114, GroupId = 7, FirstName = "Екатерина", LastName = "Вавилова", DateOfBirth = DateTime.Parse("29-08-1995"), ExamScore = 3.5F },
                    new Student { Id = 115, GroupId = 7, FirstName = "Дарья", LastName = "Фокина", DateOfBirth = DateTime.Parse("30-09-2000"), ExamScore = 3.3F },
                    new Student { Id = 116, GroupId = 7, FirstName = "Марк", LastName = "Кудряшов", DateOfBirth = DateTime.Parse("06-07-1998"), ExamScore = 3.1F },
                    new Student { Id = 117, GroupId = 7, FirstName = "Анна", LastName = "Воронкова", DateOfBirth = DateTime.Parse("27-10-1992"), ExamScore = 3.2F },
                    new Student { Id = 118, GroupId = 7, FirstName = "Тимофей", LastName = "Коновалов", DateOfBirth = DateTime.Parse("05-08-1985"), ExamScore = 5F },
                    new Student { Id = 119, GroupId = 7, FirstName = "Софья", LastName = "Алешина", DateOfBirth = DateTime.Parse("28-07-1986"), ExamScore = 3.1F },
                    new Student { Id = 120, GroupId = 7, FirstName = "Артём", LastName = "Исаев", DateOfBirth = DateTime.Parse("20-08-1995"), ExamScore = 3.6F },
                    new Student { Id = 121, GroupId = 7, FirstName = "Оливия", LastName = "Крючкова", DateOfBirth = DateTime.Parse("26-10-2000"), ExamScore = 3.9F },
                    new Student { Id = 122, GroupId = 7, FirstName = "Мария", LastName = "Сорокина", DateOfBirth = DateTime.Parse("26-09-1998"), ExamScore = 3.4F },
                    new Student { Id = 123, GroupId = 7, FirstName = "Елизавета", LastName = "Фролова", DateOfBirth = DateTime.Parse("08-03-1995"), ExamScore = 4.2F },
                    new Student { Id = 124, GroupId = 7, FirstName = "Андрей", LastName = "Бочаров", DateOfBirth = DateTime.Parse("30-05-1995"), ExamScore = 4.1F },
                    new Student { Id = 125, GroupId = 7, FirstName = "Мелисса", LastName = "Щеглова", DateOfBirth = DateTime.Parse("17-02-1988"), ExamScore = 3.5F },
                    new Student { Id = 126, GroupId = 7, FirstName = "Арсений", LastName = "Попов", DateOfBirth = DateTime.Parse("24-05-1998"), ExamScore = 4.1F },
                    new Student { Id = 127, GroupId = 7, FirstName = "Давид", LastName = "Шубин", DateOfBirth = DateTime.Parse("08-03-1989"), ExamScore = 3.6F },
                    new Student { Id = 128, GroupId = 7, FirstName = "Мирослава", LastName = "Яковлева", DateOfBirth = DateTime.Parse("30-06-1989"), ExamScore = 4.1F },
                    new Student { Id = 129, GroupId = 7, FirstName = "Алексей", LastName = "Богданов", DateOfBirth = DateTime.Parse("16-09-1986"), ExamScore = 3.1F },
                    new Student { Id = 130, GroupId = 8, FirstName = "Михаил", LastName = "Смирнов", DateOfBirth = DateTime.Parse("01-01-1989"), ExamScore = 4.7F },
                    new Student { Id = 131, GroupId = 8, FirstName = "Тимур", LastName = "Новиков", DateOfBirth = DateTime.Parse("12-02-1994"), ExamScore = 4.6F },
                    new Student { Id = 132, GroupId = 8, FirstName = "Варвара", LastName = "Бирюкова", DateOfBirth = DateTime.Parse("10-05-1988"), ExamScore = 3.9F },
                    new Student { Id = 133, GroupId = 8, FirstName = "Давид", LastName = "Гусев", DateOfBirth = DateTime.Parse("25-04-1992"), ExamScore = 3.5F },
                    new Student { Id = 134, GroupId = 8, FirstName = "Иван", LastName = "Богданов", DateOfBirth = DateTime.Parse("11-08-1986"), ExamScore = 3F },
                    new Student { Id = 135, GroupId = 9, FirstName = "Александр", LastName = "Агапов", DateOfBirth = DateTime.Parse("17-02-1998"), ExamScore = 3.6F },
                    new Student { Id = 136, GroupId = 9, FirstName = "Михаил", LastName = "Самсонов", DateOfBirth = DateTime.Parse("24-05-1986"), ExamScore = 4.2F },
                    new Student { Id = 137, GroupId = 9, FirstName = "Кира", LastName = "Васильева", DateOfBirth = DateTime.Parse("15-01-1996"), ExamScore = 4.3F },
                    new Student { Id = 138, GroupId = 9, FirstName = "Кирилл", LastName = "Фадеев", DateOfBirth = DateTime.Parse("10-11-1998"), ExamScore = 3.6F },
                    new Student { Id = 139, GroupId = 9, FirstName = "Даниил", LastName = "Сычев", DateOfBirth = DateTime.Parse("29-07-1987"), ExamScore = 3.9F },
                    new Student { Id = 140, GroupId = 9, FirstName = "Роман", LastName = "Степанов", DateOfBirth = DateTime.Parse("20-02-1990"), ExamScore = 3.6F },
                    new Student { Id = 141, GroupId = 9, FirstName = "Наталья", LastName = "Фомина", DateOfBirth = DateTime.Parse("21-07-1991"), ExamScore = 4F },
                    new Student { Id = 142, GroupId = 9, FirstName = "Тимофей", LastName = "Кулаков", DateOfBirth = DateTime.Parse("05-11-1996"), ExamScore = 3.1F },
                    new Student { Id = 143, GroupId = 9, FirstName = "Яна", LastName = "Михайлова", DateOfBirth = DateTime.Parse("25-03-1985"), ExamScore = 3.1F },
                    new Student { Id = 144, GroupId = 9, FirstName = "Вячеслав", LastName = "Михайлов", DateOfBirth = DateTime.Parse("30-01-1995"), ExamScore = 3.4F },
                    new Student { Id = 145, GroupId = 9, FirstName = "Ариана", LastName = "Демидова", DateOfBirth = DateTime.Parse("24-01-1992"), ExamScore = 4.3F },
                    new Student { Id = 146, GroupId = 9, FirstName = "Илья", LastName = "Леонтьев", DateOfBirth = DateTime.Parse("23-01-1997"), ExamScore = 4.4F },
                    new Student { Id = 147, GroupId = 9, FirstName = "Мирон", LastName = "Матвеев", DateOfBirth = DateTime.Parse("07-05-1998"), ExamScore = 5F },
                    new Student { Id = 148, GroupId = 9, FirstName = "Роман", LastName = "Лебедев", DateOfBirth = DateTime.Parse("23-01-1996"), ExamScore = 4.2F },
                    new Student { Id = 149, GroupId = 9, FirstName = "Ульяна", LastName = "Соловьева", DateOfBirth = DateTime.Parse("13-12-1997"), ExamScore = 3.4F },
                    new Student { Id = 150, GroupId = 9, FirstName = "Даниил", LastName = "Калугин", DateOfBirth = DateTime.Parse("29-12-1999"), ExamScore = 3.6F },
                    new Student { Id = 151, GroupId = 9, FirstName = "София", LastName = "Зорина", DateOfBirth = DateTime.Parse("19-10-1987"), ExamScore = 3.6F },
                    new Student { Id = 152, GroupId = 9, FirstName = "Степан", LastName = "Зотов", DateOfBirth = DateTime.Parse("23-11-1988"), ExamScore = 3F },
                    new Student { Id = 153, GroupId = 9, FirstName = "Мария", LastName = "Воронова", DateOfBirth = DateTime.Parse("23-06-1988"), ExamScore = 3.6F },
                    new Student { Id = 154, GroupId = 9, FirstName = "Алиса", LastName = "Данилова", DateOfBirth = DateTime.Parse("30-04-1991"), ExamScore = 4.8F },
                    new Student { Id = 155, GroupId = 9, FirstName = "Константин", LastName = "Киселев", DateOfBirth = DateTime.Parse("19-09-1992"), ExamScore = 4.3F },
                    new Student { Id = 156, GroupId = 9, FirstName = "Арина", LastName = "Ларионова", DateOfBirth = DateTime.Parse("07-01-1996"), ExamScore = 4F },
                    new Student { Id = 157, GroupId = 9, FirstName = "Фёдор", LastName = "Наумов", DateOfBirth = DateTime.Parse("05-04-1989"), ExamScore = 4.1F },
                    new Student { Id = 158, GroupId = 9, FirstName = "Ульяна", LastName = "Попова", DateOfBirth = DateTime.Parse("26-12-1986"), ExamScore = 3.9F },
                    new Student { Id = 159, GroupId = 10, FirstName = "Михаил", LastName = "Лопатин", DateOfBirth = DateTime.Parse("06-11-1992"), ExamScore = 3.3F },
                    new Student { Id = 160, GroupId = 10, FirstName = "Алина", LastName = "Ермакова", DateOfBirth = DateTime.Parse("31-03-2001"), ExamScore = 4.7F },
                    new Student { Id = 161, GroupId = 10, FirstName = "Дарья", LastName = "Щукина", DateOfBirth = DateTime.Parse("18-08-1987"), ExamScore = 4.9F },
                    new Student { Id = 162, GroupId = 10, FirstName = "Георгий", LastName = "Белов", DateOfBirth = DateTime.Parse("14-07-1995"), ExamScore = 3.3F },
                    new Student { Id = 163, GroupId = 10, FirstName = "Анфиса", LastName = "Смирнова", DateOfBirth = DateTime.Parse("25-02-1995"), ExamScore = 4.7F },
                    new Student { Id = 164, GroupId = 10, FirstName = "Сергей", LastName = "Кондратьев", DateOfBirth = DateTime.Parse("18-07-1994"), ExamScore = 4.7F },
                    new Student { Id = 165, GroupId = 10, FirstName = "Таисия", LastName = "Вешнякова", DateOfBirth = DateTime.Parse("29-08-1991"), ExamScore = 4.6F },
                    new Student { Id = 166, GroupId = 10, FirstName = "Варвара", LastName = "Смирнова", DateOfBirth = DateTime.Parse("01-06-1992"), ExamScore = 3.6F },
                    new Student { Id = 167, GroupId = 10, FirstName = "Матвей", LastName = "Леонтьев", DateOfBirth = DateTime.Parse("24-04-1987"), ExamScore = 4.2F },
                    new Student { Id = 168, GroupId = 10, FirstName = "Ева", LastName = "Соловьева", DateOfBirth = DateTime.Parse("18-12-1985"), ExamScore = 4.5F },
                    new Student { Id = 169, GroupId = 10, FirstName = "Иван", LastName = "Губанов", DateOfBirth = DateTime.Parse("11-10-1994"), ExamScore = 3.1F },
                    new Student { Id = 170, GroupId = 10, FirstName = "Елизавета", LastName = "Иванова", DateOfBirth = DateTime.Parse("11-06-1995"), ExamScore = 3.1F },
                    new Student { Id = 171, GroupId = 10, FirstName = "Кирилл", LastName = "Самсонов", DateOfBirth = DateTime.Parse("10-11-1994"), ExamScore = 4.7F },
                    new Student { Id = 172, GroupId = 11, FirstName = "Маргарита", LastName = "Кочергина", DateOfBirth = DateTime.Parse("27-07-2000"), ExamScore = 4.3F },
                    new Student { Id = 173, GroupId = 11, FirstName = "Ярослава", LastName = "Морозова", DateOfBirth = DateTime.Parse("11-01-1998"), ExamScore = 4.3F },
                    new Student { Id = 174, GroupId = 11, FirstName = "Илья", LastName = "Троицкий", DateOfBirth = DateTime.Parse("14-12-1992"), ExamScore = 4.8F },
                    new Student { Id = 175, GroupId = 11, FirstName = "Анна", LastName = "Кулешова", DateOfBirth = DateTime.Parse("27-02-1988"), ExamScore = 3F },
                    new Student { Id = 176, GroupId = 11, FirstName = "Алина", LastName = "Макеева", DateOfBirth = DateTime.Parse("24-04-1993"), ExamScore = 3.4F },
                    new Student { Id = 177, GroupId = 11, FirstName = "Дарья", LastName = "Агеева", DateOfBirth = DateTime.Parse("21-01-1986"), ExamScore = 4.3F },
                    new Student { Id = 178, GroupId = 11, FirstName = "Максим", LastName = "Виноградов", DateOfBirth = DateTime.Parse("20-11-1999"), ExamScore = 4.4F },
                    new Student { Id = 179, GroupId = 11, FirstName = "Константин", LastName = "Шишкин", DateOfBirth = DateTime.Parse("29-04-1987"), ExamScore = 4.4F },
                    new Student { Id = 180, GroupId = 11, FirstName = "Ульяна", LastName = "Тихонова", DateOfBirth = DateTime.Parse("20-10-1992"), ExamScore = 3.3F },
                    new Student { Id = 181, GroupId = 11, FirstName = "Максим", LastName = "Лаптев", DateOfBirth = DateTime.Parse("31-12-1985"), ExamScore = 3.2F },
                    new Student { Id = 182, GroupId = 11, FirstName = "Анна", LastName = "Щербакова", DateOfBirth = DateTime.Parse("06-11-2001"), ExamScore = 3.6F },
                    new Student { Id = 183, GroupId = 11, FirstName = "Гордей", LastName = "Кузнецов", DateOfBirth = DateTime.Parse("02-10-1998"), ExamScore = 4.8F },
                    new Student { Id = 184, GroupId = 11, FirstName = "Лука", LastName = "Лаврентьев", DateOfBirth = DateTime.Parse("20-02-1987"), ExamScore = 4.6F },
                    new Student { Id = 185, GroupId = 11, FirstName = "Мирон", LastName = "Лавров", DateOfBirth = DateTime.Parse("26-04-1987"), ExamScore = 3.5F },
                    new Student { Id = 186, GroupId = 12, FirstName = "Даниил", LastName = "Тихонов", DateOfBirth = DateTime.Parse("16-09-1990"), ExamScore = 4.5F },
                    new Student { Id = 187, GroupId = 12, FirstName = "Ника", LastName = "Кочетова", DateOfBirth = DateTime.Parse("12-01-2001"), ExamScore = 3.1F },
                    new Student { Id = 188, GroupId = 12, FirstName = "Полина", LastName = "Сорокина", DateOfBirth = DateTime.Parse("25-04-1986"), ExamScore = 4.7F },
                    new Student { Id = 189, GroupId = 12, FirstName = "Анна", LastName = "Митрофанова", DateOfBirth = DateTime.Parse("17-10-2001"), ExamScore = 3.4F },
                    new Student { Id = 190, GroupId = 12, FirstName = "Фёдор", LastName = "Виноградов", DateOfBirth = DateTime.Parse("05-02-1998"), ExamScore = 4.5F },
                    new Student { Id = 191, GroupId = 12, FirstName = "Екатерина", LastName = "Елизарова", DateOfBirth = DateTime.Parse("08-04-1986"), ExamScore = 3.8F },
                    new Student { Id = 192, GroupId = 13, FirstName = "Ангелина", LastName = "Иванова", DateOfBirth = DateTime.Parse("13-10-1990"), ExamScore = 3.5F },
                    new Student { Id = 193, GroupId = 13, FirstName = "Елизавета", LastName = "Козловская", DateOfBirth = DateTime.Parse("04-06-1994"), ExamScore = 4.9F },
                    new Student { Id = 194, GroupId = 13, FirstName = "Егор", LastName = "Гаврилов", DateOfBirth = DateTime.Parse("03-04-1989"), ExamScore = 4F },
                    new Student { Id = 195, GroupId = 13, FirstName = "Аглая", LastName = "Смирнова", DateOfBirth = DateTime.Parse("13-10-1994"), ExamScore = 3.3F },
                    new Student { Id = 196, GroupId = 13, FirstName = "Матвей", LastName = "Потапов", DateOfBirth = DateTime.Parse("31-05-1996"), ExamScore = 3.1F },
                    new Student { Id = 197, GroupId = 13, FirstName = "Артём", LastName = "Зайцев", DateOfBirth = DateTime.Parse("17-02-1991"), ExamScore = 3.3F },
                    new Student { Id = 198, GroupId = 13, FirstName = "Алиса", LastName = "Алексеева", DateOfBirth = DateTime.Parse("23-09-1993"), ExamScore = 3.4F },
                    new Student { Id = 199, GroupId = 13, FirstName = "Макар", LastName = "Семенов", DateOfBirth = DateTime.Parse("09-10-1991"), ExamScore = 3F },
                    new Student { Id = 200, GroupId = 13, FirstName = "Артур", LastName = "Некрасов", DateOfBirth = DateTime.Parse("08-03-1994"), ExamScore = 4.6F },
                    new Student { Id = 201, GroupId = 13, FirstName = "Анастасия", LastName = "Парамонова", DateOfBirth = DateTime.Parse("09-07-1993"), ExamScore = 4.4F },
                    new Student { Id = 202, GroupId = 13, FirstName = "Михаил", LastName = "Муратов", DateOfBirth = DateTime.Parse("16-10-1995"), ExamScore = 4.9F },
                    new Student { Id = 203, GroupId = 13, FirstName = "Максим", LastName = "Андреев", DateOfBirth = DateTime.Parse("29-11-1994"), ExamScore = 3.3F },
                    new Student { Id = 204, GroupId = 14, FirstName = "Мирон", LastName = "Коновалов", DateOfBirth = DateTime.Parse("24-06-1992"), ExamScore = 3.2F },
                    new Student { Id = 205, GroupId = 14, FirstName = "Алёна", LastName = "Фетисова", DateOfBirth = DateTime.Parse("20-07-1990"), ExamScore = 5F },
                    new Student { Id = 206, GroupId = 14, FirstName = "Таисия", LastName = "Морозова", DateOfBirth = DateTime.Parse("06-09-1992"), ExamScore = 3.8F },
                    new Student { Id = 207, GroupId = 14, FirstName = "Злата", LastName = "Соколова", DateOfBirth = DateTime.Parse("18-09-1986"), ExamScore = 3.2F },
                    new Student { Id = 208, GroupId = 14, FirstName = "Полина", LastName = "Карпова", DateOfBirth = DateTime.Parse("11-01-1998"), ExamScore = 4.6F },
                    new Student { Id = 209, GroupId = 14, FirstName = "Даниил", LastName = "Шилов", DateOfBirth = DateTime.Parse("24-08-1996"), ExamScore = 4.1F },
                    new Student { Id = 210, GroupId = 14, FirstName = "Никита", LastName = "Быков", DateOfBirth = DateTime.Parse("06-08-1985"), ExamScore = 4.6F },
                    new Student { Id = 211, GroupId = 14, FirstName = "Иван", LastName = "Зимин", DateOfBirth = DateTime.Parse("28-06-1989"), ExamScore = 3F },
                    new Student { Id = 212, GroupId = 14, FirstName = "Максим", LastName = "Болдырев", DateOfBirth = DateTime.Parse("09-11-1991"), ExamScore = 4.4F },
                    new Student { Id = 213, GroupId = 14, FirstName = "Владислав", LastName = "Кудряшов", DateOfBirth = DateTime.Parse("16-11-1998"), ExamScore = 4.6F },
                    new Student { Id = 214, GroupId = 14, FirstName = "Мирослава", LastName = "Федорова", DateOfBirth = DateTime.Parse("29-10-1992"), ExamScore = 4.9F },
                    new Student { Id = 215, GroupId = 14, FirstName = "Лев", LastName = "Сальников", DateOfBirth = DateTime.Parse("31-10-1985"), ExamScore = 3.9F },
                    new Student { Id = 216, GroupId = 14, FirstName = "Роман", LastName = "Елизаров", DateOfBirth = DateTime.Parse("14-04-1994"), ExamScore = 4.6F },
                    new Student { Id = 217, GroupId = 14, FirstName = "Сергей", LastName = "Кузьмин", DateOfBirth = DateTime.Parse("16-06-2000"), ExamScore = 4.9F },
                    new Student { Id = 218, GroupId = 14, FirstName = "Варвара", LastName = "Кудряшова", DateOfBirth = DateTime.Parse("07-01-1996"), ExamScore = 4.6F },
                    new Student { Id = 219, GroupId = 14, FirstName = "Олеся", LastName = "Борисова", DateOfBirth = DateTime.Parse("09-09-1990"), ExamScore = 4.8F },
                    new Student { Id = 220, GroupId = 14, FirstName = "Виктория", LastName = "Прохорова", DateOfBirth = DateTime.Parse("04-03-1986"), ExamScore = 4.9F },
                    new Student { Id = 221, GroupId = 14, FirstName = "Артём", LastName = "Поляков", DateOfBirth = DateTime.Parse("20-06-1998"), ExamScore = 3.3F },
                    new Student { Id = 222, GroupId = 14, FirstName = "Василиса", LastName = "Кузнецова", DateOfBirth = DateTime.Parse("09-12-1994"), ExamScore = 3F },
                    new Student { Id = 223, GroupId = 14, FirstName = "Владислав", LastName = "Дубинин", DateOfBirth = DateTime.Parse("06-11-1990"), ExamScore = 4.9F },
                    new Student { Id = 224, GroupId = 14, FirstName = "Руслан", LastName = "Михайлов", DateOfBirth = DateTime.Parse("17-04-1998"), ExamScore = 3.5F },
                    new Student { Id = 225, GroupId = 14, FirstName = "Таисия", LastName = "Королева", DateOfBirth = DateTime.Parse("27-02-1988"), ExamScore = 3.6F },
                    new Student { Id = 226, GroupId = 14, FirstName = "Варвара", LastName = "Денисова", DateOfBirth = DateTime.Parse("27-10-1985"), ExamScore = 4.4F },
                    new Student { Id = 227, GroupId = 15, FirstName = "Анна", LastName = "Анохина", DateOfBirth = DateTime.Parse("29-12-1992"), ExamScore = 3.6F },
                    new Student { Id = 228, GroupId = 15, FirstName = "Всеволод", LastName = "Носов", DateOfBirth = DateTime.Parse("02-11-1987"), ExamScore = 3.4F },
                    new Student { Id = 229, GroupId = 15, FirstName = "Матвей", LastName = "Панфилов", DateOfBirth = DateTime.Parse("03-07-1989"), ExamScore = 4.1F },
                    new Student { Id = 230, GroupId = 15, FirstName = "Марк", LastName = "Коновалов", DateOfBirth = DateTime.Parse("13-01-1986"), ExamScore = 4.1F },
                    new Student { Id = 231, GroupId = 15, FirstName = "Анастасия", LastName = "Комарова", DateOfBirth = DateTime.Parse("28-07-1991"), ExamScore = 3.8F },
                    new Student { Id = 232, GroupId = 15, FirstName = "Артём", LastName = "Алексеев", DateOfBirth = DateTime.Parse("16-09-1995"), ExamScore = 4.5F },
                    new Student { Id = 233, GroupId = 15, FirstName = "Ульяна", LastName = "Морозова", DateOfBirth = DateTime.Parse("04-08-1994"), ExamScore = 3.5F },
                    new Student { Id = 234, GroupId = 15, FirstName = "Арина", LastName = "Крылова", DateOfBirth = DateTime.Parse("09-04-2001"), ExamScore = 3.5F },
                    new Student { Id = 235, GroupId = 15, FirstName = "Мирослава", LastName = "Колпакова", DateOfBirth = DateTime.Parse("18-04-1999"), ExamScore = 3F },
                    new Student { Id = 236, GroupId = 15, FirstName = "Кирилл", LastName = "Лаврентьев", DateOfBirth = DateTime.Parse("15-11-2000"), ExamScore = 4.3F },
                    new Student { Id = 237, GroupId = 15, FirstName = "Кирилл", LastName = "Калачев", DateOfBirth = DateTime.Parse("20-08-1992"), ExamScore = 4F },
                    new Student { Id = 238, GroupId = 15, FirstName = "Марк", LastName = "Левин", DateOfBirth = DateTime.Parse("19-05-2001"), ExamScore = 4.2F },
                    new Student { Id = 239, GroupId = 15, FirstName = "Николай", LastName = "Лобанов", DateOfBirth = DateTime.Parse("02-10-1998"), ExamScore = 5F },
                    new Student { Id = 240, GroupId = 15, FirstName = "Карина", LastName = "Иванова", DateOfBirth = DateTime.Parse("25-12-1987"), ExamScore = 3.4F },
                    new Student { Id = 241, GroupId = 15, FirstName = "Варвара", LastName = "Миронова", DateOfBirth = DateTime.Parse("13-06-1999"), ExamScore = 3.5F },
                    new Student { Id = 242, GroupId = 15, FirstName = "Мирослава", LastName = "Смирнова", DateOfBirth = DateTime.Parse("24-09-2001"), ExamScore = 4.8F },
                    new Student { Id = 243, GroupId = 15, FirstName = "Артём", LastName = "Киселев", DateOfBirth = DateTime.Parse("24-01-1993"), ExamScore = 3.1F },
                    new Student { Id = 244, GroupId = 15, FirstName = "Константин", LastName = "Панин", DateOfBirth = DateTime.Parse("01-04-1988"), ExamScore = 4.9F },
                    new Student { Id = 245, GroupId = 15, FirstName = "Яна", LastName = "Волкова", DateOfBirth = DateTime.Parse("23-12-1990"), ExamScore = 3.8F },
                    new Student { Id = 246, GroupId = 15, FirstName = "Варвара", LastName = "Романова", DateOfBirth = DateTime.Parse("11-06-1990"), ExamScore = 4.7F },
                    new Student { Id = 247, GroupId = 16, FirstName = "Али", LastName = "Романов", DateOfBirth = DateTime.Parse("17-11-1994"), ExamScore = 4F },
                    new Student { Id = 248, GroupId = 16, FirstName = "Елизавета", LastName = "Ермакова", DateOfBirth = DateTime.Parse("01-07-1993"), ExamScore = 3.8F },
                    new Student { Id = 249, GroupId = 16, FirstName = "Павел", LastName = "Голубев", DateOfBirth = DateTime.Parse("18-01-1987"), ExamScore = 4.6F },
                    new Student { Id = 250, GroupId = 16, FirstName = "Валерия", LastName = "Вавилова", DateOfBirth = DateTime.Parse("11-05-1986"), ExamScore = 3.1F },
                    new Student { Id = 251, GroupId = 16, FirstName = "Демид", LastName = "Жуков", DateOfBirth = DateTime.Parse("16-06-1985"), ExamScore = 4.7F },
                    new Student { Id = 252, GroupId = 16, FirstName = "Дмитрий", LastName = "Елисеев", DateOfBirth = DateTime.Parse("26-07-1988"), ExamScore = 3.9F },
                    new Student { Id = 253, GroupId = 16, FirstName = "Артур", LastName = "Лобанов", DateOfBirth = DateTime.Parse("02-05-1993"), ExamScore = 3.5F },
                    new Student { Id = 254, GroupId = 16, FirstName = "Лев", LastName = "Волков", DateOfBirth = DateTime.Parse("14-05-1995"), ExamScore = 3.5F },
                    new Student { Id = 255, GroupId = 16, FirstName = "Никита", LastName = "Соловьев", DateOfBirth = DateTime.Parse("29-12-2001"), ExamScore = 4.2F },
                    new Student { Id = 256, GroupId = 16, FirstName = "Яна", LastName = "Беляева", DateOfBirth = DateTime.Parse("11-02-1993"), ExamScore = 4.9F },
                    new Student { Id = 257, GroupId = 16, FirstName = "Артём", LastName = "Постников", DateOfBirth = DateTime.Parse("10-01-1987"), ExamScore = 4.6F },
                    new Student { Id = 258, GroupId = 16, FirstName = "Милослава", LastName = "Грачева", DateOfBirth = DateTime.Parse("05-10-1989"), ExamScore = 4F },
                    new Student { Id = 259, GroupId = 16, FirstName = "Милана", LastName = "Макарова", DateOfBirth = DateTime.Parse("25-11-1992"), ExamScore = 3.5F },
                    new Student { Id = 260, GroupId = 16, FirstName = "София", LastName = "Зубова", DateOfBirth = DateTime.Parse("21-08-1993"), ExamScore = 3.5F },
                    new Student { Id = 261, GroupId = 16, FirstName = "Алёна", LastName = "Горячева", DateOfBirth = DateTime.Parse("25-03-1998"), ExamScore = 3.7F },
                    new Student { Id = 262, GroupId = 16, FirstName = "Виктория", LastName = "Смирнова", DateOfBirth = DateTime.Parse("19-12-1991"), ExamScore = 3.5F },
                    new Student { Id = 263, GroupId = 16, FirstName = "Матвей", LastName = "Сахаров", DateOfBirth = DateTime.Parse("06-09-1985"), ExamScore = 4.5F },
                    new Student { Id = 264, GroupId = 16, FirstName = "Мия", LastName = "Исаева", DateOfBirth = DateTime.Parse("24-11-1995"), ExamScore = 3.3F },
                    new Student { Id = 265, GroupId = 16, FirstName = "Матвей", LastName = "Коновалов", DateOfBirth = DateTime.Parse("27-01-1999"), ExamScore = 4.6F },
                    new Student { Id = 266, GroupId = 16, FirstName = "Дарья", LastName = "Иванова", DateOfBirth = DateTime.Parse("22-09-1994"), ExamScore = 4.8F },
                    new Student { Id = 267, GroupId = 16, FirstName = "Мария", LastName = "Кириллова", DateOfBirth = DateTime.Parse("04-08-1999"), ExamScore = 4F },
                    new Student { Id = 268, GroupId = 17, FirstName = "Савелий", LastName = "Некрасов", DateOfBirth = DateTime.Parse("25-09-2001"), ExamScore = 3.1F },
                    new Student { Id = 269, GroupId = 17, FirstName = "Светлана", LastName = "Астафьева", DateOfBirth = DateTime.Parse("10-06-1991"), ExamScore = 3.2F },
                    new Student { Id = 270, GroupId = 17, FirstName = "Мария", LastName = "Максимова", DateOfBirth = DateTime.Parse("01-05-1990"), ExamScore = 3.9F },
                    new Student { Id = 271, GroupId = 17, FirstName = "Степан", LastName = "Зайцев", DateOfBirth = DateTime.Parse("15-12-1985"), ExamScore = 4.9F },
                    new Student { Id = 272, GroupId = 17, FirstName = "Никита", LastName = "Григорьев", DateOfBirth = DateTime.Parse("17-02-1987"), ExamScore = 3.6F },
                    new Student { Id = 273, GroupId = 17, FirstName = "Полина", LastName = "Елизарова", DateOfBirth = DateTime.Parse("27-01-1986"), ExamScore = 3.3F },
                    new Student { Id = 274, GroupId = 17, FirstName = "Полина", LastName = "Яковлева", DateOfBirth = DateTime.Parse("13-09-1986"), ExamScore = 3.5F },
                    new Student { Id = 275, GroupId = 17, FirstName = "Иван", LastName = "Виноградов", DateOfBirth = DateTime.Parse("30-03-1999"), ExamScore = 4.6F },
                    new Student { Id = 276, GroupId = 17, FirstName = "Александра", LastName = "Сергеева", DateOfBirth = DateTime.Parse("22-12-1985"), ExamScore = 5F },
                    new Student { Id = 277, GroupId = 17, FirstName = "Алёна", LastName = "Боброва", DateOfBirth = DateTime.Parse("21-08-1989"), ExamScore = 4.1F },
                    new Student { Id = 278, GroupId = 17, FirstName = "Софья", LastName = "Зимина", DateOfBirth = DateTime.Parse("07-03-1998"), ExamScore = 3.9F },
                    new Student { Id = 279, GroupId = 17, FirstName = "Денис", LastName = "Попов", DateOfBirth = DateTime.Parse("05-06-1998"), ExamScore = 3.9F },
                    new Student { Id = 280, GroupId = 17, FirstName = "Матвей", LastName = "Пугачев", DateOfBirth = DateTime.Parse("24-05-2001"), ExamScore = 3.3F },
                    new Student { Id = 281, GroupId = 18, FirstName = "Гордей", LastName = "Морозов", DateOfBirth = DateTime.Parse("11-03-1991"), ExamScore = 3.1F },
                    new Student { Id = 282, GroupId = 18, FirstName = "Евгения", LastName = "Назарова", DateOfBirth = DateTime.Parse("23-05-1993"), ExamScore = 4.1F },
                    new Student { Id = 283, GroupId = 18, FirstName = "Марк", LastName = "Журавлев", DateOfBirth = DateTime.Parse("19-05-1986"), ExamScore = 4.7F },
                    new Student { Id = 284, GroupId = 18, FirstName = "Стефания", LastName = "Кузнецова", DateOfBirth = DateTime.Parse("04-01-1996"), ExamScore = 4.5F },
                    new Student { Id = 285, GroupId = 18, FirstName = "Арсений", LastName = "Алексеев", DateOfBirth = DateTime.Parse("25-02-1989"), ExamScore = 4.6F },
                    new Student { Id = 286, GroupId = 18, FirstName = "Александр", LastName = "Панкратов", DateOfBirth = DateTime.Parse("02-03-1995"), ExamScore = 4.8F },
                    new Student { Id = 287, GroupId = 18, FirstName = "Ульяна", LastName = "Смирнова", DateOfBirth = DateTime.Parse("02-10-1996"), ExamScore = 4.5F },
                    new Student { Id = 288, GroupId = 18, FirstName = "Макар", LastName = "Логинов", DateOfBirth = DateTime.Parse("10-05-1985"), ExamScore = 3.6F },
                    new Student { Id = 289, GroupId = 18, FirstName = "Артём", LastName = "Борисов", DateOfBirth = DateTime.Parse("22-01-2000"), ExamScore = 3.3F },
                    new Student { Id = 290, GroupId = 18, FirstName = "Александр", LastName = "Кузин", DateOfBirth = DateTime.Parse("28-01-1992"), ExamScore = 5F },
                    new Student { Id = 291, GroupId = 18, FirstName = "Ульяна", LastName = "Соколова", DateOfBirth = DateTime.Parse("29-06-1998"), ExamScore = 4F },
                    new Student { Id = 292, GroupId = 18, FirstName = "Вера", LastName = "Устинова", DateOfBirth = DateTime.Parse("06-06-1996"), ExamScore = 4.1F },
                    new Student { Id = 293, GroupId = 18, FirstName = "Ульяна", LastName = "Данилова", DateOfBirth = DateTime.Parse("28-07-1994"), ExamScore = 4.2F },
                    new Student { Id = 294, GroupId = 18, FirstName = "Арина", LastName = "Ежова", DateOfBirth = DateTime.Parse("16-11-2000"), ExamScore = 4.5F },
                    new Student { Id = 295, GroupId = 18, FirstName = "Фёдор", LastName = "Морозов", DateOfBirth = DateTime.Parse("07-06-1985"), ExamScore = 3.2F },
                    new Student { Id = 296, GroupId = 18, FirstName = "Анастасия", LastName = "Дементьева", DateOfBirth = DateTime.Parse("02-09-1985"), ExamScore = 3.5F },
                    new Student { Id = 297, GroupId = 18, FirstName = "Милана", LastName = "Степанова", DateOfBirth = DateTime.Parse("20-04-1988"), ExamScore = 4.9F },
                    new Student { Id = 298, GroupId = 19, FirstName = "Мария", LastName = "Осипова", DateOfBirth = DateTime.Parse("30-10-1989"), ExamScore = 5F },
                    new Student { Id = 299, GroupId = 19, FirstName = "Екатерина", LastName = "Васильева", DateOfBirth = DateTime.Parse("08-06-1994"), ExamScore = 3.4F },
                    new Student { Id = 300, GroupId = 19, FirstName = "Иван", LastName = "Сидоров", DateOfBirth = DateTime.Parse("16-07-1998"), ExamScore = 3F },
                    new Student { Id = 301, GroupId = 19, FirstName = "Тимофей", LastName = "Данилов", DateOfBirth = DateTime.Parse("17-11-1990"), ExamScore = 3.1F },
                    new Student { Id = 302, GroupId = 19, FirstName = "Георгий", LastName = "Крюков", DateOfBirth = DateTime.Parse("17-11-1989"), ExamScore = 3.1F },
                    new Student { Id = 303, GroupId = 19, FirstName = "Тимофей", LastName = "Терехов", DateOfBirth = DateTime.Parse("08-10-1986"), ExamScore = 4.3F },
                    new Student { Id = 304, GroupId = 19, FirstName = "Никита", LastName = "Павловский", DateOfBirth = DateTime.Parse("02-04-1995"), ExamScore = 3F },
                    new Student { Id = 305, GroupId = 20, FirstName = "Татьяна", LastName = "Голикова", DateOfBirth = DateTime.Parse("25-09-1987"), ExamScore = 4.4F },
                    new Student { Id = 306, GroupId = 20, FirstName = "Артём", LastName = "Власов", DateOfBirth = DateTime.Parse("02-04-1990"), ExamScore = 3.6F },
                    new Student { Id = 307, GroupId = 20, FirstName = "Амира", LastName = "Малинина", DateOfBirth = DateTime.Parse("22-05-1993"), ExamScore = 4.1F },
                    new Student { Id = 308, GroupId = 20, FirstName = "Алексей", LastName = "Данилов", DateOfBirth = DateTime.Parse("10-09-2001"), ExamScore = 3.4F },
                    new Student { Id = 309, GroupId = 20, FirstName = "Егор", LastName = "Назаров", DateOfBirth = DateTime.Parse("20-04-1995"), ExamScore = 4.1F },
                    new Student { Id = 310, GroupId = 20, FirstName = "Василий", LastName = "Алексеев", DateOfBirth = DateTime.Parse("01-12-2001"), ExamScore = 4.3F },
                    new Student { Id = 311, GroupId = 20, FirstName = "Дмитрий", LastName = "Лобанов", DateOfBirth = DateTime.Parse("06-10-1993"), ExamScore = 3.1F },
                    new Student { Id = 312, GroupId = 20, FirstName = "Вероника", LastName = "Орехова", DateOfBirth = DateTime.Parse("08-01-1993"), ExamScore = 3.5F },
                    new Student { Id = 313, GroupId = 20, FirstName = "Анастасия", LastName = "Коновалова", DateOfBirth = DateTime.Parse("13-01-1995"), ExamScore = 4.5F },
                    new Student { Id = 314, GroupId = 20, FirstName = "Лев", LastName = "Васильев", DateOfBirth = DateTime.Parse("12-12-1989"), ExamScore = 3.8F },
                    new Student { Id = 315, GroupId = 20, FirstName = "Виктория", LastName = "Митрофанова", DateOfBirth = DateTime.Parse("30-10-1997"), ExamScore = 3.8F },
                    new Student { Id = 316, GroupId = 20, FirstName = "Юлия", LastName = "Новикова", DateOfBirth = DateTime.Parse("04-01-1991"), ExamScore = 4F },
                    new Student { Id = 317, GroupId = 20, FirstName = "Максим", LastName = "Кузнецов", DateOfBirth = DateTime.Parse("20-07-2000"), ExamScore = 4.2F },
                    new Student { Id = 318, GroupId = 20, FirstName = "Александр", LastName = "Гусев", DateOfBirth = DateTime.Parse("16-12-1999"), ExamScore = 3.1F },
                    new Student { Id = 319, GroupId = 20, FirstName = "Оливия", LastName = "Маркина", DateOfBirth = DateTime.Parse("10-01-1985"), ExamScore = 3.9F },
                    new Student { Id = 320, GroupId = 21, FirstName = "Антон", LastName = "Овчинников", DateOfBirth = DateTime.Parse("29-05-1988"), ExamScore = 4.5F },
                    new Student { Id = 321, GroupId = 21, FirstName = "Александр", LastName = "Яковлев", DateOfBirth = DateTime.Parse("05-07-1999"), ExamScore = 3.5F },
                    new Student { Id = 322, GroupId = 21, FirstName = "Юлия", LastName = "Михеева", DateOfBirth = DateTime.Parse("23-10-1996"), ExamScore = 5F },
                    new Student { Id = 323, GroupId = 21, FirstName = "Алексей", LastName = "Смирнов", DateOfBirth = DateTime.Parse("18-03-1996"), ExamScore = 3.9F },
                    new Student { Id = 324, GroupId = 21, FirstName = "Мелисса", LastName = "Ермакова", DateOfBirth = DateTime.Parse("18-08-1987"), ExamScore = 3.4F },
                    new Student { Id = 325, GroupId = 21, FirstName = "Тигран", LastName = "Ермаков", DateOfBirth = DateTime.Parse("01-07-1997"), ExamScore = 4.5F },
                    new Student { Id = 326, GroupId = 21, FirstName = "Диана", LastName = "Королева", DateOfBirth = DateTime.Parse("18-12-1990"), ExamScore = 4F },
                    new Student { Id = 327, GroupId = 21, FirstName = "Григорий", LastName = "Николаев", DateOfBirth = DateTime.Parse("06-10-1997"), ExamScore = 4.3F },
                    new Student { Id = 328, GroupId = 21, FirstName = "Артём", LastName = "Кузьмин", DateOfBirth = DateTime.Parse("17-09-1989"), ExamScore = 3.9F },
                    new Student { Id = 329, GroupId = 21, FirstName = "Варвара", LastName = "Николаева", DateOfBirth = DateTime.Parse("07-04-1990"), ExamScore = 4.7F },
                    new Student { Id = 330, GroupId = 21, FirstName = "Виктория", LastName = "Казакова", DateOfBirth = DateTime.Parse("19-07-1998"), ExamScore = 3.5F },
                    new Student { Id = 331, GroupId = 21, FirstName = "Александр", LastName = "Васильев", DateOfBirth = DateTime.Parse("27-10-1992"), ExamScore = 3.8F },
                    new Student { Id = 332, GroupId = 21, FirstName = "Софья", LastName = "Трофимова", DateOfBirth = DateTime.Parse("10-03-1996"), ExamScore = 4.8F },
                    new Student { Id = 333, GroupId = 21, FirstName = "София", LastName = "Рожкова", DateOfBirth = DateTime.Parse("08-10-1996"), ExamScore = 3.7F },
                    new Student { Id = 334, GroupId = 21, FirstName = "Платон", LastName = "Третьяков", DateOfBirth = DateTime.Parse("29-10-1990"), ExamScore = 3.9F },
                    new Student { Id = 335, GroupId = 22, FirstName = "Ника", LastName = "Ильинская", DateOfBirth = DateTime.Parse("24-08-1985"), ExamScore = 3.3F },
                    new Student { Id = 336, GroupId = 22, FirstName = "Эмилия", LastName = "Кононова", DateOfBirth = DateTime.Parse("19-04-1989"), ExamScore = 3.5F },
                    new Student { Id = 337, GroupId = 22, FirstName = "Михаил", LastName = "Иванов", DateOfBirth = DateTime.Parse("05-11-1987"), ExamScore = 4.2F },
                    new Student { Id = 338, GroupId = 22, FirstName = "Ксения", LastName = "Богданова", DateOfBirth = DateTime.Parse("24-02-2001"), ExamScore = 3.9F },
                    new Student { Id = 339, GroupId = 22, FirstName = "Екатерина", LastName = "Давыдова", DateOfBirth = DateTime.Parse("12-09-1989"), ExamScore = 3.5F },
                    new Student { Id = 340, GroupId = 22, FirstName = "Ольга", LastName = "Герасимова", DateOfBirth = DateTime.Parse("09-07-1998"), ExamScore = 4.6F },
                    new Student { Id = 341, GroupId = 22, FirstName = "Даниэль", LastName = "Козловский", DateOfBirth = DateTime.Parse("24-07-2001"), ExamScore = 3.1F },
                    new Student { Id = 342, GroupId = 22, FirstName = "Дарья", LastName = "Горячева", DateOfBirth = DateTime.Parse("09-02-1992"), ExamScore = 3.6F },
                    new Student { Id = 343, GroupId = 22, FirstName = "Мирон", LastName = "Архипов", DateOfBirth = DateTime.Parse("03-03-2000"), ExamScore = 5F },
                    new Student { Id = 344, GroupId = 22, FirstName = "Даниил", LastName = "Колесов", DateOfBirth = DateTime.Parse("26-08-1994"), ExamScore = 3.9F },
                    new Student { Id = 345, GroupId = 22, FirstName = "Роман", LastName = "Корнев", DateOfBirth = DateTime.Parse("06-12-1993"), ExamScore = 3.4F },
                    new Student { Id = 346, GroupId = 22, FirstName = "Милана", LastName = "Голубева", DateOfBirth = DateTime.Parse("24-12-1999"), ExamScore = 4.6F },
                    new Student { Id = 347, GroupId = 22, FirstName = "Фёдор", LastName = "Романов", DateOfBirth = DateTime.Parse("05-05-1996"), ExamScore = 3.9F },
                    new Student { Id = 348, GroupId = 22, FirstName = "Эмин", LastName = "Зимин", DateOfBirth = DateTime.Parse("09-01-1994"), ExamScore = 4F },
                    new Student { Id = 349, GroupId = 22, FirstName = "Елизавета", LastName = "Емельянова", DateOfBirth = DateTime.Parse("16-09-1985"), ExamScore = 4.4F },
                    new Student { Id = 350, GroupId = 22, FirstName = "Екатерина", LastName = "Ефимова", DateOfBirth = DateTime.Parse("05-12-1992"), ExamScore = 3.1F },
                    new Student { Id = 351, GroupId = 22, FirstName = "Ева", LastName = "Щербакова", DateOfBirth = DateTime.Parse("04-07-1995"), ExamScore = 4.9F },
                    new Student { Id = 352, GroupId = 22, FirstName = "Дмитрий", LastName = "Гусев", DateOfBirth = DateTime.Parse("05-02-1992"), ExamScore = 4.5F },
                    new Student { Id = 353, GroupId = 22, FirstName = "Ольга", LastName = "Трофимова", DateOfBirth = DateTime.Parse("01-04-2001"), ExamScore = 3.4F },
                    new Student { Id = 354, GroupId = 22, FirstName = "Олеся", LastName = "Гаврилова", DateOfBirth = DateTime.Parse("18-05-1988"), ExamScore = 4F },
                    new Student { Id = 355, GroupId = 22, FirstName = "Алия", LastName = "Сомова", DateOfBirth = DateTime.Parse("08-10-1988"), ExamScore = 3F },
                    new Student { Id = 356, GroupId = 22, FirstName = "Леон", LastName = "Белоусов", DateOfBirth = DateTime.Parse("19-09-1989"), ExamScore = 4.5F },
                    new Student { Id = 357, GroupId = 22, FirstName = "Виктория", LastName = "Ершова", DateOfBirth = DateTime.Parse("01-09-1988"), ExamScore = 3.5F },
                    new Student { Id = 358, GroupId = 22, FirstName = "Никита", LastName = "Иванов", DateOfBirth = DateTime.Parse("23-01-1988"), ExamScore = 3.9F },
                    new Student { Id = 359, GroupId = 23, FirstName = "Марк", LastName = "Никитин", DateOfBirth = DateTime.Parse("31-07-1988"), ExamScore = 4.8F },
                    new Student { Id = 360, GroupId = 23, FirstName = "Александр", LastName = "Афанасьев", DateOfBirth = DateTime.Parse("21-06-1988"), ExamScore = 3.8F },
                    new Student { Id = 361, GroupId = 23, FirstName = "Мирослава", LastName = "Захарова", DateOfBirth = DateTime.Parse("23-03-1995"), ExamScore = 5F },
                    new Student { Id = 362, GroupId = 23, FirstName = "София", LastName = "Зимина", DateOfBirth = DateTime.Parse("10-11-1990"), ExamScore = 4.8F },
                    new Student { Id = 363, GroupId = 23, FirstName = "Виктория", LastName = "Козлова", DateOfBirth = DateTime.Parse("04-07-1986"), ExamScore = 5F },
                    new Student { Id = 364, GroupId = 23, FirstName = "Софья", LastName = "Панова", DateOfBirth = DateTime.Parse("09-02-1996"), ExamScore = 4.1F },
                    new Student { Id = 365, GroupId = 23, FirstName = "Василиса", LastName = "Смирнова", DateOfBirth = DateTime.Parse("02-02-1996"), ExamScore = 3.8F },
                    new Student { Id = 366, GroupId = 23, FirstName = "Яна", LastName = "Семина", DateOfBirth = DateTime.Parse("13-03-2001"), ExamScore = 5F },
                    new Student { Id = 367, GroupId = 23, FirstName = "Всеволод", LastName = "Тихонов", DateOfBirth = DateTime.Parse("09-06-1985"), ExamScore = 4.9F },
                    new Student { Id = 368, GroupId = 23, FirstName = "Дмитрий", LastName = "Горбачев", DateOfBirth = DateTime.Parse("27-03-1988"), ExamScore = 4.2F },
                    new Student { Id = 369, GroupId = 23, FirstName = "Софья", LastName = "Смирнова", DateOfBirth = DateTime.Parse("24-02-1995"), ExamScore = 5F },
                    new Student { Id = 370, GroupId = 24, FirstName = "Полина", LastName = "Чеботарева", DateOfBirth = DateTime.Parse("28-01-1998"), ExamScore = 4.9F },
                    new Student { Id = 371, GroupId = 24, FirstName = "Анастасия", LastName = "Григорьева", DateOfBirth = DateTime.Parse("13-06-2001"), ExamScore = 3.2F },
                    new Student { Id = 372, GroupId = 24, FirstName = "Иван", LastName = "Мартынов", DateOfBirth = DateTime.Parse("25-11-1996"), ExamScore = 3.5F },
                    new Student { Id = 373, GroupId = 24, FirstName = "Максим", LastName = "Суслов", DateOfBirth = DateTime.Parse("13-11-1988"), ExamScore = 4F },
                    new Student { Id = 374, GroupId = 24, FirstName = "Екатерина", LastName = "Беляева", DateOfBirth = DateTime.Parse("18-03-2001"), ExamScore = 3.7F },
                    new Student { Id = 375, GroupId = 24, FirstName = "Дмитрий", LastName = "Герасимов", DateOfBirth = DateTime.Parse("08-10-1985"), ExamScore = 4.9F },
                    new Student { Id = 376, GroupId = 24, FirstName = "Фёдор", LastName = "Иванов", DateOfBirth = DateTime.Parse("13-04-1988"), ExamScore = 3.7F },
                    new Student { Id = 377, GroupId = 24, FirstName = "Анна", LastName = "Иванова", DateOfBirth = DateTime.Parse("27-09-1994"), ExamScore = 3.8F },
                    new Student { Id = 378, GroupId = 24, FirstName = "Алиса", LastName = "Никитина", DateOfBirth = DateTime.Parse("26-02-1986"), ExamScore = 3.4F },
                    new Student { Id = 379, GroupId = 24, FirstName = "Никита", LastName = "Молчанов", DateOfBirth = DateTime.Parse("08-01-1987"), ExamScore = 3.9F },
                    new Student { Id = 380, GroupId = 24, FirstName = "Василиса", LastName = "Шарова", DateOfBirth = DateTime.Parse("19-07-1999"), ExamScore = 3.3F },
                    new Student { Id = 381, GroupId = 24, FirstName = "Артём", LastName = "Михайлов", DateOfBirth = DateTime.Parse("12-06-1994"), ExamScore = 3.3F },
                    new Student { Id = 382, GroupId = 24, FirstName = "Дмитрий", LastName = "Кошелев", DateOfBirth = DateTime.Parse("10-08-1986"), ExamScore = 4.1F },
                    new Student { Id = 383, GroupId = 24, FirstName = "Ярослав", LastName = "Черепанов", DateOfBirth = DateTime.Parse("25-08-1993"), ExamScore = 4.9F },
                    new Student { Id = 384, GroupId = 24, FirstName = "Павел", LastName = "Васильев", DateOfBirth = DateTime.Parse("03-07-2001"), ExamScore = 3.1F },
                    new Student { Id = 385, GroupId = 24, FirstName = "Игорь", LastName = "Лапшин", DateOfBirth = DateTime.Parse("11-08-2001"), ExamScore = 3.7F },
                    new Student { Id = 386, GroupId = 24, FirstName = "Богдан", LastName = "Ситников", DateOfBirth = DateTime.Parse("20-06-1985"), ExamScore = 4.9F },
                    new Student { Id = 387, GroupId = 24, FirstName = "Ева", LastName = "Кольцова", DateOfBirth = DateTime.Parse("31-10-1990"), ExamScore = 3F },
                    new Student { Id = 388, GroupId = 24, FirstName = "Алиса", LastName = "Терентьева", DateOfBirth = DateTime.Parse("14-07-1997"), ExamScore = 4.6F },
                    new Student { Id = 389, GroupId = 24, FirstName = "Милана", LastName = "Новикова", DateOfBirth = DateTime.Parse("16-04-2000"), ExamScore = 3.1F },
                    new Student { Id = 390, GroupId = 24, FirstName = "Елизавета", LastName = "Иванова", DateOfBirth = DateTime.Parse("26-03-1993"), ExamScore = 4.1F },
                    new Student { Id = 391, GroupId = 24, FirstName = "Кирилл", LastName = "Соколов", DateOfBirth = DateTime.Parse("31-03-1990"), ExamScore = 4F },
                    new Student { Id = 392, GroupId = 24, FirstName = "Камила", LastName = "Трифонова", DateOfBirth = DateTime.Parse("15-04-1986"), ExamScore = 3.8F },
                    new Student { Id = 393, GroupId = 24, FirstName = "Вероника", LastName = "Григорьева", DateOfBirth = DateTime.Parse("17-01-1994"), ExamScore = 3F },
                    new Student { Id = 394, GroupId = 24, FirstName = "Всеволод", LastName = "Орлов", DateOfBirth = DateTime.Parse("16-10-1986"), ExamScore = 3.6F },
                    new Student { Id = 395, GroupId = 24, FirstName = "Елизавета", LastName = "Золотова", DateOfBirth = DateTime.Parse("10-01-1989"), ExamScore = 4.1F },
                    new Student { Id = 396, GroupId = 24, FirstName = "Алиса", LastName = "Гончарова", DateOfBirth = DateTime.Parse("14-09-1994"), ExamScore = 3.9F },
                    new Student { Id = 397, GroupId = 24, FirstName = "Тимофей", LastName = "Николаев", DateOfBirth = DateTime.Parse("20-07-1998"), ExamScore = 3.3F },
                    new Student { Id = 398, GroupId = 25, FirstName = "Дмитрий", LastName = "Быков", DateOfBirth = DateTime.Parse("18-03-1990"), ExamScore = 3.7F },
                    new Student { Id = 399, GroupId = 25, FirstName = "Милана", LastName = "Игнатова", DateOfBirth = DateTime.Parse("23-05-2000"), ExamScore = 3.3F },
                    new Student { Id = 400, GroupId = 25, FirstName = "Яна", LastName = "Ершова", DateOfBirth = DateTime.Parse("23-06-1997"), ExamScore = 4F },
                    new Student { Id = 401, GroupId = 25, FirstName = "Вероника", LastName = "Соколова", DateOfBirth = DateTime.Parse("29-07-1986"), ExamScore = 4.8F },
                    new Student { Id = 402, GroupId = 25, FirstName = "Агния", LastName = "Попова", DateOfBirth = DateTime.Parse("04-12-1996"), ExamScore = 3.6F },
                    new Student { Id = 403, GroupId = 25, FirstName = "Алексей", LastName = "Кулешов", DateOfBirth = DateTime.Parse("24-12-1985"), ExamScore = 4.7F },
                    new Student { Id = 404, GroupId = 25, FirstName = "Лука", LastName = "Фролов", DateOfBirth = DateTime.Parse("04-01-1998"), ExamScore = 4.9F },
                    new Student { Id = 405, GroupId = 25, FirstName = "Евгения", LastName = "Медведева", DateOfBirth = DateTime.Parse("14-06-1988"), ExamScore = 4F },
                    new Student { Id = 406, GroupId = 25, FirstName = "Василиса", LastName = "Иванова", DateOfBirth = DateTime.Parse("22-01-1990"), ExamScore = 4.5F },
                    new Student { Id = 407, GroupId = 25, FirstName = "Данил", LastName = "Сергеев", DateOfBirth = DateTime.Parse("21-10-1991"), ExamScore = 3.6F },
                    new Student { Id = 408, GroupId = 25, FirstName = "София", LastName = "Лазарева", DateOfBirth = DateTime.Parse("02-08-1994"), ExamScore = 3.2F },
                    new Student { Id = 409, GroupId = 25, FirstName = "Кристина", LastName = "Павлова", DateOfBirth = DateTime.Parse("29-01-1988"), ExamScore = 4.7F },
                    new Student { Id = 410, GroupId = 25, FirstName = "Денис", LastName = "Васильев", DateOfBirth = DateTime.Parse("09-06-1987"), ExamScore = 4.6F },
                    new Student { Id = 411, GroupId = 25, FirstName = "Савелий", LastName = "Орлов", DateOfBirth = DateTime.Parse("09-06-1996"), ExamScore = 4.9F },
                    new Student { Id = 412, GroupId = 25, FirstName = "Злата", LastName = "Попова", DateOfBirth = DateTime.Parse("03-07-1999"), ExamScore = 3.3F },
                    new Student { Id = 413, GroupId = 25, FirstName = "Анна", LastName = "Латышева", DateOfBirth = DateTime.Parse("04-09-1986"), ExamScore = 3.5F },
                    new Student { Id = 414, GroupId = 25, FirstName = "Тимофей", LastName = "Родин", DateOfBirth = DateTime.Parse("22-12-2000"), ExamScore = 4.2F },
                    new Student { Id = 415, GroupId = 25, FirstName = "Андрей", LastName = "Никифоров", DateOfBirth = DateTime.Parse("24-08-1988"), ExamScore = 4.5F },
                    new Student { Id = 416, GroupId = 25, FirstName = "Ясмина", LastName = "Потапова", DateOfBirth = DateTime.Parse("16-11-1999"), ExamScore = 3.6F },
                    new Student { Id = 417, GroupId = 25, FirstName = "Анна", LastName = "Кондратова", DateOfBirth = DateTime.Parse("20-04-1994"), ExamScore = 3.3F },
                    new Student { Id = 418, GroupId = 25, FirstName = "Артур", LastName = "Майоров", DateOfBirth = DateTime.Parse("23-11-1986"), ExamScore = 3.6F },
                    new Student { Id = 419, GroupId = 25, FirstName = "Екатерина", LastName = "Беляева", DateOfBirth = DateTime.Parse("07-09-1992"), ExamScore = 4.5F },
                    new Student { Id = 420, GroupId = 26, FirstName = "Эвелина", LastName = "Белоусова", DateOfBirth = DateTime.Parse("12-09-1996"), ExamScore = 5F },
                    new Student { Id = 421, GroupId = 26, FirstName = "Амина", LastName = "Овчинникова", DateOfBirth = DateTime.Parse("22-05-1989"), ExamScore = 3.7F },
                    new Student { Id = 422, GroupId = 26, FirstName = "Эмма", LastName = "Шевцова", DateOfBirth = DateTime.Parse("14-01-1986"), ExamScore = 3.6F },
                    new Student { Id = 423, GroupId = 26, FirstName = "Всеволод", LastName = "Виноградов", DateOfBirth = DateTime.Parse("13-11-1999"), ExamScore = 3.4F },
                    new Student { Id = 424, GroupId = 26, FirstName = "Максим", LastName = "Жуков", DateOfBirth = DateTime.Parse("09-05-1993"), ExamScore = 3F },
                    new Student { Id = 425, GroupId = 26, FirstName = "Леон", LastName = "Воронин", DateOfBirth = DateTime.Parse("12-09-1993"), ExamScore = 3.8F },
                    new Student { Id = 426, GroupId = 26, FirstName = "Андрей", LastName = "Егоров", DateOfBirth = DateTime.Parse("19-01-1997"), ExamScore = 3.3F },
                    new Student { Id = 427, GroupId = 26, FirstName = "Александра", LastName = "Кольцова", DateOfBirth = DateTime.Parse("09-01-1986"), ExamScore = 4.7F },
                    new Student { Id = 428, GroupId = 26, FirstName = "Михаил", LastName = "Денисов", DateOfBirth = DateTime.Parse("29-03-2001"), ExamScore = 4F },
                    new Student { Id = 429, GroupId = 26, FirstName = "Алиса", LastName = "Давыдова", DateOfBirth = DateTime.Parse("21-03-1988"), ExamScore = 4.3F },
                    new Student { Id = 430, GroupId = 26, FirstName = "Александр", LastName = "Наумов", DateOfBirth = DateTime.Parse("03-10-1992"), ExamScore = 3.3F },
                    new Student { Id = 431, GroupId = 26, FirstName = "Савелий", LastName = "Воронин", DateOfBirth = DateTime.Parse("26-10-1996"), ExamScore = 3.4F },
                    new Student { Id = 432, GroupId = 26, FirstName = "Дарья", LastName = "Березина", DateOfBirth = DateTime.Parse("11-04-1985"), ExamScore = 4.6F },
                    new Student { Id = 433, GroupId = 26, FirstName = "Сара", LastName = "Чеботарева", DateOfBirth = DateTime.Parse("21-01-1995"), ExamScore = 4.3F },
                    new Student { Id = 434, GroupId = 26, FirstName = "Василиса", LastName = "Михайлова", DateOfBirth = DateTime.Parse("25-12-1992"), ExamScore = 4.8F },
                    new Student { Id = 435, GroupId = 26, FirstName = "Мия", LastName = "Винокурова", DateOfBirth = DateTime.Parse("23-03-1997"), ExamScore = 4.7F },
                    new Student { Id = 436, GroupId = 26, FirstName = "Вероника", LastName = "Беспалова", DateOfBirth = DateTime.Parse("12-03-1987"), ExamScore = 4.1F },
                    new Student { Id = 437, GroupId = 26, FirstName = "Дмитрий", LastName = "Яшин", DateOfBirth = DateTime.Parse("08-04-1999"), ExamScore = 4.9F },
                    new Student { Id = 438, GroupId = 26, FirstName = "Василиса", LastName = "Сергеева", DateOfBirth = DateTime.Parse("27-11-1991"), ExamScore = 4F },
                    new Student { Id = 439, GroupId = 26, FirstName = "Александра", LastName = "Сидорова", DateOfBirth = DateTime.Parse("07-01-1999"), ExamScore = 3.1F },
                    new Student { Id = 440, GroupId = 26, FirstName = "Олег", LastName = "Лобанов", DateOfBirth = DateTime.Parse("10-11-1986"), ExamScore = 3.7F },
                    new Student { Id = 441, GroupId = 26, FirstName = "Фёдор", LastName = "Ермолов", DateOfBirth = DateTime.Parse("01-01-1999"), ExamScore = 4.7F },
                    new Student { Id = 442, GroupId = 26, FirstName = "Михаил", LastName = "Чернов", DateOfBirth = DateTime.Parse("21-11-2000"), ExamScore = 3.5F },
                    new Student { Id = 443, GroupId = 27, FirstName = "Александр", LastName = "Михайлов", DateOfBirth = DateTime.Parse("25-05-1990"), ExamScore = 4.6F },
                    new Student { Id = 444, GroupId = 27, FirstName = "Тимофей", LastName = "Смирнов", DateOfBirth = DateTime.Parse("06-11-1998"), ExamScore = 4.6F },
                    new Student { Id = 445, GroupId = 27, FirstName = "Екатерина", LastName = "Егорова", DateOfBirth = DateTime.Parse("09-05-1986"), ExamScore = 4.5F },
                    new Student { Id = 446, GroupId = 27, FirstName = "Василиса", LastName = "Соколова", DateOfBirth = DateTime.Parse("07-05-1989"), ExamScore = 3.3F },
                    new Student { Id = 447, GroupId = 27, FirstName = "Виктория", LastName = "Рудакова", DateOfBirth = DateTime.Parse("21-02-1989"), ExamScore = 3F },
                    new Student { Id = 448, GroupId = 27, FirstName = "Георгий", LastName = "Афанасьев", DateOfBirth = DateTime.Parse("22-06-1991"), ExamScore = 3.4F },
                    new Student { Id = 449, GroupId = 27, FirstName = "Кира", LastName = "Лаврова", DateOfBirth = DateTime.Parse("20-08-1985"), ExamScore = 3.4F },
                    new Student { Id = 450, GroupId = 27, FirstName = "Руслан", LastName = "Ананьев", DateOfBirth = DateTime.Parse("31-01-1991"), ExamScore = 3.3F },
                    new Student { Id = 451, GroupId = 27, FirstName = "Алиса", LastName = "Никулина", DateOfBirth = DateTime.Parse("23-06-1989"), ExamScore = 4.5F },
                    new Student { Id = 452, GroupId = 27, FirstName = "Валерия", LastName = "Шишкина", DateOfBirth = DateTime.Parse("31-03-1992"), ExamScore = 3.8F },
                    new Student { Id = 453, GroupId = 27, FirstName = "Виктория", LastName = "Короткова", DateOfBirth = DateTime.Parse("07-03-1998"), ExamScore = 4.3F },
                    new Student { Id = 454, GroupId = 27, FirstName = "Дарья", LastName = "Свиридова", DateOfBirth = DateTime.Parse("14-03-1997"), ExamScore = 4F },
                    new Student { Id = 455, GroupId = 27, FirstName = "Нина", LastName = "Евдокимова", DateOfBirth = DateTime.Parse("26-04-1999"), ExamScore = 3.5F },
                    new Student { Id = 456, GroupId = 27, FirstName = "Максим", LastName = "Григорьев", DateOfBirth = DateTime.Parse("18-07-1994"), ExamScore = 4.2F },
                    new Student { Id = 457, GroupId = 27, FirstName = "Алиса", LastName = "Смирнова", DateOfBirth = DateTime.Parse("20-05-1998"), ExamScore = 4.1F },
                    new Student { Id = 458, GroupId = 27, FirstName = "Матвей", LastName = "Комаров", DateOfBirth = DateTime.Parse("02-09-1986"), ExamScore = 3.7F },
                    new Student { Id = 459, GroupId = 27, FirstName = "Марк", LastName = "Сергеев", DateOfBirth = DateTime.Parse("27-07-1994"), ExamScore = 3.3F },
                    new Student { Id = 460, GroupId = 27, FirstName = "Варвара", LastName = "Русанова", DateOfBirth = DateTime.Parse("26-08-1985"), ExamScore = 5F },
                    new Student { Id = 461, GroupId = 27, FirstName = "Георгий", LastName = "Титов", DateOfBirth = DateTime.Parse("19-05-1998"), ExamScore = 4.1F },
                    new Student { Id = 462, GroupId = 27, FirstName = "Артур", LastName = "Щеглов", DateOfBirth = DateTime.Parse("23-11-1992"), ExamScore = 3.9F },
                    new Student { Id = 463, GroupId = 27, FirstName = "Милана", LastName = "Высоцкая", DateOfBirth = DateTime.Parse("18-09-1985"), ExamScore = 3.5F },
                    new Student { Id = 464, GroupId = 27, FirstName = "Таисия", LastName = "Полякова", DateOfBirth = DateTime.Parse("30-01-1992"), ExamScore = 4.7F },
                    new Student { Id = 465, GroupId = 27, FirstName = "Егор", LastName = "Беляев", DateOfBirth = DateTime.Parse("18-09-1999"), ExamScore = 3.7F },
                    new Student { Id = 466, GroupId = 27, FirstName = "Алиса", LastName = "Константинова", DateOfBirth = DateTime.Parse("08-12-1997"), ExamScore = 4.9F },
                    new Student { Id = 467, GroupId = 27, FirstName = "Ярослав", LastName = "Миронов", DateOfBirth = DateTime.Parse("28-04-1997"), ExamScore = 3.8F },
                    new Student { Id = 468, GroupId = 27, FirstName = "София", LastName = "Головина", DateOfBirth = DateTime.Parse("13-10-1989"), ExamScore = 3.2F },
                    new Student { Id = 469, GroupId = 27, FirstName = "Алла", LastName = "Захарова", DateOfBirth = DateTime.Parse("20-04-1994"), ExamScore = 3.3F },
                    new Student { Id = 470, GroupId = 28, FirstName = "Амина", LastName = "Семенова", DateOfBirth = DateTime.Parse("17-02-1997"), ExamScore = 5F },
                    new Student { Id = 471, GroupId = 28, FirstName = "Андрей", LastName = "Матвеев", DateOfBirth = DateTime.Parse("01-04-1998"), ExamScore = 4.1F },
                    new Student { Id = 472, GroupId = 28, FirstName = "Диана", LastName = "Завьялова", DateOfBirth = DateTime.Parse("20-10-1995"), ExamScore = 3.5F },
                    new Student { Id = 473, GroupId = 28, FirstName = "Дарья", LastName = "Тимофеева", DateOfBirth = DateTime.Parse("31-10-1990"), ExamScore = 3.4F },
                    new Student { Id = 474, GroupId = 28, FirstName = "Елизавета", LastName = "Кузнецова", DateOfBirth = DateTime.Parse("05-02-2001"), ExamScore = 3.8F },
                    new Student { Id = 475, GroupId = 28, FirstName = "Анастасия", LastName = "Беляева", DateOfBirth = DateTime.Parse("28-05-1999"), ExamScore = 4.2F },
                    new Student { Id = 476, GroupId = 28, FirstName = "Софья", LastName = "Артамонова", DateOfBirth = DateTime.Parse("26-05-1991"), ExamScore = 4.9F },
                    new Student { Id = 477, GroupId = 28, FirstName = "Михаил", LastName = "Кузнецов", DateOfBirth = DateTime.Parse("20-05-1999"), ExamScore = 4.6F },
                    new Student { Id = 478, GroupId = 28, FirstName = "Дмитрий", LastName = "Князев", DateOfBirth = DateTime.Parse("20-04-1996"), ExamScore = 4.1F },
                    new Student { Id = 479, GroupId = 28, FirstName = "Сергей", LastName = "Гуляев", DateOfBirth = DateTime.Parse("01-04-1996"), ExamScore = 4.1F },
                    new Student { Id = 480, GroupId = 28, FirstName = "Михаил", LastName = "Попов", DateOfBirth = DateTime.Parse("18-12-1990"), ExamScore = 4.8F },
                    new Student { Id = 481, GroupId = 28, FirstName = "Мария", LastName = "Виноградова", DateOfBirth = DateTime.Parse("16-10-1998"), ExamScore = 4.3F },
                    new Student { Id = 482, GroupId = 28, FirstName = "Егор", LastName = "Петров", DateOfBirth = DateTime.Parse("03-03-1987"), ExamScore = 3.2F },
                    new Student { Id = 483, GroupId = 28, FirstName = "Милана", LastName = "Михайлова", DateOfBirth = DateTime.Parse("10-10-1994"), ExamScore = 4.3F },
                    new Student { Id = 484, GroupId = 28, FirstName = "Кирилл", LastName = "Артамонов", DateOfBirth = DateTime.Parse("14-07-1994"), ExamScore = 4.8F },
                    new Student { Id = 485, GroupId = 28, FirstName = "Леонид", LastName = "Орлов", DateOfBirth = DateTime.Parse("02-10-1998"), ExamScore = 3.8F },
                    new Student { Id = 486, GroupId = 28, FirstName = "Василий", LastName = "Смирнов", DateOfBirth = DateTime.Parse("05-01-1991"), ExamScore = 4.4F },
                    new Student { Id = 487, GroupId = 28, FirstName = "Дарья", LastName = "Калинина", DateOfBirth = DateTime.Parse("14-11-2001"), ExamScore = 3.6F },
                    new Student { Id = 488, GroupId = 28, FirstName = "Кира", LastName = "Гусева", DateOfBirth = DateTime.Parse("25-05-1993"), ExamScore = 3.4F },
                    new Student { Id = 489, GroupId = 28, FirstName = "Анна", LastName = "Акимова", DateOfBirth = DateTime.Parse("07-02-1994"), ExamScore = 3.5F },
                    new Student { Id = 490, GroupId = 28, FirstName = "Кристина", LastName = "Евдокимова", DateOfBirth = DateTime.Parse("23-01-1996"), ExamScore = 5F },
                    new Student { Id = 491, GroupId = 28, FirstName = "Матвей", LastName = "Носов", DateOfBirth = DateTime.Parse("27-08-1995"), ExamScore = 3.7F },
                    new Student { Id = 492, GroupId = 28, FirstName = "Агния", LastName = "Смирнова", DateOfBirth = DateTime.Parse("31-10-1988"), ExamScore = 4.1F },
                    new Student { Id = 493, GroupId = 28, FirstName = "Марина", LastName = "Боброва", DateOfBirth = DateTime.Parse("31-07-1989"), ExamScore = 4.3F },
                    new Student { Id = 494, GroupId = 28, FirstName = "Давид", LastName = "Егоров", DateOfBirth = DateTime.Parse("22-08-1989"), ExamScore = 4.4F },
                    new Student { Id = 495, GroupId = 28, FirstName = "Егор", LastName = "Молчанов", DateOfBirth = DateTime.Parse("02-12-1987"), ExamScore = 4.9F },
                    new Student { Id = 496, GroupId = 28, FirstName = "Николай", LastName = "Терехов", DateOfBirth = DateTime.Parse("24-08-1988"), ExamScore = 3.9F }
                );
        }
    }
}
