using System;
using System.Linq;
using MVC.Common;

namespace MVC.DataAccess
{
    public class SampleData
    {
        public static void Initialize(UniversityContext context)
        {
            if (!context.Courses.Any())
            {
                context.Courses.AddRange(
                    new Course
                    {
                        Name = "Математика",
                        Description = "Царица наук"
                    },
                    new Course
                    {
                        Name = "Физика",
                        Description = "Основа всего"
                    },
                    new Course
                    {
                        Name = "Физкультура",
                        Description = "В здоровом теле - здоровый дух"
                    },
                    new Course
                    {
                        Name = "История",
                        Description = "У того, кто не знает прошлого - нет будущего"
                    }
                );
                context.SaveChanges();
            }

            if (!context.Groups.Any())
            {
                context.Groups.AddRange(
                    new Group { CourseId = 1, Name = "КБ-101"},
                    new Group { CourseId = 2, Name = "ЛП-102"},
                    new Group { CourseId = 3, Name = "РР-103"},
                    new Group { CourseId = 2, Name = "РС-104"},
                    new Group { CourseId = 1, Name = "РА-105"},
                    new Group { CourseId = 3, Name = "РА-202"},
                    new Group { CourseId = 4, Name = "АР-203"},
                    new Group { CourseId = 4, Name = "РА-204"},
                    new Group { CourseId = 1, Name = "НК-205"},
                    new Group { CourseId = 3, Name = "БК-301"},
                    new Group { CourseId = 4, Name = "РА-353"},
                    new Group { CourseId = 1, Name = "РА-333"},
                    new Group { CourseId = 3, Name = "ВП-322"},
                    new Group { CourseId = 3, Name = "УЦ-311"},
                    new Group { CourseId = 1, Name = "МВ-354"},
                    new Group { CourseId = 3, Name = "РА-344"}
                );
                context.SaveChanges();
            }

            if (!context.Students.Any())
            {
                context.Students.AddRange(
                    new Student { GroupId = 1, FirstName = "Ксения", LastName = "Пономарева", DateOfBirth = DateTime.Parse("24-06-1994"), ExamScore = 3.3F },
                    new Student { GroupId = 1, FirstName = "Милана", LastName = "Михайлова", DateOfBirth = DateTime.Parse("18-10-1993"), ExamScore = 4.6F },
                    new Student { GroupId = 1, FirstName = "Тимофей", LastName = "Яковлев", DateOfBirth = DateTime.Parse("16-03-2001"), ExamScore = 4.3F },
                    new Student { GroupId = 1, FirstName = "Эвелина", LastName = "Михайлова", DateOfBirth = DateTime.Parse("14-02-1989"), ExamScore = 4.5F },
                    new Student { GroupId = 1, FirstName = "Елизавета", LastName = "Волкова", DateOfBirth = DateTime.Parse("03-06-2001"), ExamScore = 4.6F },
                    new Student { GroupId = 1, FirstName = "Ольга", LastName = "Кузнецова", DateOfBirth = DateTime.Parse("01-03-1991"), ExamScore = 4.8F },
                    new Student { GroupId = 1, FirstName = "Илья", LastName = "Харитонов", DateOfBirth = DateTime.Parse("28-03-2000"), ExamScore = 3.8F },
                    new Student { GroupId = 1, FirstName = "Мария", LastName = "Соловьева", DateOfBirth = DateTime.Parse("09-04-1989"), ExamScore = 4.3F },
                    new Student { GroupId = 1, FirstName = "Майя", LastName = "Гришина", DateOfBirth = DateTime.Parse("30-09-1990"), ExamScore = 4.1F },
                    new Student { GroupId = 1, FirstName = "Дарья", LastName = "Корнеева", DateOfBirth = DateTime.Parse("03-01-2001"), ExamScore = 3.4F },
                    new Student { GroupId = 1, FirstName = "Эвелина", LastName = "Горшкова", DateOfBirth = DateTime.Parse("13-04-1985"), ExamScore = 3.1F },
                    new Student { GroupId = 1, FirstName = "София", LastName = "Юдина", DateOfBirth = DateTime.Parse("27-04-1991"), ExamScore = 3F },
                    new Student { GroupId = 1, FirstName = "Ульяна", LastName = "Гаврилова", DateOfBirth = DateTime.Parse("05-07-2000"), ExamScore = 3.4F },
                    new Student { GroupId = 1, FirstName = "Кира", LastName = "Ковалева", DateOfBirth = DateTime.Parse("26-12-2000"), ExamScore = 4.8F },
                    new Student { GroupId = 1, FirstName = "Александра", LastName = "Петрова", DateOfBirth = DateTime.Parse("08-04-2001"), ExamScore = 4.1F },
                    new Student { GroupId = 1, FirstName = "Никита", LastName = "Румянцев", DateOfBirth = DateTime.Parse("20-08-1989"), ExamScore = 3.7F },
                    new Student { GroupId = 1, FirstName = "Мия", LastName = "Кузьмина", DateOfBirth = DateTime.Parse("26-07-1996"), ExamScore = 4.3F },
                    new Student { GroupId = 2, FirstName = "Милана", LastName = "Куликова", DateOfBirth = DateTime.Parse("10-04-1989"), ExamScore = 4.2F },
                    new Student { GroupId = 2, FirstName = "Анастасия", LastName = "Сергеева", DateOfBirth = DateTime.Parse("05-09-1999"), ExamScore = 4.5F },
                    new Student { GroupId = 2, FirstName = "Денис", LastName = "Чернов", DateOfBirth = DateTime.Parse("04-02-1988"), ExamScore = 3F },
                    new Student { GroupId = 2, FirstName = "Савелий", LastName = "Воронов", DateOfBirth = DateTime.Parse("07-09-1991"), ExamScore = 3.8F },
                    new Student { GroupId = 2, FirstName = "Егор", LastName = "Степанов", DateOfBirth = DateTime.Parse("04-07-1999"), ExamScore = 3.8F },
                    new Student { GroupId = 2, FirstName = "Кирилл", LastName = "Федоров", DateOfBirth = DateTime.Parse("15-04-1995"), ExamScore = 4.2F },
                    new Student { GroupId = 2, FirstName = "Аиша", LastName = "Дубровина", DateOfBirth = DateTime.Parse("12-04-1985"), ExamScore = 3F },
                    new Student { GroupId = 2, FirstName = "Матвей", LastName = "Озеров", DateOfBirth = DateTime.Parse("16-10-1985"), ExamScore = 4F },
                    new Student { GroupId = 2, FirstName = "Нина", LastName = "Соловьева", DateOfBirth = DateTime.Parse("26-10-1998"), ExamScore = 4.4F },
                    new Student { GroupId = 2, FirstName = "Константин", LastName = "Павлов", DateOfBirth = DateTime.Parse("22-11-1997"), ExamScore = 4.1F },
                    new Student { GroupId = 3, FirstName = "Макар", LastName = "Захаров", DateOfBirth = DateTime.Parse("14-08-1999"), ExamScore = 3.9F },
                    new Student { GroupId = 3, FirstName = "Николай", LastName = "Афанасьев", DateOfBirth = DateTime.Parse("18-03-1987"), ExamScore = 3.5F },
                    new Student { GroupId = 3, FirstName = "Иван", LastName = "Иванов", DateOfBirth = DateTime.Parse("31-01-1993"), ExamScore = 3F },
                    new Student { GroupId = 3, FirstName = "Михаил", LastName = "Дмитриев", DateOfBirth = DateTime.Parse("06-03-1994"), ExamScore = 4.7F },
                    new Student { GroupId = 3, FirstName = "Артём", LastName = "Макаров", DateOfBirth = DateTime.Parse("20-01-1994"), ExamScore = 3.9F },
                    new Student { GroupId = 4, FirstName = "Ева", LastName = "Рябинина", DateOfBirth = DateTime.Parse("20-10-1990"), ExamScore = 3.6F },
                    new Student { GroupId = 4, FirstName = "Роман", LastName = "Кузьмин", DateOfBirth = DateTime.Parse("11-07-1992"), ExamScore = 3.9F },
                    new Student { GroupId = 4, FirstName = "Софья", LastName = "Винокурова", DateOfBirth = DateTime.Parse("29-11-1986"), ExamScore = 3F },
                    new Student { GroupId = 4, FirstName = "Мария", LastName = "Пирогова", DateOfBirth = DateTime.Parse("04-12-1991"), ExamScore = 3.5F },
                    new Student { GroupId = 4, FirstName = "Максим", LastName = "Денисов", DateOfBirth = DateTime.Parse("21-04-1998"), ExamScore = 3.1F },
                    new Student { GroupId = 4, FirstName = "Артём", LastName = "Колпаков", DateOfBirth = DateTime.Parse("17-09-1991"), ExamScore = 3.5F },
                    new Student { GroupId = 4, FirstName = "Лев", LastName = "Попов", DateOfBirth = DateTime.Parse("02-05-2000"), ExamScore = 3.7F },
                    new Student { GroupId = 4, FirstName = "Кира", LastName = "Савельева", DateOfBirth = DateTime.Parse("01-02-1991"), ExamScore = 4F },
                    new Student { GroupId = 4, FirstName = "Даниил", LastName = "Лаптев", DateOfBirth = DateTime.Parse("31-10-1994"), ExamScore = 4.3F },
                    new Student { GroupId = 4, FirstName = "Амира", LastName = "Филатова", DateOfBirth = DateTime.Parse("24-08-1988"), ExamScore = 3.3F },
                    new Student { GroupId = 4, FirstName = "Любовь", LastName = "Покровская", DateOfBirth = DateTime.Parse("19-09-1989"), ExamScore = 3F },
                    new Student { GroupId = 4, FirstName = "Евгения", LastName = "Алексеева", DateOfBirth = DateTime.Parse("11-05-1995"), ExamScore = 3.9F },
                    new Student { GroupId = 4, FirstName = "Тимофей", LastName = "Тарасов", DateOfBirth = DateTime.Parse("25-11-1992"), ExamScore = 4.9F },
                    new Student { GroupId = 4, FirstName = "Платон", LastName = "Терехов", DateOfBirth = DateTime.Parse("30-06-1990"), ExamScore = 4.5F },
                    new Student { GroupId = 4, FirstName = "Анна", LastName = "Андрианова", DateOfBirth = DateTime.Parse("22-05-1989"), ExamScore = 4.2F },
                    new Student { GroupId = 4, FirstName = "Арина", LastName = "Зуева", DateOfBirth = DateTime.Parse("15-09-1994"), ExamScore = 3.2F },
                    new Student { GroupId = 4, FirstName = "Арина", LastName = "Савельева", DateOfBirth = DateTime.Parse("09-10-1994"), ExamScore = 4.4F },
                    new Student { GroupId = 4, FirstName = "Тимофей", LastName = "Федотов", DateOfBirth = DateTime.Parse("23-01-1985"), ExamScore = 3.5F },
                    new Student { GroupId = 5, FirstName = "Владислав", LastName = "Капустин", DateOfBirth = DateTime.Parse("08-01-1990"), ExamScore = 4.8F },
                    new Student { GroupId = 5, FirstName = "Матвей", LastName = "Волков", DateOfBirth = DateTime.Parse("21-10-1986"), ExamScore = 4.5F },
                    new Student { GroupId = 5, FirstName = "Варвара", LastName = "Краснова", DateOfBirth = DateTime.Parse("07-11-2001"), ExamScore = 4F },
                    new Student { GroupId = 5, FirstName = "Матвей", LastName = "Воробьев", DateOfBirth = DateTime.Parse("06-03-1993"), ExamScore = 4F },
                    new Student { GroupId = 5, FirstName = "Мария", LastName = "Степанова", DateOfBirth = DateTime.Parse("30-08-1998"), ExamScore = 3.4F },
                    new Student { GroupId = 5, FirstName = "Нина", LastName = "Абрамова", DateOfBirth = DateTime.Parse("06-05-1986"), ExamScore = 3.4F },
                    new Student { GroupId = 5, FirstName = "Герман", LastName = "Кукушкин", DateOfBirth = DateTime.Parse("20-05-1991"), ExamScore = 3.7F },
                    new Student { GroupId = 5, FirstName = "Виктория", LastName = "Блинова", DateOfBirth = DateTime.Parse("21-04-2001"), ExamScore = 4.2F },
                    new Student { GroupId = 5, FirstName = "Алёна", LastName = "Морозова", DateOfBirth = DateTime.Parse("30-01-2001"), ExamScore = 3.1F },
                    new Student { GroupId = 5, FirstName = "Виктория", LastName = "Тарасова", DateOfBirth = DateTime.Parse("18-03-1998"), ExamScore = 3.5F },
                    new Student { GroupId = 5, FirstName = "Алексей", LastName = "Беляев", DateOfBirth = DateTime.Parse("07-08-1994"), ExamScore = 4.2F },
                    new Student { GroupId = 5, FirstName = "Елизавета", LastName = "Малышева", DateOfBirth = DateTime.Parse("10-11-1989"), ExamScore = 3.4F },
                    new Student { GroupId = 5, FirstName = "Максим", LastName = "Егоров", DateOfBirth = DateTime.Parse("11-02-1996"), ExamScore = 3.2F },
                    new Student { GroupId = 5, FirstName = "Максим", LastName = "Дубов", DateOfBirth = DateTime.Parse("04-12-1993"), ExamScore = 4.1F },
                    new Student { GroupId = 6, FirstName = "Елизавета", LastName = "Смирнова", DateOfBirth = DateTime.Parse("17-06-1992"), ExamScore = 3.8F },
                    new Student { GroupId = 6, FirstName = "Алиса", LastName = "Корнилова", DateOfBirth = DateTime.Parse("23-09-1993"), ExamScore = 3.9F },
                    new Student { GroupId = 6, FirstName = "Ян", LastName = "Герасимов", DateOfBirth = DateTime.Parse("09-06-1988"), ExamScore = 3.7F },
                    new Student { GroupId = 6, FirstName = "Олег", LastName = "Смирнов", DateOfBirth = DateTime.Parse("26-12-1985"), ExamScore = 3.4F },
                    new Student { GroupId = 6, FirstName = "Елисей", LastName = "Аксенов", DateOfBirth = DateTime.Parse("05-07-1998"), ExamScore = 4.2F },
                    new Student { GroupId = 6, FirstName = "Сергей", LastName = "Лукьянов", DateOfBirth = DateTime.Parse("06-09-1997"), ExamScore = 3.8F },
                    new Student { GroupId = 6, FirstName = "Полина", LastName = "Ковалева", DateOfBirth = DateTime.Parse("06-01-1997"), ExamScore = 4F },
                    new Student { GroupId = 6, FirstName = "Мирон", LastName = "Казаков", DateOfBirth = DateTime.Parse("29-07-1999"), ExamScore = 3.2F },
                    new Student { GroupId = 6, FirstName = "Алиса", LastName = "Логинова", DateOfBirth = DateTime.Parse("17-04-1991"), ExamScore = 5F },
                    new Student { GroupId = 6, FirstName = "Ксения", LastName = "Попова", DateOfBirth = DateTime.Parse("13-11-2000"), ExamScore = 4.4F },
                    new Student { GroupId = 6, FirstName = "Ангелина", LastName = "Кондрашова", DateOfBirth = DateTime.Parse("10-09-1999"), ExamScore = 3.8F },
                    new Student { GroupId = 6, FirstName = "Ульяна", LastName = "Давыдова", DateOfBirth = DateTime.Parse("30-11-1992"), ExamScore = 3.4F },
                    new Student { GroupId = 6, FirstName = "Анастасия", LastName = "Капустина", DateOfBirth = DateTime.Parse("30-05-1988"), ExamScore = 3.1F },
                    new Student { GroupId = 7, FirstName = "Макар", LastName = "Корнеев", DateOfBirth = DateTime.Parse("09-10-1985"), ExamScore = 3.2F },
                    new Student { GroupId = 7, FirstName = "Давид", LastName = "Голованов", DateOfBirth = DateTime.Parse("14-09-1987"), ExamScore = 4.6F },
                    new Student { GroupId = 7, FirstName = "Диана", LastName = "Колесникова", DateOfBirth = DateTime.Parse("11-02-1995"), ExamScore = 4.5F },
                    new Student { GroupId = 7, FirstName = "Константин", LastName = "Волков", DateOfBirth = DateTime.Parse("14-08-1996"), ExamScore = 3.3F },
                    new Student { GroupId = 7, FirstName = "Арина", LastName = "Чернышева", DateOfBirth = DateTime.Parse("22-04-1993"), ExamScore = 4.6F },
                    new Student { GroupId = 7, FirstName = "Евдокия", LastName = "Прохорова", DateOfBirth = DateTime.Parse("07-06-1992"), ExamScore = 3.1F },
                    new Student { GroupId = 7, FirstName = "Никита", LastName = "Тарасов", DateOfBirth = DateTime.Parse("25-04-2000"), ExamScore = 3.8F },
                    new Student { GroupId = 7, FirstName = "Лев", LastName = "Калинин", DateOfBirth = DateTime.Parse("19-02-1989"), ExamScore = 4.8F },
                    new Student { GroupId = 7, FirstName = "Георгий", LastName = "Большаков", DateOfBirth = DateTime.Parse("25-05-1985"), ExamScore = 3.2F },
                    new Student { GroupId = 7, FirstName = "Виктория", LastName = "Яшина", DateOfBirth = DateTime.Parse("17-11-1988"), ExamScore = 3.5F },
                    new Student { GroupId = 7, FirstName = "Лев", LastName = "Иванов", DateOfBirth = DateTime.Parse("19-08-1995"), ExamScore = 5F },
                    new Student { GroupId = 7, FirstName = "Елизавета", LastName = "Романова", DateOfBirth = DateTime.Parse("04-10-1986"), ExamScore = 3.3F },
                    new Student { GroupId = 7, FirstName = "Виктория", LastName = "Медведева", DateOfBirth = DateTime.Parse("09-01-1993"), ExamScore = 3F },
                    new Student { GroupId = 7, FirstName = "Анастасия", LastName = "Иванова", DateOfBirth = DateTime.Parse("04-11-1990"), ExamScore = 4.4F },
                    new Student { GroupId = 7, FirstName = "Елизавета", LastName = "Константинова", DateOfBirth = DateTime.Parse("28-08-1989"), ExamScore = 4.7F },
                    new Student { GroupId = 8, FirstName = "Мирослава", LastName = "Высоцкая", DateOfBirth = DateTime.Parse("02-11-1996"), ExamScore = 5F },
                    new Student { GroupId = 8, FirstName = "Никита", LastName = "Рубцов", DateOfBirth = DateTime.Parse("05-05-2000"), ExamScore = 3.3F },
                    new Student { GroupId = 8, FirstName = "Степан", LastName = "Ильин", DateOfBirth = DateTime.Parse("26-12-1999"), ExamScore = 4.6F },
                    new Student { GroupId = 8, FirstName = "Арина", LastName = "Егорова", DateOfBirth = DateTime.Parse("12-08-1987"), ExamScore = 5F },
                    new Student { GroupId = 8, FirstName = "Таисия", LastName = "Дубровина", DateOfBirth = DateTime.Parse("07-05-1994"), ExamScore = 4.6F },
                    new Student { GroupId = 8, FirstName = "Арина", LastName = "Воробьева", DateOfBirth = DateTime.Parse("04-08-1994"), ExamScore = 3.6F },
                    new Student { GroupId = 8, FirstName = "Вероника", LastName = "Пономарева", DateOfBirth = DateTime.Parse("29-04-1991"), ExamScore = 4.3F },
                    new Student { GroupId = 8, FirstName = "Михаил", LastName = "Львов", DateOfBirth = DateTime.Parse("08-05-1989"), ExamScore = 4F },
                    new Student { GroupId = 8, FirstName = "Дмитрий", LastName = "Семенов", DateOfBirth = DateTime.Parse("21-06-1993"), ExamScore = 4.4F },
                    new Student { GroupId = 8, FirstName = "Ульяна", LastName = "Краснова", DateOfBirth = DateTime.Parse("04-03-2000"), ExamScore = 4.5F },
                    new Student { GroupId = 8, FirstName = "Малика", LastName = "Козлова", DateOfBirth = DateTime.Parse("11-06-2000"), ExamScore = 4F },
                    new Student { GroupId = 8, FirstName = "Полина", LastName = "Воробьева", DateOfBirth = DateTime.Parse("16-05-1994"), ExamScore = 4.9F },
                    new Student { GroupId = 8, FirstName = "Владислав", LastName = "Нефедов", DateOfBirth = DateTime.Parse("29-10-1988"), ExamScore = 4.9F },
                    new Student { GroupId = 8, FirstName = "Арсений", LastName = "Рогов", DateOfBirth = DateTime.Parse("22-12-1991"), ExamScore = 4.2F },
                    new Student { GroupId = 9, FirstName = "София", LastName = "Ракова", DateOfBirth = DateTime.Parse("03-07-2001"), ExamScore = 4.7F },
                    new Student { GroupId = 9, FirstName = "Вероника", LastName = "Денисова", DateOfBirth = DateTime.Parse("04-05-1994"), ExamScore = 4.2F },
                    new Student { GroupId = 9, FirstName = "Павел", LastName = "Медведев", DateOfBirth = DateTime.Parse("20-03-1989"), ExamScore = 4.1F },
                    new Student { GroupId = 9, FirstName = "Николай", LastName = "Исаев", DateOfBirth = DateTime.Parse("10-02-1987"), ExamScore = 3.5F },
                    new Student { GroupId = 9, FirstName = "Кирилл", LastName = "Жилин", DateOfBirth = DateTime.Parse("16-04-1989"), ExamScore = 5F },
                    new Student { GroupId = 9, FirstName = "Вероника", LastName = "Кузнецова", DateOfBirth = DateTime.Parse("06-09-1997"), ExamScore = 4.7F },
                    new Student { GroupId = 9, FirstName = "Серафима", LastName = "Волкова", DateOfBirth = DateTime.Parse("03-06-1996"), ExamScore = 5F },
                    new Student { GroupId = 9, FirstName = "Екатерина", LastName = "Вавилова", DateOfBirth = DateTime.Parse("24-04-1992"), ExamScore = 4.9F },
                    new Student { GroupId = 9, FirstName = "Дарья", LastName = "Фокина", DateOfBirth = DateTime.Parse("13-06-1987"), ExamScore = 4.3F },
                    new Student { GroupId = 9, FirstName = "Марк", LastName = "Кудряшов", DateOfBirth = DateTime.Parse("07-09-1993"), ExamScore = 4.4F },
                    new Student { GroupId = 10, FirstName = "Анна", LastName = "Воронкова", DateOfBirth = DateTime.Parse("07-10-1993"), ExamScore = 3.7F },
                    new Student { GroupId = 10, FirstName = "Тимофей", LastName = "Коновалов", DateOfBirth = DateTime.Parse("24-11-2000"), ExamScore = 4.1F },
                    new Student { GroupId = 10, FirstName = "Софья", LastName = "Алешина", DateOfBirth = DateTime.Parse("26-06-1996"), ExamScore = 3.6F },
                    new Student { GroupId = 10, FirstName = "Артём", LastName = "Исаев", DateOfBirth = DateTime.Parse("19-03-1998"), ExamScore = 4F },
                    new Student { GroupId = 10, FirstName = "Оливия", LastName = "Крючкова", DateOfBirth = DateTime.Parse("23-02-1991"), ExamScore = 4F },
                    new Student { GroupId = 10, FirstName = "Мария", LastName = "Сорокина", DateOfBirth = DateTime.Parse("13-03-1990"), ExamScore = 4.4F },
                    new Student { GroupId = 10, FirstName = "Елизавета", LastName = "Фролова", DateOfBirth = DateTime.Parse("27-04-1990"), ExamScore = 5F },
                    new Student { GroupId = 10, FirstName = "Андрей", LastName = "Бочаров", DateOfBirth = DateTime.Parse("08-07-1994"), ExamScore = 3F },
                    new Student { GroupId = 11, FirstName = "Мелисса", LastName = "Щеглова", DateOfBirth = DateTime.Parse("16-03-1993"), ExamScore = 4.3F },
                    new Student { GroupId = 11, FirstName = "Арсений", LastName = "Попов", DateOfBirth = DateTime.Parse("21-12-1986"), ExamScore = 4.5F },
                    new Student { GroupId = 11, FirstName = "Давид", LastName = "Шубин", DateOfBirth = DateTime.Parse("23-07-1986"), ExamScore = 4.7F },
                    new Student { GroupId = 11, FirstName = "Мирослава", LastName = "Яковлева", DateOfBirth = DateTime.Parse("30-05-1987"), ExamScore = 3F },
                    new Student { GroupId = 11, FirstName = "Алексей", LastName = "Богданов", DateOfBirth = DateTime.Parse("25-07-1997"), ExamScore = 3.8F },
                    new Student { GroupId = 11, FirstName = "Михаил", LastName = "Смирнов", DateOfBirth = DateTime.Parse("12-04-1994"), ExamScore = 4.3F },
                    new Student { GroupId = 11, FirstName = "Тимур", LastName = "Новиков", DateOfBirth = DateTime.Parse("24-12-1988"), ExamScore = 4.4F },
                    new Student { GroupId = 11, FirstName = "Варвара", LastName = "Бирюкова", DateOfBirth = DateTime.Parse("20-12-1993"), ExamScore = 4.3F },
                    new Student { GroupId = 11, FirstName = "Давид", LastName = "Гусев", DateOfBirth = DateTime.Parse("14-02-1999"), ExamScore = 3.4F },
                    new Student { GroupId = 11, FirstName = "Иван", LastName = "Богданов", DateOfBirth = DateTime.Parse("10-11-1985"), ExamScore = 4.6F },
                    new Student { GroupId = 11, FirstName = "Александр", LastName = "Агапов", DateOfBirth = DateTime.Parse("21-11-1991"), ExamScore = 3.3F },
                    new Student { GroupId = 11, FirstName = "Михаил", LastName = "Самсонов", DateOfBirth = DateTime.Parse("09-07-1995"), ExamScore = 5F },
                    new Student { GroupId = 12, FirstName = "Кира", LastName = "Васильева", DateOfBirth = DateTime.Parse("23-06-1988"), ExamScore = 3.9F },
                    new Student { GroupId = 12, FirstName = "Кирилл", LastName = "Фадеев", DateOfBirth = DateTime.Parse("22-10-1990"), ExamScore = 3.7F },
                    new Student { GroupId = 12, FirstName = "Даниил", LastName = "Сычев", DateOfBirth = DateTime.Parse("19-02-1989"), ExamScore = 3.6F },
                    new Student { GroupId = 12, FirstName = "Роман", LastName = "Степанов", DateOfBirth = DateTime.Parse("25-07-1991"), ExamScore = 4F },
                    new Student { GroupId = 12, FirstName = "Наталья", LastName = "Фомина", DateOfBirth = DateTime.Parse("26-11-1986"), ExamScore = 3.7F },
                    new Student { GroupId = 12, FirstName = "Тимофей", LastName = "Кулаков", DateOfBirth = DateTime.Parse("04-03-2000"), ExamScore = 4F },
                    new Student { GroupId = 12, FirstName = "Яна", LastName = "Михайлова", DateOfBirth = DateTime.Parse("07-07-1990"), ExamScore = 3.3F },
                    new Student { GroupId = 12, FirstName = "Вячеслав", LastName = "Михайлов", DateOfBirth = DateTime.Parse("29-07-2001"), ExamScore = 3.8F },
                    new Student { GroupId = 12, FirstName = "Ариана", LastName = "Демидова", DateOfBirth = DateTime.Parse("16-12-1986"), ExamScore = 3.4F },
                    new Student { GroupId = 13, FirstName = "Илья", LastName = "Леонтьев", DateOfBirth = DateTime.Parse("28-01-1990"), ExamScore = 3.5F },
                    new Student { GroupId = 13, FirstName = "Мирон", LastName = "Матвеев", DateOfBirth = DateTime.Parse("19-09-1996"), ExamScore = 4.5F },
                    new Student { GroupId = 13, FirstName = "Роман", LastName = "Лебедев", DateOfBirth = DateTime.Parse("08-08-2001"), ExamScore = 4.7F },
                    new Student { GroupId = 13, FirstName = "Ульяна", LastName = "Соловьева", DateOfBirth = DateTime.Parse("01-01-2000"), ExamScore = 3.9F },
                    new Student { GroupId = 13, FirstName = "Даниил", LastName = "Калугин", DateOfBirth = DateTime.Parse("06-02-2000"), ExamScore = 4.6F },
                    new Student { GroupId = 13, FirstName = "София", LastName = "Зорина", DateOfBirth = DateTime.Parse("02-03-1997"), ExamScore = 3.5F },
                    new Student { GroupId = 13, FirstName = "Степан", LastName = "Зотов", DateOfBirth = DateTime.Parse("19-09-2001"), ExamScore = 3.2F },
                    new Student { GroupId = 13, FirstName = "Мария", LastName = "Воронова", DateOfBirth = DateTime.Parse("10-02-1999"), ExamScore = 3.5F },
                    new Student { GroupId = 13, FirstName = "Алиса", LastName = "Данилова", DateOfBirth = DateTime.Parse("14-03-1991"), ExamScore = 3.7F },
                    new Student { GroupId = 13, FirstName = "Константин", LastName = "Киселев", DateOfBirth = DateTime.Parse("18-08-1991"), ExamScore = 3.9F },
                    new Student { GroupId = 13, FirstName = "Арина", LastName = "Ларионова", DateOfBirth = DateTime.Parse("16-01-2000"), ExamScore = 4.2F },
                    new Student { GroupId = 13, FirstName = "Фёдор", LastName = "Наумов", DateOfBirth = DateTime.Parse("07-10-2001"), ExamScore = 5F },
                    new Student { GroupId = 14, FirstName = "Ульяна", LastName = "Попова", DateOfBirth = DateTime.Parse("02-03-1990"), ExamScore = 4.9F },
                    new Student { GroupId = 14, FirstName = "Михаил", LastName = "Лопатин", DateOfBirth = DateTime.Parse("11-11-1992"), ExamScore = 3.9F },
                    new Student { GroupId = 14, FirstName = "Алина", LastName = "Ермакова", DateOfBirth = DateTime.Parse("14-11-1995"), ExamScore = 3.2F },
                    new Student { GroupId = 14, FirstName = "Дарья", LastName = "Щукина", DateOfBirth = DateTime.Parse("24-04-1994"), ExamScore = 3.3F },
                    new Student { GroupId = 14, FirstName = "Георгий", LastName = "Белов", DateOfBirth = DateTime.Parse("22-03-1998"), ExamScore = 4.1F },
                    new Student { GroupId = 14, FirstName = "Анфиса", LastName = "Смирнова", DateOfBirth = DateTime.Parse("31-08-1991"), ExamScore = 4.8F },
                    new Student { GroupId = 14, FirstName = "Сергей", LastName = "Кондратьев", DateOfBirth = DateTime.Parse("16-07-1993"), ExamScore = 4.2F },
                    new Student { GroupId = 14, FirstName = "Таисия", LastName = "Вешнякова", DateOfBirth = DateTime.Parse("19-12-1986"), ExamScore = 3.2F },
                    new Student { GroupId = 14, FirstName = "Варвара", LastName = "Смирнова", DateOfBirth = DateTime.Parse("13-05-1987"), ExamScore = 4.2F },
                    new Student { GroupId = 14, FirstName = "Матвей", LastName = "Леонтьев", DateOfBirth = DateTime.Parse("27-05-1990"), ExamScore = 3.3F },
                    new Student { GroupId = 14, FirstName = "Ева", LastName = "Соловьева", DateOfBirth = DateTime.Parse("08-04-1991"), ExamScore = 4.8F },
                    new Student { GroupId = 15, FirstName = "Иван", LastName = "Губанов", DateOfBirth = DateTime.Parse("13-01-1989"), ExamScore = 4.5F },
                    new Student { GroupId = 15, FirstName = "Елизавета", LastName = "Иванова", DateOfBirth = DateTime.Parse("30-09-1985"), ExamScore = 3.7F },
                    new Student { GroupId = 15, FirstName = "Кирилл", LastName = "Самсонов", DateOfBirth = DateTime.Parse("07-11-1997"), ExamScore = 4.4F },
                    new Student { GroupId = 15, FirstName = "Маргарита", LastName = "Кочергина", DateOfBirth = DateTime.Parse("28-09-1994"), ExamScore = 3.5F },
                    new Student { GroupId = 15, FirstName = "Ярослава", LastName = "Морозова", DateOfBirth = DateTime.Parse("20-09-1986"), ExamScore = 3.5F },
                    new Student { GroupId = 15, FirstName = "Илья", LastName = "Троицкий", DateOfBirth = DateTime.Parse("06-06-1993"), ExamScore = 3F },
                    new Student { GroupId = 15, FirstName = "Анна", LastName = "Кулешова", DateOfBirth = DateTime.Parse("08-01-1989"), ExamScore = 4F },
                    new Student { GroupId = 16, FirstName = "Алина", LastName = "Макеева", DateOfBirth = DateTime.Parse("15-04-1997"), ExamScore = 3.4F },
                    new Student { GroupId = 16, FirstName = "Дарья", LastName = "Агеева", DateOfBirth = DateTime.Parse("27-12-1999"), ExamScore = 4F },
                    new Student { GroupId = 16, FirstName = "Максим", LastName = "Виноградов", DateOfBirth = DateTime.Parse("02-03-1992"), ExamScore = 3.9F },
                    new Student { GroupId = 16, FirstName = "Константин", LastName = "Шишкин", DateOfBirth = DateTime.Parse("28-02-1986"), ExamScore = 4.8F },
                    new Student { GroupId = 16, FirstName = "Ульяна", LastName = "Тихонова", DateOfBirth = DateTime.Parse("04-11-1994"), ExamScore = 4.7F },
                    new Student { GroupId = 16, FirstName = "Максим", LastName = "Лаптев", DateOfBirth = DateTime.Parse("19-03-1995"), ExamScore = 5F },
                    new Student { GroupId = 16, FirstName = "Анна", LastName = "Щербакова", DateOfBirth = DateTime.Parse("24-01-1986"), ExamScore = 5F },
                    new Student { GroupId = 16, FirstName = "Гордей", LastName = "Кузнецов", DateOfBirth = DateTime.Parse("22-09-1987"), ExamScore = 4F },
                    new Student { GroupId = 16, FirstName = "Лука", LastName = "Лаврентьев", DateOfBirth = DateTime.Parse("14-09-1991"), ExamScore = 3.9F },
                    new Student { GroupId = 16, FirstName = "Мирон", LastName = "Лавров", DateOfBirth = DateTime.Parse("14-08-1989"), ExamScore = 4.7F },
                    new Student { GroupId = 16, FirstName = "Даниил", LastName = "Тихонов", DateOfBirth = DateTime.Parse("27-03-2001"), ExamScore = 3.6F },
                    new Student { GroupId = 16, FirstName = "Ника", LastName = "Кочетова", DateOfBirth = DateTime.Parse("29-05-1998"), ExamScore = 4.7F },
                    new Student { GroupId = 16, FirstName = "Полина", LastName = "Сорокина", DateOfBirth = DateTime.Parse("06-04-1987"), ExamScore = 4.4F },
                    new Student { GroupId = 16, FirstName = "Анна", LastName = "Митрофанова", DateOfBirth = DateTime.Parse("14-10-1996"), ExamScore = 3F },
                    new Student { GroupId = 16, FirstName = "Фёдор", LastName = "Виноградов", DateOfBirth = DateTime.Parse("13-06-1993"), ExamScore = 3.4F },
                    new Student { GroupId = 16, FirstName = "Екатерина", LastName = "Елизарова", DateOfBirth = DateTime.Parse("07-12-1998"), ExamScore = 3.1F },
                    new Student { GroupId = 16, FirstName = "Ангелина", LastName = "Иванова", DateOfBirth = DateTime.Parse("23-04-1995"), ExamScore = 4.5F }
                );
                context.SaveChanges();
            }
        }
    }
}
