using System;
using System.Linq;
using MVC.Common;

namespace MVC.DataAccess
{
    public class SampleData
    {
        public static void Initialize(UniversityContext context)
        {
            if (!context.Courses.Any())
            {
                context.Courses.AddRange(
                    new Course
                    {
                        Name = "Математика",
                        Description = "Царица наук"
                    },
                    new Course
                    {
                        Name = "Физика",
                        Description = "Основа всего"
                    },
                    new Course
                    {
                        Name = "Физкультура",
                        Description = "В здоровом теле - здоровый дух"
                    },
                    new Course
                    {
                        Name = "История",
                        Description = "У того, кто не знает прошлого - нет будущего"
                    }
                );
                context.SaveChanges();
            }

            if (!context.Groups.Any())
            {
                context.Groups.AddRange(
                    new Group { CourseId = 1, Name = "КБ-101" },
                    new Group { CourseId = 2, Name = "ЛП-102" },
                    new Group { CourseId = 3, Name = "РР-103" },
                    new Group { CourseId = 2, Name = "РС-104" },
                    new Group { CourseId = 1, Name = "РА-105" },
                    new Group { CourseId = 3, Name = "РА-202" },
                    new Group { CourseId = 4, Name = "АР-203" },
                    new Group { CourseId = 4, Name = "РА-204" },
                    new Group { CourseId = 1, Name = "НК-205" },
                    new Group { CourseId = 3, Name = "БК-301" },
                    new Group { CourseId = 4, Name = "РА-353" },
                    new Group { CourseId = 1, Name = "РА-333" },
                    new Group { CourseId = 3, Name = "ВП-322" },
                    new Group { CourseId = 3, Name = "УЦ-311" },
                    new Group { CourseId = 1, Name = "МВ-354" },
                    new Group { CourseId = 3, Name = "РА-344" },
                    new Group { CourseId = 3, Name = "ГА-223" },
                    new Group { CourseId = 3, Name = "ПВ-232" },
                    new Group { CourseId = 1, Name = "СП-344" },
                    new Group { CourseId = 1, Name = "ОР-421" },
                    new Group { CourseId = 1, Name = "РФ-231" },
                    new Group { CourseId = 2, Name = "ШО-521" },
                    new Group { CourseId = 2, Name = "РР-214" },
                    new Group { CourseId = 2, Name = "ФП-341" },
                    new Group { CourseId = 4, Name = "ПЦ-344" },
                    new Group { CourseId = 4, Name = "ТО-324" },
                    new Group { CourseId = 4, Name = "НР-433" },
                    new Group { CourseId = 4, Name = "РА-364" }
                );
                context.SaveChanges();
            }

            if (!context.Students.Any())
            {
                context.Students.AddRange(
                    new Student { GroupId = 1, FirstName = "Ксения", LastName = "Пономарева", DateOfBirth = DateTime.Parse("28-11-1991"), ExamScore = 4F },
                    new Student { GroupId = 1, FirstName = "Милана", LastName = "Михайлова", DateOfBirth = DateTime.Parse("08-09-1995"), ExamScore = 5F },
                    new Student { GroupId = 1, FirstName = "Тимофей", LastName = "Яковлев", DateOfBirth = DateTime.Parse("13-08-2001"), ExamScore = 4.3F },
                    new Student { GroupId = 1, FirstName = "Эвелина", LastName = "Михайлова", DateOfBirth = DateTime.Parse("23-12-1996"), ExamScore = 4.5F },
                    new Student { GroupId = 1, FirstName = "Елизавета", LastName = "Волкова", DateOfBirth = DateTime.Parse("13-11-1985"), ExamScore = 3.2F },
                    new Student { GroupId = 1, FirstName = "Ольга", LastName = "Кузнецова", DateOfBirth = DateTime.Parse("30-05-1988"), ExamScore = 4.8F },
                    new Student { GroupId = 1, FirstName = "Илья", LastName = "Харитонов", DateOfBirth = DateTime.Parse("16-03-1993"), ExamScore = 3.5F },
                    new Student { GroupId = 1, FirstName = "Мария", LastName = "Соловьева", DateOfBirth = DateTime.Parse("16-08-1988"), ExamScore = 4.6F },
                    new Student { GroupId = 1, FirstName = "Майя", LastName = "Гришина", DateOfBirth = DateTime.Parse("06-05-1992"), ExamScore = 4.1F },
                    new Student { GroupId = 1, FirstName = "Дарья", LastName = "Корнеева", DateOfBirth = DateTime.Parse("21-10-1986"), ExamScore = 3.8F },
                    new Student { GroupId = 1, FirstName = "Эвелина", LastName = "Горшкова", DateOfBirth = DateTime.Parse("13-10-1994"), ExamScore = 3F },
                    new Student { GroupId = 1, FirstName = "София", LastName = "Юдина", DateOfBirth = DateTime.Parse("17-03-1996"), ExamScore = 3.3F },
                    new Student { GroupId = 1, FirstName = "Ульяна", LastName = "Гаврилова", DateOfBirth = DateTime.Parse("30-07-2001"), ExamScore = 3.2F },
                    new Student { GroupId = 1, FirstName = "Кира", LastName = "Ковалева", DateOfBirth = DateTime.Parse("24-02-1991"), ExamScore = 4.3F },
                    new Student { GroupId = 1, FirstName = "Александра", LastName = "Петрова", DateOfBirth = DateTime.Parse("31-10-1993"), ExamScore = 5F },
                    new Student { GroupId = 1, FirstName = "Никита", LastName = "Румянцев", DateOfBirth = DateTime.Parse("27-10-1989"), ExamScore = 3.5F },
                    new Student { GroupId = 1, FirstName = "Мия", LastName = "Кузьмина", DateOfBirth = DateTime.Parse("23-12-2000"), ExamScore = 4.8F },
                    new Student { GroupId = 2, FirstName = "Милана", LastName = "Куликова", DateOfBirth = DateTime.Parse("10-11-1995"), ExamScore = 3.1F },
                    new Student { GroupId = 2, FirstName = "Анастасия", LastName = "Сергеева", DateOfBirth = DateTime.Parse("01-12-1988"), ExamScore = 3.7F },
                    new Student { GroupId = 2, FirstName = "Денис", LastName = "Чернов", DateOfBirth = DateTime.Parse("31-12-1985"), ExamScore = 5F },
                    new Student { GroupId = 2, FirstName = "Савелий", LastName = "Воронов", DateOfBirth = DateTime.Parse("30-03-1999"), ExamScore = 3.6F },
                    new Student { GroupId = 2, FirstName = "Егор", LastName = "Степанов", DateOfBirth = DateTime.Parse("15-02-1990"), ExamScore = 4.7F },
                    new Student { GroupId = 2, FirstName = "Кирилл", LastName = "Федоров", DateOfBirth = DateTime.Parse("26-05-1989"), ExamScore = 3.5F },
                    new Student { GroupId = 2, FirstName = "Аиша", LastName = "Дубровина", DateOfBirth = DateTime.Parse("29-10-2001"), ExamScore = 4F },
                    new Student { GroupId = 2, FirstName = "Матвей", LastName = "Озеров", DateOfBirth = DateTime.Parse("08-04-1989"), ExamScore = 4.5F },
                    new Student { GroupId = 2, FirstName = "Нина", LastName = "Соловьева", DateOfBirth = DateTime.Parse("21-01-1996"), ExamScore = 4.5F },
                    new Student { GroupId = 2, FirstName = "Константин", LastName = "Павлов", DateOfBirth = DateTime.Parse("07-07-1997"), ExamScore = 4.3F },
                    new Student { GroupId = 2, FirstName = "Макар", LastName = "Захаров", DateOfBirth = DateTime.Parse("15-01-1996"), ExamScore = 3F },
                    new Student { GroupId = 2, FirstName = "Николай", LastName = "Афанасьев", DateOfBirth = DateTime.Parse("28-01-1986"), ExamScore = 5F },
                    new Student { GroupId = 2, FirstName = "Иван", LastName = "Иванов", DateOfBirth = DateTime.Parse("28-01-1992"), ExamScore = 3.4F },
                    new Student { GroupId = 2, FirstName = "Михаил", LastName = "Дмитриев", DateOfBirth = DateTime.Parse("19-12-1986"), ExamScore = 3.1F },
                    new Student { GroupId = 2, FirstName = "Артём", LastName = "Макаров", DateOfBirth = DateTime.Parse("23-06-1990"), ExamScore = 3.9F },
                    new Student { GroupId = 2, FirstName = "Ева", LastName = "Рябинина", DateOfBirth = DateTime.Parse("24-06-1990"), ExamScore = 4F },
                    new Student { GroupId = 2, FirstName = "Роман", LastName = "Кузьмин", DateOfBirth = DateTime.Parse("28-08-1985"), ExamScore = 3F },
                    new Student { GroupId = 2, FirstName = "Софья", LastName = "Винокурова", DateOfBirth = DateTime.Parse("16-09-1999"), ExamScore = 3.2F },
                    new Student { GroupId = 2, FirstName = "Мария", LastName = "Пирогова", DateOfBirth = DateTime.Parse("23-05-1985"), ExamScore = 4.1F },
                    new Student { GroupId = 3, FirstName = "Максим", LastName = "Денисов", DateOfBirth = DateTime.Parse("28-05-1986"), ExamScore = 3.3F },
                    new Student { GroupId = 3, FirstName = "Артём", LastName = "Колпаков", DateOfBirth = DateTime.Parse("07-08-2000"), ExamScore = 4F },
                    new Student { GroupId = 3, FirstName = "Лев", LastName = "Попов", DateOfBirth = DateTime.Parse("13-11-1994"), ExamScore = 4F },
                    new Student { GroupId = 3, FirstName = "Кира", LastName = "Савельева", DateOfBirth = DateTime.Parse("03-03-1995"), ExamScore = 3.2F },
                    new Student { GroupId = 3, FirstName = "Даниил", LastName = "Лаптев", DateOfBirth = DateTime.Parse("23-05-1991"), ExamScore = 3.4F },
                    new Student { GroupId = 3, FirstName = "Амира", LastName = "Филатова", DateOfBirth = DateTime.Parse("07-05-1992"), ExamScore = 3.7F },
                    new Student { GroupId = 3, FirstName = "Любовь", LastName = "Покровская", DateOfBirth = DateTime.Parse("19-01-1991"), ExamScore = 4F },
                    new Student { GroupId = 3, FirstName = "Евгения", LastName = "Алексеева", DateOfBirth = DateTime.Parse("09-02-2000"), ExamScore = 3.8F },
                    new Student { GroupId = 3, FirstName = "Тимофей", LastName = "Тарасов", DateOfBirth = DateTime.Parse("28-07-1987"), ExamScore = 4.3F },
                    new Student { GroupId = 3, FirstName = "Платон", LastName = "Терехов", DateOfBirth = DateTime.Parse("30-09-1985"), ExamScore = 3.8F },
                    new Student { GroupId = 3, FirstName = "Анна", LastName = "Андрианова", DateOfBirth = DateTime.Parse("05-01-1990"), ExamScore = 4.5F },
                    new Student { GroupId = 3, FirstName = "Арина", LastName = "Зуева", DateOfBirth = DateTime.Parse("08-10-2000"), ExamScore = 4.5F },
                    new Student { GroupId = 3, FirstName = "Арина", LastName = "Савельева", DateOfBirth = DateTime.Parse("13-11-1988"), ExamScore = 3.1F },
                    new Student { GroupId = 3, FirstName = "Тимофей", LastName = "Федотов", DateOfBirth = DateTime.Parse("23-05-1996"), ExamScore = 4.1F },
                    new Student { GroupId = 3, FirstName = "Владислав", LastName = "Капустин", DateOfBirth = DateTime.Parse("05-04-1988"), ExamScore = 5F },
                    new Student { GroupId = 3, FirstName = "Матвей", LastName = "Волков", DateOfBirth = DateTime.Parse("02-12-1994"), ExamScore = 4.2F },
                    new Student { GroupId = 3, FirstName = "Варвара", LastName = "Краснова", DateOfBirth = DateTime.Parse("25-06-1992"), ExamScore = 3.8F },
                    new Student { GroupId = 3, FirstName = "Матвей", LastName = "Воробьев", DateOfBirth = DateTime.Parse("12-07-1989"), ExamScore = 3.4F },
                    new Student { GroupId = 3, FirstName = "Мария", LastName = "Степанова", DateOfBirth = DateTime.Parse("24-04-1999"), ExamScore = 4.9F },
                    new Student { GroupId = 3, FirstName = "Нина", LastName = "Абрамова", DateOfBirth = DateTime.Parse("03-02-1987"), ExamScore = 4.8F },
                    new Student { GroupId = 4, FirstName = "Герман", LastName = "Кукушкин", DateOfBirth = DateTime.Parse("28-12-1990"), ExamScore = 4.4F },
                    new Student { GroupId = 4, FirstName = "Виктория", LastName = "Блинова", DateOfBirth = DateTime.Parse("19-01-1992"), ExamScore = 4.9F },
                    new Student { GroupId = 4, FirstName = "Алёна", LastName = "Морозова", DateOfBirth = DateTime.Parse("20-01-1998"), ExamScore = 4F },
                    new Student { GroupId = 4, FirstName = "Виктория", LastName = "Тарасова", DateOfBirth = DateTime.Parse("03-10-1999"), ExamScore = 4.1F },
                    new Student { GroupId = 4, FirstName = "Алексей", LastName = "Беляев", DateOfBirth = DateTime.Parse("21-09-1999"), ExamScore = 4.3F },
                    new Student { GroupId = 4, FirstName = "Елизавета", LastName = "Малышева", DateOfBirth = DateTime.Parse("25-01-1997"), ExamScore = 3.2F },
                    new Student { GroupId = 4, FirstName = "Максим", LastName = "Егоров", DateOfBirth = DateTime.Parse("05-02-1989"), ExamScore = 3.4F },
                    new Student { GroupId = 4, FirstName = "Максим", LastName = "Дубов", DateOfBirth = DateTime.Parse("14-04-1995"), ExamScore = 3F },
                    new Student { GroupId = 4, FirstName = "Елизавета", LastName = "Смирнова", DateOfBirth = DateTime.Parse("04-05-1990"), ExamScore = 3.1F },
                    new Student { GroupId = 4, FirstName = "Алиса", LastName = "Корнилова", DateOfBirth = DateTime.Parse("11-08-2001"), ExamScore = 4.1F },
                    new Student { GroupId = 4, FirstName = "Ян", LastName = "Герасимов", DateOfBirth = DateTime.Parse("27-12-1987"), ExamScore = 4.6F },
                    new Student { GroupId = 4, FirstName = "Олег", LastName = "Смирнов", DateOfBirth = DateTime.Parse("09-06-1997"), ExamScore = 3.7F },
                    new Student { GroupId = 4, FirstName = "Елисей", LastName = "Аксенов", DateOfBirth = DateTime.Parse("23-08-1993"), ExamScore = 4F },
                    new Student { GroupId = 4, FirstName = "Сергей", LastName = "Лукьянов", DateOfBirth = DateTime.Parse("07-07-1998"), ExamScore = 4.5F },
                    new Student { GroupId = 4, FirstName = "Полина", LastName = "Ковалева", DateOfBirth = DateTime.Parse("28-05-1999"), ExamScore = 4.8F },
                    new Student { GroupId = 5, FirstName = "Мирон", LastName = "Казаков", DateOfBirth = DateTime.Parse("17-10-1993"), ExamScore = 4.4F },
                    new Student { GroupId = 5, FirstName = "Алиса", LastName = "Логинова", DateOfBirth = DateTime.Parse("07-11-2001"), ExamScore = 5F },
                    new Student { GroupId = 5, FirstName = "Ксения", LastName = "Попова", DateOfBirth = DateTime.Parse("24-10-1986"), ExamScore = 3.2F },
                    new Student { GroupId = 5, FirstName = "Ангелина", LastName = "Кондрашова", DateOfBirth = DateTime.Parse("20-07-1985"), ExamScore = 3.1F },
                    new Student { GroupId = 5, FirstName = "Ульяна", LastName = "Давыдова", DateOfBirth = DateTime.Parse("30-10-1985"), ExamScore = 3.3F },
                    new Student { GroupId = 5, FirstName = "Анастасия", LastName = "Капустина", DateOfBirth = DateTime.Parse("10-08-1991"), ExamScore = 3.8F },
                    new Student { GroupId = 5, FirstName = "Макар", LastName = "Корнеев", DateOfBirth = DateTime.Parse("20-11-1998"), ExamScore = 4.5F },
                    new Student { GroupId = 5, FirstName = "Давид", LastName = "Голованов", DateOfBirth = DateTime.Parse("01-03-1995"), ExamScore = 4.6F },
                    new Student { GroupId = 5, FirstName = "Диана", LastName = "Колесникова", DateOfBirth = DateTime.Parse("13-05-2000"), ExamScore = 3.2F },
                    new Student { GroupId = 5, FirstName = "Константин", LastName = "Волков", DateOfBirth = DateTime.Parse("07-07-1990"), ExamScore = 3.3F },
                    new Student { GroupId = 5, FirstName = "Арина", LastName = "Чернышева", DateOfBirth = DateTime.Parse("09-02-1991"), ExamScore = 4.8F },
                    new Student { GroupId = 5, FirstName = "Евдокия", LastName = "Прохорова", DateOfBirth = DateTime.Parse("27-12-1995"), ExamScore = 3F },
                    new Student { GroupId = 5, FirstName = "Никита", LastName = "Тарасов", DateOfBirth = DateTime.Parse("01-10-1988"), ExamScore = 3.1F },
                    new Student { GroupId = 5, FirstName = "Лев", LastName = "Калинин", DateOfBirth = DateTime.Parse("23-12-2000"), ExamScore = 4.4F },
                    new Student { GroupId = 5, FirstName = "Георгий", LastName = "Большаков", DateOfBirth = DateTime.Parse("19-10-1996"), ExamScore = 4.3F },
                    new Student { GroupId = 5, FirstName = "Виктория", LastName = "Яшина", DateOfBirth = DateTime.Parse("03-01-1993"), ExamScore = 4.5F },
                    new Student { GroupId = 5, FirstName = "Лев", LastName = "Иванов", DateOfBirth = DateTime.Parse("09-03-1994"), ExamScore = 4.5F },
                    new Student { GroupId = 5, FirstName = "Елизавета", LastName = "Романова", DateOfBirth = DateTime.Parse("18-10-1990"), ExamScore = 4.9F },
                    new Student { GroupId = 5, FirstName = "Виктория", LastName = "Медведева", DateOfBirth = DateTime.Parse("15-12-2000"), ExamScore = 3.9F },
                    new Student { GroupId = 6, FirstName = "Анастасия", LastName = "Иванова", DateOfBirth = DateTime.Parse("27-10-1995"), ExamScore = 4.8F },
                    new Student { GroupId = 6, FirstName = "Елизавета", LastName = "Константинова", DateOfBirth = DateTime.Parse("18-04-1998"), ExamScore = 3.5F },
                    new Student { GroupId = 6, FirstName = "Мирослава", LastName = "Высоцкая", DateOfBirth = DateTime.Parse("06-12-1988"), ExamScore = 4.8F },
                    new Student { GroupId = 6, FirstName = "Никита", LastName = "Рубцов", DateOfBirth = DateTime.Parse("09-12-1986"), ExamScore = 3.6F },
                    new Student { GroupId = 6, FirstName = "Степан", LastName = "Ильин", DateOfBirth = DateTime.Parse("17-09-1989"), ExamScore = 3.3F },
                    new Student { GroupId = 6, FirstName = "Арина", LastName = "Егорова", DateOfBirth = DateTime.Parse("15-01-1996"), ExamScore = 4.4F },
                    new Student { GroupId = 6, FirstName = "Таисия", LastName = "Дубровина", DateOfBirth = DateTime.Parse("24-07-1994"), ExamScore = 3.2F },
                    new Student { GroupId = 6, FirstName = "Арина", LastName = "Воробьева", DateOfBirth = DateTime.Parse("12-10-1989"), ExamScore = 3.7F },
                    new Student { GroupId = 6, FirstName = "Вероника", LastName = "Пономарева", DateOfBirth = DateTime.Parse("05-08-1985"), ExamScore = 4.4F },
                    new Student { GroupId = 6, FirstName = "Михаил", LastName = "Львов", DateOfBirth = DateTime.Parse("09-01-1986"), ExamScore = 3.4F },
                    new Student { GroupId = 6, FirstName = "Дмитрий", LastName = "Семенов", DateOfBirth = DateTime.Parse("20-04-1995"), ExamScore = 4.3F },
                    new Student { GroupId = 6, FirstName = "Ульяна", LastName = "Краснова", DateOfBirth = DateTime.Parse("30-08-1999"), ExamScore = 3.2F },
                    new Student { GroupId = 6, FirstName = "Малика", LastName = "Козлова", DateOfBirth = DateTime.Parse("27-07-1988"), ExamScore = 3.2F },
                    new Student { GroupId = 6, FirstName = "Полина", LastName = "Воробьева", DateOfBirth = DateTime.Parse("20-05-1996"), ExamScore = 3F },
                    new Student { GroupId = 6, FirstName = "Владислав", LastName = "Нефедов", DateOfBirth = DateTime.Parse("29-08-2000"), ExamScore = 3.8F },
                    new Student { GroupId = 6, FirstName = "Арсений", LastName = "Рогов", DateOfBirth = DateTime.Parse("30-11-1987"), ExamScore = 4.2F },
                    new Student { GroupId = 6, FirstName = "София", LastName = "Ракова", DateOfBirth = DateTime.Parse("13-03-2000"), ExamScore = 4.8F },
                    new Student { GroupId = 6, FirstName = "Вероника", LastName = "Денисова", DateOfBirth = DateTime.Parse("27-01-1989"), ExamScore = 4.6F },
                    new Student { GroupId = 7, FirstName = "Павел", LastName = "Медведев", DateOfBirth = DateTime.Parse("06-06-1999"), ExamScore = 4.6F },
                    new Student { GroupId = 7, FirstName = "Николай", LastName = "Исаев", DateOfBirth = DateTime.Parse("29-08-1993"), ExamScore = 3.4F },
                    new Student { GroupId = 7, FirstName = "Кирилл", LastName = "Жилин", DateOfBirth = DateTime.Parse("25-08-1996"), ExamScore = 3.1F },
                    new Student { GroupId = 7, FirstName = "Вероника", LastName = "Кузнецова", DateOfBirth = DateTime.Parse("21-09-1987"), ExamScore = 4.6F },
                    new Student { GroupId = 7, FirstName = "Серафима", LastName = "Волкова", DateOfBirth = DateTime.Parse("06-11-1996"), ExamScore = 5F },
                    new Student { GroupId = 7, FirstName = "Екатерина", LastName = "Вавилова", DateOfBirth = DateTime.Parse("10-08-2000"), ExamScore = 3.6F },
                    new Student { GroupId = 7, FirstName = "Дарья", LastName = "Фокина", DateOfBirth = DateTime.Parse("22-09-1987"), ExamScore = 4.7F },
                    new Student { GroupId = 7, FirstName = "Марк", LastName = "Кудряшов", DateOfBirth = DateTime.Parse("20-06-1995"), ExamScore = 4.2F },
                    new Student { GroupId = 7, FirstName = "Анна", LastName = "Воронкова", DateOfBirth = DateTime.Parse("28-01-1987"), ExamScore = 4.7F },
                    new Student { GroupId = 7, FirstName = "Тимофей", LastName = "Коновалов", DateOfBirth = DateTime.Parse("16-10-2001"), ExamScore = 3F },
                    new Student { GroupId = 7, FirstName = "Софья", LastName = "Алешина", DateOfBirth = DateTime.Parse("09-01-1987"), ExamScore = 3.5F },
                    new Student { GroupId = 7, FirstName = "Артём", LastName = "Исаев", DateOfBirth = DateTime.Parse("11-06-1991"), ExamScore = 3.7F },
                    new Student { GroupId = 7, FirstName = "Оливия", LastName = "Крючкова", DateOfBirth = DateTime.Parse("18-11-1990"), ExamScore = 4.9F },
                    new Student { GroupId = 7, FirstName = "Мария", LastName = "Сорокина", DateOfBirth = DateTime.Parse("09-07-2001"), ExamScore = 3.9F },
                    new Student { GroupId = 7, FirstName = "Елизавета", LastName = "Фролова", DateOfBirth = DateTime.Parse("08-11-1988"), ExamScore = 3.8F },
                    new Student { GroupId = 7, FirstName = "Андрей", LastName = "Бочаров", DateOfBirth = DateTime.Parse("02-05-2001"), ExamScore = 4F },
                    new Student { GroupId = 7, FirstName = "Мелисса", LastName = "Щеглова", DateOfBirth = DateTime.Parse("02-08-1999"), ExamScore = 4.1F },
                    new Student { GroupId = 7, FirstName = "Арсений", LastName = "Попов", DateOfBirth = DateTime.Parse("17-04-1994"), ExamScore = 3.4F },
                    new Student { GroupId = 7, FirstName = "Давид", LastName = "Шубин", DateOfBirth = DateTime.Parse("01-08-1992"), ExamScore = 4.1F },
                    new Student { GroupId = 8, FirstName = "Мирослава", LastName = "Яковлева", DateOfBirth = DateTime.Parse("26-08-1996"), ExamScore = 4.4F },
                    new Student { GroupId = 8, FirstName = "Алексей", LastName = "Богданов", DateOfBirth = DateTime.Parse("13-09-1996"), ExamScore = 4.1F },
                    new Student { GroupId = 8, FirstName = "Михаил", LastName = "Смирнов", DateOfBirth = DateTime.Parse("08-11-1987"), ExamScore = 4.2F },
                    new Student { GroupId = 8, FirstName = "Тимур", LastName = "Новиков", DateOfBirth = DateTime.Parse("03-02-1999"), ExamScore = 4.3F },
                    new Student { GroupId = 8, FirstName = "Варвара", LastName = "Бирюкова", DateOfBirth = DateTime.Parse("03-06-2001"), ExamScore = 4.1F },
                    new Student { GroupId = 8, FirstName = "Давид", LastName = "Гусев", DateOfBirth = DateTime.Parse("27-05-1997"), ExamScore = 3.1F },
                    new Student { GroupId = 8, FirstName = "Иван", LastName = "Богданов", DateOfBirth = DateTime.Parse("10-01-1993"), ExamScore = 3.1F },
                    new Student { GroupId = 8, FirstName = "Александр", LastName = "Агапов", DateOfBirth = DateTime.Parse("11-07-1993"), ExamScore = 4.2F },
                    new Student { GroupId = 8, FirstName = "Михаил", LastName = "Самсонов", DateOfBirth = DateTime.Parse("06-11-1991"), ExamScore = 4.5F },
                    new Student { GroupId = 8, FirstName = "Кира", LastName = "Васильева", DateOfBirth = DateTime.Parse("12-09-1994"), ExamScore = 3.4F },
                    new Student { GroupId = 8, FirstName = "Кирилл", LastName = "Фадеев", DateOfBirth = DateTime.Parse("19-11-1992"), ExamScore = 3.6F },
                    new Student { GroupId = 8, FirstName = "Даниил", LastName = "Сычев", DateOfBirth = DateTime.Parse("02-02-1994"), ExamScore = 5F },
                    new Student { GroupId = 8, FirstName = "Роман", LastName = "Степанов", DateOfBirth = DateTime.Parse("25-05-1993"), ExamScore = 4F },
                    new Student { GroupId = 8, FirstName = "Наталья", LastName = "Фомина", DateOfBirth = DateTime.Parse("21-12-1985"), ExamScore = 4.9F },
                    new Student { GroupId = 8, FirstName = "Тимофей", LastName = "Кулаков", DateOfBirth = DateTime.Parse("20-10-1996"), ExamScore = 3.2F },
                    new Student { GroupId = 8, FirstName = "Яна", LastName = "Михайлова", DateOfBirth = DateTime.Parse("19-03-1998"), ExamScore = 4.4F },
                    new Student { GroupId = 8, FirstName = "Вячеслав", LastName = "Михайлов", DateOfBirth = DateTime.Parse("05-01-1987"), ExamScore = 4.6F },
                    new Student { GroupId = 8, FirstName = "Ариана", LastName = "Демидова", DateOfBirth = DateTime.Parse("15-01-1986"), ExamScore = 3.3F },
                    new Student { GroupId = 9, FirstName = "Илья", LastName = "Леонтьев", DateOfBirth = DateTime.Parse("25-09-1989"), ExamScore = 3.3F },
                    new Student { GroupId = 9, FirstName = "Мирон", LastName = "Матвеев", DateOfBirth = DateTime.Parse("11-10-2000"), ExamScore = 3.5F },
                    new Student { GroupId = 9, FirstName = "Роман", LastName = "Лебедев", DateOfBirth = DateTime.Parse("08-03-1999"), ExamScore = 3.9F },
                    new Student { GroupId = 9, FirstName = "Ульяна", LastName = "Соловьева", DateOfBirth = DateTime.Parse("30-05-1988"), ExamScore = 4F },
                    new Student { GroupId = 9, FirstName = "Даниил", LastName = "Калугин", DateOfBirth = DateTime.Parse("26-06-1991"), ExamScore = 4.3F },
                    new Student { GroupId = 9, FirstName = "София", LastName = "Зорина", DateOfBirth = DateTime.Parse("12-12-1997"), ExamScore = 4.8F },
                    new Student { GroupId = 9, FirstName = "Степан", LastName = "Зотов", DateOfBirth = DateTime.Parse("05-10-1997"), ExamScore = 3.1F },
                    new Student { GroupId = 9, FirstName = "Мария", LastName = "Воронова", DateOfBirth = DateTime.Parse("08-02-1994"), ExamScore = 4.8F },
                    new Student { GroupId = 9, FirstName = "Алиса", LastName = "Данилова", DateOfBirth = DateTime.Parse("18-10-1996"), ExamScore = 3.1F },
                    new Student { GroupId = 9, FirstName = "Константин", LastName = "Киселев", DateOfBirth = DateTime.Parse("31-05-2001"), ExamScore = 4.8F },
                    new Student { GroupId = 9, FirstName = "Арина", LastName = "Ларионова", DateOfBirth = DateTime.Parse("22-08-1997"), ExamScore = 3.9F },
                    new Student { GroupId = 9, FirstName = "Фёдор", LastName = "Наумов", DateOfBirth = DateTime.Parse("21-01-1999"), ExamScore = 4.9F },
                    new Student { GroupId = 9, FirstName = "Ульяна", LastName = "Попова", DateOfBirth = DateTime.Parse("01-05-1990"), ExamScore = 5F },
                    new Student { GroupId = 9, FirstName = "Михаил", LastName = "Лопатин", DateOfBirth = DateTime.Parse("27-03-1995"), ExamScore = 3.9F },
                    new Student { GroupId = 9, FirstName = "Алина", LastName = "Ермакова", DateOfBirth = DateTime.Parse("26-12-2001"), ExamScore = 3F },
                    new Student { GroupId = 9, FirstName = "Дарья", LastName = "Щукина", DateOfBirth = DateTime.Parse("07-05-1996"), ExamScore = 4.3F },
                    new Student { GroupId = 9, FirstName = "Георгий", LastName = "Белов", DateOfBirth = DateTime.Parse("04-07-1989"), ExamScore = 3.1F },
                    new Student { GroupId = 9, FirstName = "Анфиса", LastName = "Смирнова", DateOfBirth = DateTime.Parse("11-12-1987"), ExamScore = 3.1F },
                    new Student { GroupId = 9, FirstName = "Сергей", LastName = "Кондратьев", DateOfBirth = DateTime.Parse("22-01-1985"), ExamScore = 4.8F },
                    new Student { GroupId = 10, FirstName = "Таисия", LastName = "Вешнякова", DateOfBirth = DateTime.Parse("31-03-1988"), ExamScore = 4.7F },
                    new Student { GroupId = 10, FirstName = "Варвара", LastName = "Смирнова", DateOfBirth = DateTime.Parse("12-06-1993"), ExamScore = 4.4F },
                    new Student { GroupId = 10, FirstName = "Матвей", LastName = "Леонтьев", DateOfBirth = DateTime.Parse("25-05-1999"), ExamScore = 4.2F },
                    new Student { GroupId = 10, FirstName = "Ева", LastName = "Соловьева", DateOfBirth = DateTime.Parse("19-12-1999"), ExamScore = 3.6F },
                    new Student { GroupId = 10, FirstName = "Иван", LastName = "Губанов", DateOfBirth = DateTime.Parse("09-08-1986"), ExamScore = 4.4F },
                    new Student { GroupId = 10, FirstName = "Елизавета", LastName = "Иванова", DateOfBirth = DateTime.Parse("16-09-1999"), ExamScore = 4.1F },
                    new Student { GroupId = 10, FirstName = "Кирилл", LastName = "Самсонов", DateOfBirth = DateTime.Parse("20-03-1999"), ExamScore = 3.9F },
                    new Student { GroupId = 10, FirstName = "Маргарита", LastName = "Кочергина", DateOfBirth = DateTime.Parse("28-05-2000"), ExamScore = 5F },
                    new Student { GroupId = 10, FirstName = "Ярослава", LastName = "Морозова", DateOfBirth = DateTime.Parse("19-06-1987"), ExamScore = 3.7F },
                    new Student { GroupId = 10, FirstName = "Илья", LastName = "Троицкий", DateOfBirth = DateTime.Parse("23-07-1987"), ExamScore = 3.1F },
                    new Student { GroupId = 10, FirstName = "Анна", LastName = "Кулешова", DateOfBirth = DateTime.Parse("07-11-1999"), ExamScore = 4.4F },
                    new Student { GroupId = 10, FirstName = "Алина", LastName = "Макеева", DateOfBirth = DateTime.Parse("26-08-1995"), ExamScore = 3.2F },
                    new Student { GroupId = 10, FirstName = "Дарья", LastName = "Агеева", DateOfBirth = DateTime.Parse("18-05-1991"), ExamScore = 4.9F },
                    new Student { GroupId = 10, FirstName = "Максим", LastName = "Виноградов", DateOfBirth = DateTime.Parse("09-03-2001"), ExamScore = 3.9F },
                    new Student { GroupId = 10, FirstName = "Константин", LastName = "Шишкин", DateOfBirth = DateTime.Parse("29-04-1994"), ExamScore = 3.9F },
                    new Student { GroupId = 10, FirstName = "Ульяна", LastName = "Тихонова", DateOfBirth = DateTime.Parse("02-01-1992"), ExamScore = 3.8F },
                    new Student { GroupId = 10, FirstName = "Максим", LastName = "Лаптев", DateOfBirth = DateTime.Parse("08-06-1998"), ExamScore = 3.8F },
                    new Student { GroupId = 10, FirstName = "Анна", LastName = "Щербакова", DateOfBirth = DateTime.Parse("13-12-1991"), ExamScore = 4.2F },
                    new Student { GroupId = 10, FirstName = "Гордей", LastName = "Кузнецов", DateOfBirth = DateTime.Parse("22-05-1996"), ExamScore = 3F },
                    new Student { GroupId = 11, FirstName = "Лука", LastName = "Лаврентьев", DateOfBirth = DateTime.Parse("22-06-1998"), ExamScore = 4.7F },
                    new Student { GroupId = 11, FirstName = "Мирон", LastName = "Лавров", DateOfBirth = DateTime.Parse("07-01-1999"), ExamScore = 3.4F },
                    new Student { GroupId = 11, FirstName = "Даниил", LastName = "Тихонов", DateOfBirth = DateTime.Parse("01-03-1986"), ExamScore = 3.7F },
                    new Student { GroupId = 11, FirstName = "Ника", LastName = "Кочетова", DateOfBirth = DateTime.Parse("11-12-1999"), ExamScore = 4.6F },
                    new Student { GroupId = 11, FirstName = "Полина", LastName = "Сорокина", DateOfBirth = DateTime.Parse("20-03-1994"), ExamScore = 3.6F },
                    new Student { GroupId = 11, FirstName = "Анна", LastName = "Митрофанова", DateOfBirth = DateTime.Parse("05-11-1999"), ExamScore = 3.8F },
                    new Student { GroupId = 11, FirstName = "Фёдор", LastName = "Виноградов", DateOfBirth = DateTime.Parse("01-01-1996"), ExamScore = 4.3F },
                    new Student { GroupId = 11, FirstName = "Екатерина", LastName = "Елизарова", DateOfBirth = DateTime.Parse("20-09-1992"), ExamScore = 4.6F },
                    new Student { GroupId = 11, FirstName = "Ангелина", LastName = "Иванова", DateOfBirth = DateTime.Parse("16-09-1996"), ExamScore = 3.1F },
                    new Student { GroupId = 11, FirstName = "Елизавета", LastName = "Козловская", DateOfBirth = DateTime.Parse("23-05-1998"), ExamScore = 4.6F },
                    new Student { GroupId = 11, FirstName = "Егор", LastName = "Гаврилов", DateOfBirth = DateTime.Parse("22-05-2001"), ExamScore = 3.6F },
                    new Student { GroupId = 11, FirstName = "Аглая", LastName = "Смирнова", DateOfBirth = DateTime.Parse("20-09-1986"), ExamScore = 3.2F },
                    new Student { GroupId = 11, FirstName = "Матвей", LastName = "Потапов", DateOfBirth = DateTime.Parse("09-11-1999"), ExamScore = 3.3F },
                    new Student { GroupId = 11, FirstName = "Артём", LastName = "Зайцев", DateOfBirth = DateTime.Parse("22-11-1999"), ExamScore = 3.8F },
                    new Student { GroupId = 11, FirstName = "Алиса", LastName = "Алексеева", DateOfBirth = DateTime.Parse("29-04-1991"), ExamScore = 3.4F },
                    new Student { GroupId = 11, FirstName = "Макар", LastName = "Семенов", DateOfBirth = DateTime.Parse("29-11-1989"), ExamScore = 5F },
                    new Student { GroupId = 11, FirstName = "Артур", LastName = "Некрасов", DateOfBirth = DateTime.Parse("08-11-1991"), ExamScore = 4.3F },
                    new Student { GroupId = 11, FirstName = "Анастасия", LastName = "Парамонова", DateOfBirth = DateTime.Parse("08-06-1985"), ExamScore = 3F },
                    new Student { GroupId = 12, FirstName = "Михаил", LastName = "Муратов", DateOfBirth = DateTime.Parse("27-10-1994"), ExamScore = 4.3F },
                    new Student { GroupId = 12, FirstName = "Максим", LastName = "Андреев", DateOfBirth = DateTime.Parse("17-04-1998"), ExamScore = 3.5F },
                    new Student { GroupId = 12, FirstName = "Мирон", LastName = "Коновалов", DateOfBirth = DateTime.Parse("10-11-1997"), ExamScore = 4.2F },
                    new Student { GroupId = 12, FirstName = "Алёна", LastName = "Фетисова", DateOfBirth = DateTime.Parse("16-11-1995"), ExamScore = 4.7F },
                    new Student { GroupId = 12, FirstName = "Таисия", LastName = "Морозова", DateOfBirth = DateTime.Parse("23-11-1989"), ExamScore = 3.5F },
                    new Student { GroupId = 12, FirstName = "Злата", LastName = "Соколова", DateOfBirth = DateTime.Parse("04-05-1993"), ExamScore = 4.3F },
                    new Student { GroupId = 12, FirstName = "Полина", LastName = "Карпова", DateOfBirth = DateTime.Parse("24-02-1996"), ExamScore = 3.6F },
                    new Student { GroupId = 12, FirstName = "Даниил", LastName = "Шилов", DateOfBirth = DateTime.Parse("28-07-1995"), ExamScore = 3.9F },
                    new Student { GroupId = 12, FirstName = "Никита", LastName = "Быков", DateOfBirth = DateTime.Parse("08-01-2001"), ExamScore = 3.7F },
                    new Student { GroupId = 12, FirstName = "Иван", LastName = "Зимин", DateOfBirth = DateTime.Parse("11-07-1995"), ExamScore = 3.1F },
                    new Student { GroupId = 12, FirstName = "Максим", LastName = "Болдырев", DateOfBirth = DateTime.Parse("23-06-1999"), ExamScore = 3.8F },
                    new Student { GroupId = 12, FirstName = "Владислав", LastName = "Кудряшов", DateOfBirth = DateTime.Parse("01-05-1988"), ExamScore = 3.7F },
                    new Student { GroupId = 12, FirstName = "Мирослава", LastName = "Федорова", DateOfBirth = DateTime.Parse("29-06-1995"), ExamScore = 3.8F },
                    new Student { GroupId = 12, FirstName = "Лев", LastName = "Сальников", DateOfBirth = DateTime.Parse("11-12-1995"), ExamScore = 3.8F },
                    new Student { GroupId = 12, FirstName = "Роман", LastName = "Елизаров", DateOfBirth = DateTime.Parse("15-08-1999"), ExamScore = 3.6F },
                    new Student { GroupId = 12, FirstName = "Сергей", LastName = "Кузьмин", DateOfBirth = DateTime.Parse("13-06-2001"), ExamScore = 5F },
                    new Student { GroupId = 13, FirstName = "Варвара", LastName = "Кудряшова", DateOfBirth = DateTime.Parse("22-08-1993"), ExamScore = 3.7F },
                    new Student { GroupId = 13, FirstName = "Олеся", LastName = "Борисова", DateOfBirth = DateTime.Parse("11-06-1988"), ExamScore = 4.1F },
                    new Student { GroupId = 13, FirstName = "Виктория", LastName = "Прохорова", DateOfBirth = DateTime.Parse("16-07-1997"), ExamScore = 3.3F },
                    new Student { GroupId = 13, FirstName = "Артём", LastName = "Поляков", DateOfBirth = DateTime.Parse("29-10-1989"), ExamScore = 4.9F },
                    new Student { GroupId = 13, FirstName = "Василиса", LastName = "Кузнецова", DateOfBirth = DateTime.Parse("20-06-1988"), ExamScore = 4.8F },
                    new Student { GroupId = 13, FirstName = "Владислав", LastName = "Дубинин", DateOfBirth = DateTime.Parse("17-05-1995"), ExamScore = 4.2F },
                    new Student { GroupId = 13, FirstName = "Руслан", LastName = "Михайлов", DateOfBirth = DateTime.Parse("20-12-1995"), ExamScore = 5F },
                    new Student { GroupId = 13, FirstName = "Таисия", LastName = "Королева", DateOfBirth = DateTime.Parse("24-09-1989"), ExamScore = 3.5F },
                    new Student { GroupId = 13, FirstName = "Варвара", LastName = "Денисова", DateOfBirth = DateTime.Parse("29-05-1986"), ExamScore = 4.3F },
                    new Student { GroupId = 13, FirstName = "Анна", LastName = "Анохина", DateOfBirth = DateTime.Parse("06-01-1992"), ExamScore = 4.4F },
                    new Student { GroupId = 13, FirstName = "Всеволод", LastName = "Носов", DateOfBirth = DateTime.Parse("24-01-1987"), ExamScore = 3F },
                    new Student { GroupId = 13, FirstName = "Матвей", LastName = "Панфилов", DateOfBirth = DateTime.Parse("06-12-1993"), ExamScore = 3.7F },
                    new Student { GroupId = 13, FirstName = "Марк", LastName = "Коновалов", DateOfBirth = DateTime.Parse("16-05-1998"), ExamScore = 4.9F },
                    new Student { GroupId = 13, FirstName = "Анастасия", LastName = "Комарова", DateOfBirth = DateTime.Parse("26-10-1996"), ExamScore = 3.2F },
                    new Student { GroupId = 13, FirstName = "Артём", LastName = "Алексеев", DateOfBirth = DateTime.Parse("16-03-2000"), ExamScore = 3.1F },
                    new Student { GroupId = 13, FirstName = "Ульяна", LastName = "Морозова", DateOfBirth = DateTime.Parse("28-01-1987"), ExamScore = 3.1F },
                    new Student { GroupId = 13, FirstName = "Арина", LastName = "Крылова", DateOfBirth = DateTime.Parse("13-08-1991"), ExamScore = 3F },
                    new Student { GroupId = 13, FirstName = "Мирослава", LastName = "Колпакова", DateOfBirth = DateTime.Parse("30-04-1994"), ExamScore = 4.8F },
                    new Student { GroupId = 14, FirstName = "Кирилл", LastName = "Лаврентьев", DateOfBirth = DateTime.Parse("07-10-2001"), ExamScore = 4.7F },
                    new Student { GroupId = 14, FirstName = "Кирилл", LastName = "Калачев", DateOfBirth = DateTime.Parse("13-08-1990"), ExamScore = 3.3F },
                    new Student { GroupId = 14, FirstName = "Марк", LastName = "Левин", DateOfBirth = DateTime.Parse("01-12-1993"), ExamScore = 4.5F },
                    new Student { GroupId = 14, FirstName = "Николай", LastName = "Лобанов", DateOfBirth = DateTime.Parse("13-09-2000"), ExamScore = 3.9F },
                    new Student { GroupId = 14, FirstName = "Карина", LastName = "Иванова", DateOfBirth = DateTime.Parse("02-06-1993"), ExamScore = 3F },
                    new Student { GroupId = 14, FirstName = "Варвара", LastName = "Миронова", DateOfBirth = DateTime.Parse("05-12-1992"), ExamScore = 4.9F },
                    new Student { GroupId = 14, FirstName = "Мирослава", LastName = "Смирнова", DateOfBirth = DateTime.Parse("17-05-1999"), ExamScore = 3.1F },
                    new Student { GroupId = 14, FirstName = "Артём", LastName = "Киселев", DateOfBirth = DateTime.Parse("15-11-2000"), ExamScore = 4.5F },
                    new Student { GroupId = 14, FirstName = "Константин", LastName = "Панин", DateOfBirth = DateTime.Parse("02-11-1989"), ExamScore = 4.9F },
                    new Student { GroupId = 14, FirstName = "Яна", LastName = "Волкова", DateOfBirth = DateTime.Parse("22-05-2001"), ExamScore = 4.3F },
                    new Student { GroupId = 14, FirstName = "Варвара", LastName = "Романова", DateOfBirth = DateTime.Parse("05-06-1997"), ExamScore = 4.8F },
                    new Student { GroupId = 14, FirstName = "Али", LastName = "Романов", DateOfBirth = DateTime.Parse("04-09-1986"), ExamScore = 3F },
                    new Student { GroupId = 14, FirstName = "Елизавета", LastName = "Ермакова", DateOfBirth = DateTime.Parse("19-04-2001"), ExamScore = 3.7F },
                    new Student { GroupId = 14, FirstName = "Павел", LastName = "Голубев", DateOfBirth = DateTime.Parse("27-01-1997"), ExamScore = 4.9F },
                    new Student { GroupId = 14, FirstName = "Валерия", LastName = "Вавилова", DateOfBirth = DateTime.Parse("29-12-1987"), ExamScore = 4.7F },
                    new Student { GroupId = 14, FirstName = "Демид", LastName = "Жуков", DateOfBirth = DateTime.Parse("22-03-1990"), ExamScore = 3.6F },
                    new Student { GroupId = 15, FirstName = "Дмитрий", LastName = "Елисеев", DateOfBirth = DateTime.Parse("19-08-1992"), ExamScore = 4F },
                    new Student { GroupId = 15, FirstName = "Артур", LastName = "Лобанов", DateOfBirth = DateTime.Parse("23-05-1991"), ExamScore = 3.3F },
                    new Student { GroupId = 15, FirstName = "Лев", LastName = "Волков", DateOfBirth = DateTime.Parse("08-03-1986"), ExamScore = 4.3F },
                    new Student { GroupId = 15, FirstName = "Никита", LastName = "Соловьев", DateOfBirth = DateTime.Parse("26-03-1989"), ExamScore = 3.8F },
                    new Student { GroupId = 15, FirstName = "Яна", LastName = "Беляева", DateOfBirth = DateTime.Parse("10-08-1987"), ExamScore = 3.7F },
                    new Student { GroupId = 15, FirstName = "Артём", LastName = "Постников", DateOfBirth = DateTime.Parse("27-08-1987"), ExamScore = 3.5F },
                    new Student { GroupId = 15, FirstName = "Милослава", LastName = "Грачева", DateOfBirth = DateTime.Parse("05-07-1991"), ExamScore = 4.1F },
                    new Student { GroupId = 15, FirstName = "Милана", LastName = "Макарова", DateOfBirth = DateTime.Parse("03-06-2001"), ExamScore = 3.7F },
                    new Student { GroupId = 15, FirstName = "София", LastName = "Зубова", DateOfBirth = DateTime.Parse("05-10-1999"), ExamScore = 4.8F },
                    new Student { GroupId = 15, FirstName = "Алёна", LastName = "Горячева", DateOfBirth = DateTime.Parse("01-04-1993"), ExamScore = 4.9F },
                    new Student { GroupId = 15, FirstName = "Виктория", LastName = "Смирнова", DateOfBirth = DateTime.Parse("16-07-1995"), ExamScore = 3.9F },
                    new Student { GroupId = 15, FirstName = "Матвей", LastName = "Сахаров", DateOfBirth = DateTime.Parse("29-05-1999"), ExamScore = 3.8F },
                    new Student { GroupId = 15, FirstName = "Мия", LastName = "Исаева", DateOfBirth = DateTime.Parse("22-11-1998"), ExamScore = 4.4F },
                    new Student { GroupId = 15, FirstName = "Матвей", LastName = "Коновалов", DateOfBirth = DateTime.Parse("23-08-1993"), ExamScore = 4.5F },
                    new Student { GroupId = 15, FirstName = "Дарья", LastName = "Иванова", DateOfBirth = DateTime.Parse("18-03-1993"), ExamScore = 3.6F },
                    new Student { GroupId = 15, FirstName = "Мария", LastName = "Кириллова", DateOfBirth = DateTime.Parse("17-06-1994"), ExamScore = 4.6F },
                    new Student { GroupId = 15, FirstName = "Савелий", LastName = "Некрасов", DateOfBirth = DateTime.Parse("27-04-1991"), ExamScore = 4.9F },
                    new Student { GroupId = 15, FirstName = "Светлана", LastName = "Астафьева", DateOfBirth = DateTime.Parse("08-12-1990"), ExamScore = 4.4F },
                    new Student { GroupId = 15, FirstName = "Мария", LastName = "Максимова", DateOfBirth = DateTime.Parse("10-06-1986"), ExamScore = 3.8F },
                    new Student { GroupId = 16, FirstName = "Степан", LastName = "Зайцев", DateOfBirth = DateTime.Parse("07-09-1994"), ExamScore = 3F },
                    new Student { GroupId = 16, FirstName = "Никита", LastName = "Григорьев", DateOfBirth = DateTime.Parse("09-02-1987"), ExamScore = 4.2F },
                    new Student { GroupId = 16, FirstName = "Полина", LastName = "Елизарова", DateOfBirth = DateTime.Parse("07-10-1992"), ExamScore = 3.6F },
                    new Student { GroupId = 16, FirstName = "Полина", LastName = "Яковлева", DateOfBirth = DateTime.Parse("06-10-1994"), ExamScore = 3.4F },
                    new Student { GroupId = 16, FirstName = "Иван", LastName = "Виноградов", DateOfBirth = DateTime.Parse("20-08-1996"), ExamScore = 3.5F },
                    new Student { GroupId = 16, FirstName = "Александра", LastName = "Сергеева", DateOfBirth = DateTime.Parse("26-08-1996"), ExamScore = 3.7F },
                    new Student { GroupId = 16, FirstName = "Алёна", LastName = "Боброва", DateOfBirth = DateTime.Parse("11-02-1997"), ExamScore = 4.1F },
                    new Student { GroupId = 16, FirstName = "Софья", LastName = "Зимина", DateOfBirth = DateTime.Parse("30-01-1994"), ExamScore = 5F },
                    new Student { GroupId = 16, FirstName = "Денис", LastName = "Попов", DateOfBirth = DateTime.Parse("19-07-1995"), ExamScore = 4.1F },
                    new Student { GroupId = 16, FirstName = "Матвей", LastName = "Пугачев", DateOfBirth = DateTime.Parse("13-07-1985"), ExamScore = 4.6F },
                    new Student { GroupId = 16, FirstName = "Гордей", LastName = "Морозов", DateOfBirth = DateTime.Parse("28-12-1993"), ExamScore = 3.8F },
                    new Student { GroupId = 16, FirstName = "Евгения", LastName = "Назарова", DateOfBirth = DateTime.Parse("21-06-1995"), ExamScore = 3.1F },
                    new Student { GroupId = 16, FirstName = "Марк", LastName = "Журавлев", DateOfBirth = DateTime.Parse("11-08-1995"), ExamScore = 4.3F },
                    new Student { GroupId = 16, FirstName = "Стефания", LastName = "Кузнецова", DateOfBirth = DateTime.Parse("23-01-1992"), ExamScore = 3.1F },
                    new Student { GroupId = 16, FirstName = "Арсений", LastName = "Алексеев", DateOfBirth = DateTime.Parse("22-07-2000"), ExamScore = 5F },
                    new Student { GroupId = 16, FirstName = "Александр", LastName = "Панкратов", DateOfBirth = DateTime.Parse("11-05-1997"), ExamScore = 3.9F },
                    new Student { GroupId = 16, FirstName = "Ульяна", LastName = "Смирнова", DateOfBirth = DateTime.Parse("24-12-1993"), ExamScore = 3.5F },
                    new Student { GroupId = 16, FirstName = "Макар", LastName = "Логинов", DateOfBirth = DateTime.Parse("26-07-1986"), ExamScore = 4.1F },
                    new Student { GroupId = 16, FirstName = "Артём", LastName = "Борисов", DateOfBirth = DateTime.Parse("17-03-1986"), ExamScore = 4.2F },
                    new Student { GroupId = 16, FirstName = "Александр", LastName = "Кузин", DateOfBirth = DateTime.Parse("24-03-1996"), ExamScore = 3F },
                    new Student { GroupId = 17, FirstName = "Ульяна", LastName = "Соколова", DateOfBirth = DateTime.Parse("19-08-1999"), ExamScore = 3.7F },
                    new Student { GroupId = 17, FirstName = "Вера", LastName = "Устинова", DateOfBirth = DateTime.Parse("16-11-1997"), ExamScore = 3.5F },
                    new Student { GroupId = 17, FirstName = "Ульяна", LastName = "Данилова", DateOfBirth = DateTime.Parse("27-03-1991"), ExamScore = 4.8F },
                    new Student { GroupId = 17, FirstName = "Арина", LastName = "Ежова", DateOfBirth = DateTime.Parse("03-10-1998"), ExamScore = 4.3F },
                    new Student { GroupId = 17, FirstName = "Фёдор", LastName = "Морозов", DateOfBirth = DateTime.Parse("19-01-1987"), ExamScore = 3.6F },
                    new Student { GroupId = 17, FirstName = "Анастасия", LastName = "Дементьева", DateOfBirth = DateTime.Parse("05-05-1998"), ExamScore = 4.1F },
                    new Student { GroupId = 17, FirstName = "Милана", LastName = "Степанова", DateOfBirth = DateTime.Parse("12-12-1986"), ExamScore = 3.6F },
                    new Student { GroupId = 17, FirstName = "Мария", LastName = "Осипова", DateOfBirth = DateTime.Parse("16-01-1989"), ExamScore = 3.8F },
                    new Student { GroupId = 17, FirstName = "Екатерина", LastName = "Васильева", DateOfBirth = DateTime.Parse("18-04-1997"), ExamScore = 3.4F },
                    new Student { GroupId = 17, FirstName = "Иван", LastName = "Сидоров", DateOfBirth = DateTime.Parse("01-01-1992"), ExamScore = 3.4F },
                    new Student { GroupId = 17, FirstName = "Тимофей", LastName = "Данилов", DateOfBirth = DateTime.Parse("20-11-1993"), ExamScore = 3.2F },
                    new Student { GroupId = 17, FirstName = "Георгий", LastName = "Крюков", DateOfBirth = DateTime.Parse("14-04-1986"), ExamScore = 3.7F },
                    new Student { GroupId = 17, FirstName = "Тимофей", LastName = "Терехов", DateOfBirth = DateTime.Parse("09-09-1990"), ExamScore = 5F },
                    new Student { GroupId = 17, FirstName = "Никита", LastName = "Павловский", DateOfBirth = DateTime.Parse("18-09-1997"), ExamScore = 3.2F },
                    new Student { GroupId = 17, FirstName = "Татьяна", LastName = "Голикова", DateOfBirth = DateTime.Parse("21-03-1995"), ExamScore = 4.8F },
                    new Student { GroupId = 17, FirstName = "Артём", LastName = "Власов", DateOfBirth = DateTime.Parse("27-09-1988"), ExamScore = 4.3F },
                    new Student { GroupId = 17, FirstName = "Амира", LastName = "Малинина", DateOfBirth = DateTime.Parse("14-06-1999"), ExamScore = 3.6F },
                    new Student { GroupId = 17, FirstName = "Алексей", LastName = "Данилов", DateOfBirth = DateTime.Parse("28-05-1989"), ExamScore = 3.8F },
                    new Student { GroupId = 18, FirstName = "Егор", LastName = "Назаров", DateOfBirth = DateTime.Parse("01-11-1985"), ExamScore = 5F },
                    new Student { GroupId = 18, FirstName = "Василий", LastName = "Алексеев", DateOfBirth = DateTime.Parse("26-02-1985"), ExamScore = 3.9F },
                    new Student { GroupId = 18, FirstName = "Дмитрий", LastName = "Лобанов", DateOfBirth = DateTime.Parse("09-01-1985"), ExamScore = 4.4F },
                    new Student { GroupId = 18, FirstName = "Вероника", LastName = "Орехова", DateOfBirth = DateTime.Parse("06-07-1994"), ExamScore = 4.7F },
                    new Student { GroupId = 18, FirstName = "Анастасия", LastName = "Коновалова", DateOfBirth = DateTime.Parse("29-04-1991"), ExamScore = 3.2F },
                    new Student { GroupId = 18, FirstName = "Лев", LastName = "Васильев", DateOfBirth = DateTime.Parse("14-01-2000"), ExamScore = 3.3F },
                    new Student { GroupId = 18, FirstName = "Виктория", LastName = "Митрофанова", DateOfBirth = DateTime.Parse("22-09-1985"), ExamScore = 4.7F },
                    new Student { GroupId = 18, FirstName = "Юлия", LastName = "Новикова", DateOfBirth = DateTime.Parse("24-03-1995"), ExamScore = 4.2F },
                    new Student { GroupId = 18, FirstName = "Максим", LastName = "Кузнецов", DateOfBirth = DateTime.Parse("20-12-1990"), ExamScore = 4.2F },
                    new Student { GroupId = 18, FirstName = "Александр", LastName = "Гусев", DateOfBirth = DateTime.Parse("12-08-1994"), ExamScore = 3.6F },
                    new Student { GroupId = 18, FirstName = "Оливия", LastName = "Маркина", DateOfBirth = DateTime.Parse("22-10-2000"), ExamScore = 3.5F },
                    new Student { GroupId = 18, FirstName = "Антон", LastName = "Овчинников", DateOfBirth = DateTime.Parse("12-12-1989"), ExamScore = 4F },
                    new Student { GroupId = 18, FirstName = "Александр", LastName = "Яковлев", DateOfBirth = DateTime.Parse("04-11-1995"), ExamScore = 5F },
                    new Student { GroupId = 18, FirstName = "Юлия", LastName = "Михеева", DateOfBirth = DateTime.Parse("01-07-1992"), ExamScore = 4.3F },
                    new Student { GroupId = 18, FirstName = "Алексей", LastName = "Смирнов", DateOfBirth = DateTime.Parse("03-09-1985"), ExamScore = 3.3F },
                    new Student { GroupId = 18, FirstName = "Мелисса", LastName = "Ермакова", DateOfBirth = DateTime.Parse("05-11-1987"), ExamScore = 3.4F },
                    new Student { GroupId = 18, FirstName = "Тигран", LastName = "Ермаков", DateOfBirth = DateTime.Parse("15-01-2000"), ExamScore = 3.9F },
                    new Student { GroupId = 18, FirstName = "Диана", LastName = "Королева", DateOfBirth = DateTime.Parse("06-03-2000"), ExamScore = 5F },
                    new Student { GroupId = 19, FirstName = "Григорий", LastName = "Николаев", DateOfBirth = DateTime.Parse("08-08-2000"), ExamScore = 3F },
                    new Student { GroupId = 19, FirstName = "Артём", LastName = "Кузьмин", DateOfBirth = DateTime.Parse("02-01-1999"), ExamScore = 3.9F },
                    new Student { GroupId = 19, FirstName = "Варвара", LastName = "Николаева", DateOfBirth = DateTime.Parse("24-09-1993"), ExamScore = 3.8F },
                    new Student { GroupId = 19, FirstName = "Виктория", LastName = "Казакова", DateOfBirth = DateTime.Parse("10-09-1990"), ExamScore = 4.4F },
                    new Student { GroupId = 19, FirstName = "Александр", LastName = "Васильев", DateOfBirth = DateTime.Parse("02-09-2001"), ExamScore = 4.8F },
                    new Student { GroupId = 19, FirstName = "Софья", LastName = "Трофимова", DateOfBirth = DateTime.Parse("31-08-1994"), ExamScore = 4.3F },
                    new Student { GroupId = 19, FirstName = "София", LastName = "Рожкова", DateOfBirth = DateTime.Parse("17-05-1998"), ExamScore = 4.5F },
                    new Student { GroupId = 19, FirstName = "Платон", LastName = "Третьяков", DateOfBirth = DateTime.Parse("25-08-1996"), ExamScore = 3.7F },
                    new Student { GroupId = 19, FirstName = "Ника", LastName = "Ильинская", DateOfBirth = DateTime.Parse("17-06-1994"), ExamScore = 3.6F },
                    new Student { GroupId = 19, FirstName = "Эмилия", LastName = "Кононова", DateOfBirth = DateTime.Parse("18-02-1998"), ExamScore = 4.5F },
                    new Student { GroupId = 19, FirstName = "Михаил", LastName = "Иванов", DateOfBirth = DateTime.Parse("06-12-1999"), ExamScore = 3.5F },
                    new Student { GroupId = 19, FirstName = "Ксения", LastName = "Богданова", DateOfBirth = DateTime.Parse("01-04-1998"), ExamScore = 4.6F },
                    new Student { GroupId = 19, FirstName = "Екатерина", LastName = "Давыдова", DateOfBirth = DateTime.Parse("20-11-1986"), ExamScore = 3.1F },
                    new Student { GroupId = 19, FirstName = "Ольга", LastName = "Герасимова", DateOfBirth = DateTime.Parse("07-07-1998"), ExamScore = 3.2F },
                    new Student { GroupId = 19, FirstName = "Даниэль", LastName = "Козловский", DateOfBirth = DateTime.Parse("05-04-1997"), ExamScore = 4.8F },
                    new Student { GroupId = 19, FirstName = "Дарья", LastName = "Горячева", DateOfBirth = DateTime.Parse("16-07-1996"), ExamScore = 3.3F },
                    new Student { GroupId = 19, FirstName = "Мирон", LastName = "Архипов", DateOfBirth = DateTime.Parse("30-05-1992"), ExamScore = 4.6F },
                    new Student { GroupId = 19, FirstName = "Даниил", LastName = "Колесов", DateOfBirth = DateTime.Parse("20-11-1991"), ExamScore = 3.6F },
                    new Student { GroupId = 20, FirstName = "Роман", LastName = "Корнев", DateOfBirth = DateTime.Parse("27-03-1988"), ExamScore = 4.3F },
                    new Student { GroupId = 20, FirstName = "Милана", LastName = "Голубева", DateOfBirth = DateTime.Parse("13-09-1992"), ExamScore = 4.8F },
                    new Student { GroupId = 20, FirstName = "Фёдор", LastName = "Романов", DateOfBirth = DateTime.Parse("18-03-2000"), ExamScore = 5F },
                    new Student { GroupId = 20, FirstName = "Эмин", LastName = "Зимин", DateOfBirth = DateTime.Parse("22-11-1996"), ExamScore = 3.2F },
                    new Student { GroupId = 20, FirstName = "Елизавета", LastName = "Емельянова", DateOfBirth = DateTime.Parse("29-09-1998"), ExamScore = 4.5F },
                    new Student { GroupId = 20, FirstName = "Екатерина", LastName = "Ефимова", DateOfBirth = DateTime.Parse("13-02-1987"), ExamScore = 3.9F },
                    new Student { GroupId = 20, FirstName = "Ева", LastName = "Щербакова", DateOfBirth = DateTime.Parse("10-02-1989"), ExamScore = 3.8F },
                    new Student { GroupId = 20, FirstName = "Дмитрий", LastName = "Гусев", DateOfBirth = DateTime.Parse("16-06-1995"), ExamScore = 4.2F },
                    new Student { GroupId = 20, FirstName = "Ольга", LastName = "Трофимова", DateOfBirth = DateTime.Parse("03-01-2001"), ExamScore = 4.8F },
                    new Student { GroupId = 20, FirstName = "Олеся", LastName = "Гаврилова", DateOfBirth = DateTime.Parse("15-07-1999"), ExamScore = 3.7F },
                    new Student { GroupId = 20, FirstName = "Алия", LastName = "Сомова", DateOfBirth = DateTime.Parse("13-09-1991"), ExamScore = 4.8F },
                    new Student { GroupId = 20, FirstName = "Леон", LastName = "Белоусов", DateOfBirth = DateTime.Parse("28-08-1985"), ExamScore = 3.9F },
                    new Student { GroupId = 20, FirstName = "Виктория", LastName = "Ершова", DateOfBirth = DateTime.Parse("17-08-1995"), ExamScore = 3.2F },
                    new Student { GroupId = 20, FirstName = "Никита", LastName = "Иванов", DateOfBirth = DateTime.Parse("14-05-2000"), ExamScore = 3.3F },
                    new Student { GroupId = 20, FirstName = "Марк", LastName = "Никитин", DateOfBirth = DateTime.Parse("20-08-1996"), ExamScore = 4.1F },
                    new Student { GroupId = 20, FirstName = "Александр", LastName = "Афанасьев", DateOfBirth = DateTime.Parse("04-04-1985"), ExamScore = 4F },
                    new Student { GroupId = 20, FirstName = "Мирослава", LastName = "Захарова", DateOfBirth = DateTime.Parse("28-05-1996"), ExamScore = 3.4F },
                    new Student { GroupId = 20, FirstName = "София", LastName = "Зимина", DateOfBirth = DateTime.Parse("07-01-1999"), ExamScore = 4.6F },
                    new Student { GroupId = 20, FirstName = "Виктория", LastName = "Козлова", DateOfBirth = DateTime.Parse("26-04-1985"), ExamScore = 3.8F },
                    new Student { GroupId = 21, FirstName = "Софья", LastName = "Панова", DateOfBirth = DateTime.Parse("06-10-1986"), ExamScore = 4.1F },
                    new Student { GroupId = 21, FirstName = "Василиса", LastName = "Смирнова", DateOfBirth = DateTime.Parse("27-09-1998"), ExamScore = 4F },
                    new Student { GroupId = 21, FirstName = "Яна", LastName = "Семина", DateOfBirth = DateTime.Parse("30-11-2001"), ExamScore = 4.6F },
                    new Student { GroupId = 21, FirstName = "Всеволод", LastName = "Тихонов", DateOfBirth = DateTime.Parse("10-12-1996"), ExamScore = 3.8F },
                    new Student { GroupId = 21, FirstName = "Дмитрий", LastName = "Горбачев", DateOfBirth = DateTime.Parse("27-06-1991"), ExamScore = 3.2F },
                    new Student { GroupId = 21, FirstName = "Софья", LastName = "Смирнова", DateOfBirth = DateTime.Parse("15-09-1989"), ExamScore = 4.7F },
                    new Student { GroupId = 21, FirstName = "Полина", LastName = "Чеботарева", DateOfBirth = DateTime.Parse("12-08-1994"), ExamScore = 4.1F },
                    new Student { GroupId = 21, FirstName = "Анастасия", LastName = "Григорьева", DateOfBirth = DateTime.Parse("08-04-1988"), ExamScore = 4.7F },
                    new Student { GroupId = 21, FirstName = "Иван", LastName = "Мартынов", DateOfBirth = DateTime.Parse("11-05-2001"), ExamScore = 3.5F },
                    new Student { GroupId = 21, FirstName = "Максим", LastName = "Суслов", DateOfBirth = DateTime.Parse("16-06-1994"), ExamScore = 3.9F },
                    new Student { GroupId = 21, FirstName = "Екатерина", LastName = "Беляева", DateOfBirth = DateTime.Parse("01-02-1986"), ExamScore = 3F },
                    new Student { GroupId = 21, FirstName = "Дмитрий", LastName = "Герасимов", DateOfBirth = DateTime.Parse("28-12-2000"), ExamScore = 3.9F },
                    new Student { GroupId = 21, FirstName = "Фёдор", LastName = "Иванов", DateOfBirth = DateTime.Parse("27-01-1998"), ExamScore = 4.8F },
                    new Student { GroupId = 21, FirstName = "Анна", LastName = "Иванова", DateOfBirth = DateTime.Parse("13-08-1987"), ExamScore = 3F },
                    new Student { GroupId = 21, FirstName = "Алиса", LastName = "Никитина", DateOfBirth = DateTime.Parse("06-01-1993"), ExamScore = 4.3F },
                    new Student { GroupId = 21, FirstName = "Никита", LastName = "Молчанов", DateOfBirth = DateTime.Parse("12-08-1993"), ExamScore = 3.3F },
                    new Student { GroupId = 21, FirstName = "Василиса", LastName = "Шарова", DateOfBirth = DateTime.Parse("30-09-1994"), ExamScore = 4.9F },
                    new Student { GroupId = 21, FirstName = "Артём", LastName = "Михайлов", DateOfBirth = DateTime.Parse("26-06-2001"), ExamScore = 3.2F },
                    new Student { GroupId = 21, FirstName = "Дмитрий", LastName = "Кошелев", DateOfBirth = DateTime.Parse("10-04-1998"), ExamScore = 3.1F },
                    new Student { GroupId = 21, FirstName = "Ярослав", LastName = "Черепанов", DateOfBirth = DateTime.Parse("21-06-1988"), ExamScore = 3.7F },
                    new Student { GroupId = 22, FirstName = "Павел", LastName = "Васильев", DateOfBirth = DateTime.Parse("07-10-1987"), ExamScore = 3.7F },
                    new Student { GroupId = 22, FirstName = "Игорь", LastName = "Лапшин", DateOfBirth = DateTime.Parse("24-08-1993"), ExamScore = 3.5F },
                    new Student { GroupId = 22, FirstName = "Богдан", LastName = "Ситников", DateOfBirth = DateTime.Parse("05-11-2001"), ExamScore = 4.6F },
                    new Student { GroupId = 22, FirstName = "Ева", LastName = "Кольцова", DateOfBirth = DateTime.Parse("21-06-1996"), ExamScore = 4.8F },
                    new Student { GroupId = 22, FirstName = "Алиса", LastName = "Терентьева", DateOfBirth = DateTime.Parse("05-05-1997"), ExamScore = 4.9F },
                    new Student { GroupId = 22, FirstName = "Милана", LastName = "Новикова", DateOfBirth = DateTime.Parse("11-04-1994"), ExamScore = 3.2F },
                    new Student { GroupId = 22, FirstName = "Елизавета", LastName = "Иванова", DateOfBirth = DateTime.Parse("08-12-1994"), ExamScore = 3.2F },
                    new Student { GroupId = 22, FirstName = "Кирилл", LastName = "Соколов", DateOfBirth = DateTime.Parse("18-05-1988"), ExamScore = 4.4F },
                    new Student { GroupId = 22, FirstName = "Камила", LastName = "Трифонова", DateOfBirth = DateTime.Parse("14-08-1989"), ExamScore = 3.7F },
                    new Student { GroupId = 22, FirstName = "Вероника", LastName = "Григорьева", DateOfBirth = DateTime.Parse("05-07-1997"), ExamScore = 4.3F },
                    new Student { GroupId = 22, FirstName = "Всеволод", LastName = "Орлов", DateOfBirth = DateTime.Parse("10-06-2001"), ExamScore = 4.4F },
                    new Student { GroupId = 22, FirstName = "Елизавета", LastName = "Золотова", DateOfBirth = DateTime.Parse("11-02-1991"), ExamScore = 4.6F },
                    new Student { GroupId = 22, FirstName = "Алиса", LastName = "Гончарова", DateOfBirth = DateTime.Parse("20-01-1986"), ExamScore = 4.9F },
                    new Student { GroupId = 22, FirstName = "Тимофей", LastName = "Николаев", DateOfBirth = DateTime.Parse("10-10-1996"), ExamScore = 3.1F },
                    new Student { GroupId = 22, FirstName = "Дмитрий", LastName = "Быков", DateOfBirth = DateTime.Parse("20-09-1994"), ExamScore = 3.3F },
                    new Student { GroupId = 22, FirstName = "Милана", LastName = "Игнатова", DateOfBirth = DateTime.Parse("23-08-1988"), ExamScore = 4.7F },
                    new Student { GroupId = 22, FirstName = "Яна", LastName = "Ершова", DateOfBirth = DateTime.Parse("02-06-2001"), ExamScore = 3.7F },
                    new Student { GroupId = 22, FirstName = "Вероника", LastName = "Соколова", DateOfBirth = DateTime.Parse("08-04-1995"), ExamScore = 4.9F },
                    new Student { GroupId = 22, FirstName = "Агния", LastName = "Попова", DateOfBirth = DateTime.Parse("23-06-1996"), ExamScore = 4.1F },
                    new Student { GroupId = 22, FirstName = "Алексей", LastName = "Кулешов", DateOfBirth = DateTime.Parse("16-07-1995"), ExamScore = 4.8F },
                    new Student { GroupId = 23, FirstName = "Лука", LastName = "Фролов", DateOfBirth = DateTime.Parse("25-03-1986"), ExamScore = 4.3F },
                    new Student { GroupId = 23, FirstName = "Евгения", LastName = "Медведева", DateOfBirth = DateTime.Parse("16-03-1996"), ExamScore = 5F },
                    new Student { GroupId = 23, FirstName = "Василиса", LastName = "Иванова", DateOfBirth = DateTime.Parse("31-03-1991"), ExamScore = 3.1F },
                    new Student { GroupId = 23, FirstName = "Данил", LastName = "Сергеев", DateOfBirth = DateTime.Parse("05-03-1986"), ExamScore = 3.2F },
                    new Student { GroupId = 23, FirstName = "София", LastName = "Лазарева", DateOfBirth = DateTime.Parse("17-03-1996"), ExamScore = 4.2F },
                    new Student { GroupId = 23, FirstName = "Кристина", LastName = "Павлова", DateOfBirth = DateTime.Parse("07-05-1994"), ExamScore = 3.6F },
                    new Student { GroupId = 23, FirstName = "Денис", LastName = "Васильев", DateOfBirth = DateTime.Parse("26-08-1990"), ExamScore = 4.7F },
                    new Student { GroupId = 23, FirstName = "Савелий", LastName = "Орлов", DateOfBirth = DateTime.Parse("14-03-1987"), ExamScore = 3.4F },
                    new Student { GroupId = 23, FirstName = "Злата", LastName = "Попова", DateOfBirth = DateTime.Parse("03-06-1995"), ExamScore = 3.2F },
                    new Student { GroupId = 23, FirstName = "Анна", LastName = "Латышева", DateOfBirth = DateTime.Parse("08-09-1992"), ExamScore = 3.6F },
                    new Student { GroupId = 23, FirstName = "Тимофей", LastName = "Родин", DateOfBirth = DateTime.Parse("19-05-2000"), ExamScore = 4.3F },
                    new Student { GroupId = 23, FirstName = "Андрей", LastName = "Никифоров", DateOfBirth = DateTime.Parse("17-05-1986"), ExamScore = 3.5F },
                    new Student { GroupId = 23, FirstName = "Ясмина", LastName = "Потапова", DateOfBirth = DateTime.Parse("21-11-1995"), ExamScore = 4.3F },
                    new Student { GroupId = 23, FirstName = "Анна", LastName = "Кондратова", DateOfBirth = DateTime.Parse("02-10-1999"), ExamScore = 4.9F },
                    new Student { GroupId = 23, FirstName = "Артур", LastName = "Майоров", DateOfBirth = DateTime.Parse("22-01-1999"), ExamScore = 3.8F },
                    new Student { GroupId = 23, FirstName = "Екатерина", LastName = "Беляева", DateOfBirth = DateTime.Parse("16-03-1992"), ExamScore = 3.8F },
                    new Student { GroupId = 24, FirstName = "Эвелина", LastName = "Белоусова", DateOfBirth = DateTime.Parse("11-11-1997"), ExamScore = 3.2F },
                    new Student { GroupId = 24, FirstName = "Амина", LastName = "Овчинникова", DateOfBirth = DateTime.Parse("10-01-1991"), ExamScore = 4.7F },
                    new Student { GroupId = 24, FirstName = "Эмма", LastName = "Шевцова", DateOfBirth = DateTime.Parse("26-03-1999"), ExamScore = 4.5F },
                    new Student { GroupId = 24, FirstName = "Всеволод", LastName = "Виноградов", DateOfBirth = DateTime.Parse("05-10-1989"), ExamScore = 3F },
                    new Student { GroupId = 24, FirstName = "Максим", LastName = "Жуков", DateOfBirth = DateTime.Parse("20-06-1997"), ExamScore = 4.3F },
                    new Student { GroupId = 24, FirstName = "Леон", LastName = "Воронин", DateOfBirth = DateTime.Parse("10-11-1988"), ExamScore = 4.7F },
                    new Student { GroupId = 24, FirstName = "Андрей", LastName = "Егоров", DateOfBirth = DateTime.Parse("31-12-2001"), ExamScore = 5F },
                    new Student { GroupId = 24, FirstName = "Александра", LastName = "Кольцова", DateOfBirth = DateTime.Parse("04-08-1997"), ExamScore = 3.1F },
                    new Student { GroupId = 24, FirstName = "Михаил", LastName = "Денисов", DateOfBirth = DateTime.Parse("28-08-1993"), ExamScore = 3.9F },
                    new Student { GroupId = 24, FirstName = "Алиса", LastName = "Давыдова", DateOfBirth = DateTime.Parse("04-03-1996"), ExamScore = 3.4F },
                    new Student { GroupId = 24, FirstName = "Александр", LastName = "Наумов", DateOfBirth = DateTime.Parse("10-08-1987"), ExamScore = 3.1F },
                    new Student { GroupId = 24, FirstName = "Савелий", LastName = "Воронин", DateOfBirth = DateTime.Parse("29-07-1992"), ExamScore = 4.4F },
                    new Student { GroupId = 24, FirstName = "Дарья", LastName = "Березина", DateOfBirth = DateTime.Parse("10-03-1995"), ExamScore = 4.1F },
                    new Student { GroupId = 24, FirstName = "Сара", LastName = "Чеботарева", DateOfBirth = DateTime.Parse("22-08-1987"), ExamScore = 4.5F },
                    new Student { GroupId = 24, FirstName = "Василиса", LastName = "Михайлова", DateOfBirth = DateTime.Parse("26-09-2001"), ExamScore = 3.3F },
                    new Student { GroupId = 24, FirstName = "Мия", LastName = "Винокурова", DateOfBirth = DateTime.Parse("27-05-1993"), ExamScore = 3.8F },
                    new Student { GroupId = 24, FirstName = "Вероника", LastName = "Беспалова", DateOfBirth = DateTime.Parse("21-08-1995"), ExamScore = 3F },
                    new Student { GroupId = 24, FirstName = "Дмитрий", LastName = "Яшин", DateOfBirth = DateTime.Parse("20-01-1999"), ExamScore = 3.3F },
                    new Student { GroupId = 24, FirstName = "Василиса", LastName = "Сергеева", DateOfBirth = DateTime.Parse("25-03-1995"), ExamScore = 3.4F },
                    new Student { GroupId = 25, FirstName = "Александра", LastName = "Сидорова", DateOfBirth = DateTime.Parse("20-02-1985"), ExamScore = 3.2F },
                    new Student { GroupId = 25, FirstName = "Олег", LastName = "Лобанов", DateOfBirth = DateTime.Parse("01-12-1997"), ExamScore = 3.6F },
                    new Student { GroupId = 25, FirstName = "Фёдор", LastName = "Ермолов", DateOfBirth = DateTime.Parse("12-10-1995"), ExamScore = 4F },
                    new Student { GroupId = 25, FirstName = "Михаил", LastName = "Чернов", DateOfBirth = DateTime.Parse("02-08-1997"), ExamScore = 4.6F },
                    new Student { GroupId = 25, FirstName = "Александр", LastName = "Михайлов", DateOfBirth = DateTime.Parse("15-01-1991"), ExamScore = 4.7F },
                    new Student { GroupId = 25, FirstName = "Тимофей", LastName = "Смирнов", DateOfBirth = DateTime.Parse("26-06-2000"), ExamScore = 3.5F },
                    new Student { GroupId = 25, FirstName = "Екатерина", LastName = "Егорова", DateOfBirth = DateTime.Parse("18-06-1995"), ExamScore = 3.2F },
                    new Student { GroupId = 25, FirstName = "Василиса", LastName = "Соколова", DateOfBirth = DateTime.Parse("27-08-1992"), ExamScore = 3.7F },
                    new Student { GroupId = 25, FirstName = "Виктория", LastName = "Рудакова", DateOfBirth = DateTime.Parse("05-10-1996"), ExamScore = 3.1F },
                    new Student { GroupId = 25, FirstName = "Георгий", LastName = "Афанасьев", DateOfBirth = DateTime.Parse("07-01-1987"), ExamScore = 4.6F },
                    new Student { GroupId = 25, FirstName = "Кира", LastName = "Лаврова", DateOfBirth = DateTime.Parse("26-09-1999"), ExamScore = 4F },
                    new Student { GroupId = 25, FirstName = "Руслан", LastName = "Ананьев", DateOfBirth = DateTime.Parse("27-12-1994"), ExamScore = 4.6F },
                    new Student { GroupId = 25, FirstName = "Алиса", LastName = "Никулина", DateOfBirth = DateTime.Parse("16-11-1991"), ExamScore = 4.7F },
                    new Student { GroupId = 25, FirstName = "Валерия", LastName = "Шишкина", DateOfBirth = DateTime.Parse("14-12-1985"), ExamScore = 3.1F },
                    new Student { GroupId = 25, FirstName = "Виктория", LastName = "Короткова", DateOfBirth = DateTime.Parse("12-04-1986"), ExamScore = 4.9F },
                    new Student { GroupId = 25, FirstName = "Дарья", LastName = "Свиридова", DateOfBirth = DateTime.Parse("19-09-2001"), ExamScore = 4.1F },
                    new Student { GroupId = 25, FirstName = "Нина", LastName = "Евдокимова", DateOfBirth = DateTime.Parse("22-12-1994"), ExamScore = 3.5F },
                    new Student { GroupId = 25, FirstName = "Максим", LastName = "Григорьев", DateOfBirth = DateTime.Parse("18-10-2000"), ExamScore = 3.2F },
                    new Student { GroupId = 25, FirstName = "Алиса", LastName = "Смирнова", DateOfBirth = DateTime.Parse("02-12-1985"), ExamScore = 3.1F },
                    new Student { GroupId = 25, FirstName = "Матвей", LastName = "Комаров", DateOfBirth = DateTime.Parse("21-07-1998"), ExamScore = 3.7F },
                    new Student { GroupId = 26, FirstName = "Марк", LastName = "Сергеев", DateOfBirth = DateTime.Parse("30-03-1994"), ExamScore = 3.7F },
                    new Student { GroupId = 26, FirstName = "Варвара", LastName = "Русанова", DateOfBirth = DateTime.Parse("03-03-1987"), ExamScore = 4F },
                    new Student { GroupId = 26, FirstName = "Георгий", LastName = "Титов", DateOfBirth = DateTime.Parse("22-09-2001"), ExamScore = 4.2F },
                    new Student { GroupId = 26, FirstName = "Артур", LastName = "Щеглов", DateOfBirth = DateTime.Parse("19-08-1993"), ExamScore = 4.2F },
                    new Student { GroupId = 26, FirstName = "Милана", LastName = "Высоцкая", DateOfBirth = DateTime.Parse("08-10-1989"), ExamScore = 4.8F },
                    new Student { GroupId = 26, FirstName = "Таисия", LastName = "Полякова", DateOfBirth = DateTime.Parse("04-04-1988"), ExamScore = 3.6F },
                    new Student { GroupId = 26, FirstName = "Егор", LastName = "Беляев", DateOfBirth = DateTime.Parse("30-01-1999"), ExamScore = 4.6F },
                    new Student { GroupId = 26, FirstName = "Алиса", LastName = "Константинова", DateOfBirth = DateTime.Parse("01-08-2001"), ExamScore = 4.6F },
                    new Student { GroupId = 26, FirstName = "Ярослав", LastName = "Миронов", DateOfBirth = DateTime.Parse("05-11-1992"), ExamScore = 4.9F },
                    new Student { GroupId = 26, FirstName = "София", LastName = "Головина", DateOfBirth = DateTime.Parse("31-03-1999"), ExamScore = 4.3F },
                    new Student { GroupId = 26, FirstName = "Алла", LastName = "Захарова", DateOfBirth = DateTime.Parse("12-02-1993"), ExamScore = 3.6F },
                    new Student { GroupId = 26, FirstName = "Амина", LastName = "Семенова", DateOfBirth = DateTime.Parse("22-03-1993"), ExamScore = 4F },
                    new Student { GroupId = 26, FirstName = "Андрей", LastName = "Матвеев", DateOfBirth = DateTime.Parse("11-06-1985"), ExamScore = 4F },
                    new Student { GroupId = 26, FirstName = "Диана", LastName = "Завьялова", DateOfBirth = DateTime.Parse("12-08-1989"), ExamScore = 3.8F },
                    new Student { GroupId = 26, FirstName = "Дарья", LastName = "Тимофеева", DateOfBirth = DateTime.Parse("14-05-1987"), ExamScore = 3.4F },
                    new Student { GroupId = 26, FirstName = "Елизавета", LastName = "Кузнецова", DateOfBirth = DateTime.Parse("28-06-1997"), ExamScore = 3.2F },
                    new Student { GroupId = 26, FirstName = "Анастасия", LastName = "Беляева", DateOfBirth = DateTime.Parse("07-01-1997"), ExamScore = 3.1F },
                    new Student { GroupId = 26, FirstName = "Софья", LastName = "Артамонова", DateOfBirth = DateTime.Parse("30-12-1996"), ExamScore = 4F },
                    new Student { GroupId = 26, FirstName = "Михаил", LastName = "Кузнецов", DateOfBirth = DateTime.Parse("24-11-1991"), ExamScore = 3.2F },
                    new Student { GroupId = 26, FirstName = "Дмитрий", LastName = "Князев", DateOfBirth = DateTime.Parse("13-11-1994"), ExamScore = 4.5F },
                    new Student { GroupId = 27, FirstName = "Сергей", LastName = "Гуляев", DateOfBirth = DateTime.Parse("13-10-1989"), ExamScore = 4.1F },
                    new Student { GroupId = 27, FirstName = "Михаил", LastName = "Попов", DateOfBirth = DateTime.Parse("17-09-1991"), ExamScore = 4.8F },
                    new Student { GroupId = 27, FirstName = "Мария", LastName = "Виноградова", DateOfBirth = DateTime.Parse("06-10-1986"), ExamScore = 4F },
                    new Student { GroupId = 27, FirstName = "Егор", LastName = "Петров", DateOfBirth = DateTime.Parse("15-06-1987"), ExamScore = 4.9F },
                    new Student { GroupId = 27, FirstName = "Милана", LastName = "Михайлова", DateOfBirth = DateTime.Parse("19-10-1999"), ExamScore = 4F },
                    new Student { GroupId = 27, FirstName = "Кирилл", LastName = "Артамонов", DateOfBirth = DateTime.Parse("14-07-1990"), ExamScore = 4.5F },
                    new Student { GroupId = 27, FirstName = "Леонид", LastName = "Орлов", DateOfBirth = DateTime.Parse("14-04-1989"), ExamScore = 3.2F },
                    new Student { GroupId = 27, FirstName = "Василий", LastName = "Смирнов", DateOfBirth = DateTime.Parse("07-06-1995"), ExamScore = 3.4F },
                    new Student { GroupId = 27, FirstName = "Дарья", LastName = "Калинина", DateOfBirth = DateTime.Parse("05-07-1997"), ExamScore = 4.5F },
                    new Student { GroupId = 27, FirstName = "Кира", LastName = "Гусева", DateOfBirth = DateTime.Parse("28-01-1990"), ExamScore = 3.7F },
                    new Student { GroupId = 27, FirstName = "Анна", LastName = "Акимова", DateOfBirth = DateTime.Parse("30-07-1985"), ExamScore = 3.6F },
                    new Student { GroupId = 27, FirstName = "Кристина", LastName = "Евдокимова", DateOfBirth = DateTime.Parse("30-11-1992"), ExamScore = 3F },
                    new Student { GroupId = 27, FirstName = "Матвей", LastName = "Носов", DateOfBirth = DateTime.Parse("11-10-1989"), ExamScore = 4.8F },
                    new Student { GroupId = 27, FirstName = "Агния", LastName = "Смирнова", DateOfBirth = DateTime.Parse("03-07-1998"), ExamScore = 4.8F },
                    new Student { GroupId = 27, FirstName = "Марина", LastName = "Боброва", DateOfBirth = DateTime.Parse("12-01-1999"), ExamScore = 3.1F },
                    new Student { GroupId = 28, FirstName = "Давид", LastName = "Егоров", DateOfBirth = DateTime.Parse("22-03-1989"), ExamScore = 4.2F },
                    new Student { GroupId = 28, FirstName = "Егор", LastName = "Молчанов", DateOfBirth = DateTime.Parse("03-07-1998"), ExamScore = 3.9F },
                    new Student { GroupId = 28, FirstName = "Николай", LastName = "Терехов", DateOfBirth = DateTime.Parse("16-08-1997"), ExamScore = 3F },
                    new Student { GroupId = 28, FirstName = "Кира", LastName = "Журавлева", DateOfBirth = DateTime.Parse("10-06-1999"), ExamScore = 3.6F },
                    new Student { GroupId = 28, FirstName = "Георгий", LastName = "Кузнецов", DateOfBirth = DateTime.Parse("20-04-1987"), ExamScore = 4.4F },
                    new Student { GroupId = 28, FirstName = "Максим", LastName = "Устинов", DateOfBirth = DateTime.Parse("16-07-2001"), ExamScore = 4.7F },
                    new Student { GroupId = 28, FirstName = "Злата", LastName = "Меркулова", DateOfBirth = DateTime.Parse("29-04-1986"), ExamScore = 4F }
                );
                context.SaveChanges();
            }
        }
    }
}
